// Azure neural voices (free tier: 500k characters / month on the F0 plan).
// Short language code -> { locale, voice }. Chosen as warm, clear female
// voices to match the app's conversation partners.
export const azureVoices: Record<string, { locale: string; voice: string }> = {
  en: { locale: 'en-US', voice: 'en-US-JennyNeural' },
  es: { locale: 'es-ES', voice: 'es-ES-ElviraNeural' },
  fr: { locale: 'fr-FR', voice: 'fr-FR-DeniseNeural' },
  de: { locale: 'de-DE', voice: 'de-DE-KatjaNeural' },
  it: { locale: 'it-IT', voice: 'it-IT-ElsaNeural' },
  ja: { locale: 'ja-JP', voice: 'ja-JP-NanamiNeural' },
  ko: { locale: 'ko-KR', voice: 'ko-KR-SunHiNeural' },
  zh: { locale: 'zh-CN', voice: 'zh-CN-XiaoxiaoNeural' },
  hi: { locale: 'hi-IN', voice: 'hi-IN-SwaraNeural' },
  ar: { locale: 'ar-EG', voice: 'ar-EG-SalmaNeural' },
  he: { locale: 'he-IL', voice: 'he-IL-HilaNeural' },
  ru: { locale: 'ru-RU', voice: 'ru-RU-SvetlanaNeural' },
  pt: { locale: 'pt-BR', voice: 'pt-BR-FranciscaNeural' },
  tr: { locale: 'tr-TR', voice: 'tr-TR-EmelNeural' },
  vi: { locale: 'vi-VN', voice: 'vi-VN-HoaiMyNeural' },
  pl: { locale: 'pl-PL', voice: 'pl-PL-ZofiaNeural' },
  nl: { locale: 'nl-NL', voice: 'nl-NL-ColetteNeural' },
  sv: { locale: 'sv-SE', voice: 'sv-SE-SofieNeural' },
  no: { locale: 'nb-NO', voice: 'nb-NO-IselinNeural' },
  da: { locale: 'da-DK', voice: 'da-DK-ChristelNeural' },
  fi: { locale: 'fi-FI', voice: 'fi-FI-NooraNeural' },
  el: { locale: 'el-GR', voice: 'el-GR-AthinaNeural' },
  th: { locale: 'th-TH', voice: 'th-TH-PremwadeeNeural' },
  id: { locale: 'id-ID', voice: 'id-ID-GadisNeural' },
  ms: { locale: 'ms-MY', voice: 'ms-MY-YasminNeural' },
  uk: { locale: 'uk-UA', voice: 'uk-UA-PolinaNeural' },
  cs: { locale: 'cs-CZ', voice: 'cs-CZ-VlastaNeural' },
  ro: { locale: 'ro-RO', voice: 'ro-RO-AlinaNeural' },
  hu: { locale: 'hu-HU', voice: 'hu-HU-NoemiNeural' },
  bn: { locale: 'bn-IN', voice: 'bn-IN-TanishaaNeural' },
  mr: { locale: 'mr-IN', voice: 'mr-IN-AarohiNeural' },
  gu: { locale: 'gu-IN', voice: 'gu-IN-DhwaniNeural' },
  as: { locale: 'as-IN', voice: 'as-IN-YashicaNeural' },
  ml: { locale: 'ml-IN', voice: 'ml-IN-SobhanaNeural' },
  kn: { locale: 'kn-IN', voice: 'kn-IN-SapnaNeural' },
};
