// Auto-extracted from prototype
export const LANGS: any = {
      es: {
        name: "Spanish", flag: "🇪🇸", code: "ES", font: "", locale: "es-ES",
        greeting: "Buenos días, Maya", chapter: "Café culture", cultureTeaser: "Why Spaniards linger",
        goalLine: "Order a coffee and make small talk.", goalShort: "order a coffee", accent: "Spain (Castilian)",
        partnerName: "Lucía", partnerInitial: "L", partnerRole: "barista", partnerPlace: "Madrid café",
        scenarioTitle: "At the café · Madrid", scenarioSub: "Roleplay · order a coffee & small talk",
        lessonPromptEn: "I'd like a coffee with milk, please.", lessonHint: "Why “con”?",
        bank: ["Quería", "un café", "con leche", "por favor", "la cuenta", "sin"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "¡Perfecto! 🎉",
        lessonCorrectBody: "“Quería” is the polite, softened way to order — literally “I wanted.”",
        lessonWrongBody: "Start with the polite verb, then what you want.",
        cultureCaption: "A café in Sevilla · 11am", cultureTitle: "A coffee is never just a coffee",
        cultureBody: "In Spain, ordering “para llevar” (to go) is rare — coffee is a moment to sit, not fuel to grab. Lingering is the point, and no waiter will rush you.",
        culturePhrase: "“¿Me cobras?” — how locals ask for the bill, instead of waving.",
        milestoneTitle: "You can now order a coffee — and chat while you do.",
        convo: [
          { who: "p", n: "¿Qué te pongo, guapa?", en: "What can I get you, dear?" },
          { who: "u", n: "Un café con leche, por favor.", fb: "Nice — try adding “para llevar”" },
          { who: "p", n: "¡Marchando! ¿Algo más?", en: "Coming right up! Anything else?" },
          { who: "u", n: "No, gracias. ¿Me cobras?", fb: "Perfect — locals ask for the bill this way" },
          { who: "p", n: "Claro, son dos euros.", en: "Of course — that's two euros." }
        ],
        debrief: [
          { title: "“para yevar” → “para llevar”", body: "Your “ll” sounded like a soft y — in Spain it's a firmer “ly.”" },
          { title: "More natural: “¿Me cobras?”", body: "“la cuenta” works, but locals shorten it in a café." }
        ],
        clip: "La Tomatina, explicada por los locales", podcast: "Café con Mateo — ep. 4", article: "El secreto del café con hielo",
        reader: [
          { t: "En el sur de España, cuando hace calor, mucha gente pide un " },
          { w: "café con hielo", d: "iced coffee — hot coffee served with a glass of ice on the side" },
          { t: ". El camarero trae un café caliente y un vaso " },
          { w: "aparte", d: "adv. · separate, on the side" },
          { t: " lleno de hielo. Tú mismo lo " },
          { w: "mezclas", d: "you mix (from mezclar — to mix)" },
          { t: ". Es un pequeño ritual del verano andaluz." }
        ],
        grammarMini: "por vs para", grammarTitle: "“por” vs “para” — the 10-second rule",
        grammarIntro: "Both become “for” in English. The split is simpler than it looks:",
        gTermA: "por", gDescA: "cause / reason — “because of”", gExA: "Gracias por el café.",
        gTermB: "para", gDescB: "goal / destination — “in order to”", gExB: "Un café para llevar.",
        reviewWord: "llevar", reviewSource: "from your café conversation, 4 days ago", reviewMeaning: "to carry / to take (away)"
      },
      fr: {
        name: "French", flag: "🇫🇷", code: "FR", font: "", locale: "fr-FR",
        greeting: "Bonjour, Maya", chapter: "Au café", cultureTeaser: "Greet before you order",
        goalLine: "Order a coffee — the polite, French way.", goalShort: "order a coffee", accent: "France (Parisian)",
        partnerName: "Camille", partnerInitial: "C", partnerRole: "serveur", partnerPlace: "Paris café",
        scenarioTitle: "Au café · Paris", scenarioSub: "Roleplay · order & a little small talk",
        lessonPromptEn: "I'd like a coffee with milk, please.", lessonHint: "Why “au lait”?",
        bank: ["Je voudrais", "un café", "au lait", "s'il vous plaît", "l'addition", "sans"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "Parfait ! 🎉",
        lessonCorrectBody: "“Je voudrais” (I would like) is the polite order — softer than “Je veux” (I want).",
        lessonWrongBody: "Start with the polite “I would like,” then what you want.",
        cultureCaption: "A café in Paris · 10am", cultureTitle: "The café is the living room of France",
        cultureBody: "In France you greet before you order — a quick “Bonjour” is non-negotiable. Skip it and you'll feel the chill. One coffee buys you the table for as long as you like.",
        culturePhrase: "“L'addition, s'il vous plaît” — catch the waiter's eye; never snap or wave.",
        milestoneTitle: "You can now order a coffee — politely, the French way.",
        convo: [
          { who: "p", n: "Bonjour ! Qu'est-ce que je vous sers ?", en: "Hello! What can I get you?" },
          { who: "u", n: "Un café au lait, s'il vous plaît.", fb: "Great — you greeted first, very French" },
          { who: "p", n: "Très bien. Ce sera tout ?", en: "Very good. Will that be all?" },
          { who: "u", n: "Oui. L'addition, s'il vous plaît.", fb: "Perfect — polite and natural" },
          { who: "p", n: "Bien sûr, deux euros cinquante.", en: "Of course — two fifty." }
        ],
        debrief: [
          { title: "“Bonjour” comes first", body: "Greet before ordering — in France it's never optional." },
          { title: "Use formal “vous”", body: "With a waiter you don't know, use “vous,” not “tu.”" }
        ],
        clip: "Le marché de Bastille, en vrai", podcast: "Un café avec Camille — ép. 4", article: "Le petit rituel du café parisien",
        reader: [
          { t: "À Paris, beaucoup de gens prennent leur café debout, " },
          { w: "au comptoir", d: "at the counter — cheaper than sitting at a table" },
          { t: ". Le serveur vous dit " },
          { w: "bonjour", d: "hello / good day — always say it first" },
          { t: " avant tout. On reste, on observe, on " },
          { w: "discute", d: "chats (from discuter — to chat / discuss)" },
          { t: ". Le café, c'est une pause, pas une course." }
        ],
        grammarMini: "tu vs vous", grammarTitle: "“tu” vs “vous” — who gets which",
        grammarIntro: "French has two words for “you.” Pick wrong and you sound too familiar — or too cold:",
        gTermA: "tu", gDescA: "informal — friends, family, kids", gExA: "Tu veux un café ?",
        gTermB: "vous", gDescB: "formal / plural — strangers, elders", gExB: "Vous voulez un café ?",
        reviewWord: "comptoir", reviewSource: "from your café article, 2 days ago", reviewMeaning: "counter / bar (where you stand to drink)"
      },
      hi: {
        name: "Hindi", flag: "🇮🇳", code: "HI", font: "hi", locale: "hi-IN",
        greeting: "नमस्ते, Maya", chapter: "चाय Chai culture", cultureTeaser: "Chai is a ritual",
        goalLine: "Order chai and make small talk.", goalShort: "order chai", accent: "India (Delhi)",
        partnerName: "रवि Ravi", partnerInitial: "R", partnerRole: "chai wala", partnerPlace: "Delhi tea stall",
        scenarioTitle: "चाय की दुकान · Delhi", scenarioSub: "Roleplay · order chai & chat",
        lessonPromptEn: "I'd like one tea, please.", lessonHint: "Why “मुझे … चाहिए”?",
        bank: ["मुझे", "एक", "चाय", "चाहिए", "पानी", "दो"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "बहुत बढ़िया! 🎉",
        lessonCorrectBody: "“मुझे … चाहिए” is the natural “I'd like” — literally “to me … is wanted.”",
        lessonWrongBody: "Start with “मुझे” (to me), then how many, then the item, then “चाहिए.”",
        cultureCaption: "A chai stall in Old Delhi · morning", cultureTitle: "Chai is a pause, and an invitation",
        cultureBody: "Across India, chai isn't just a drink — it's how you make a friend, close a deal, or take a breath. At a roadside stall you stand, sip from a small glass, and chat with strangers. Refusing an offered chai can feel like refusing the friendship.",
        culturePhrase: "“कितने का है?” (kitne ka hai?) — “how much is it?”, the phrase you'll use everywhere.",
        milestoneTitle: "You can now order chai — and chat while it brews.",
        convo: [
          { who: "p", n: "नमस्ते! क्या लेंगे आप?", en: "Hello! What will you have?" },
          { who: "u", n: "मुझे एक चाय चाहिए।", fb: "Nice — “मुझे … चाहिए” is very natural" },
          { who: "p", n: "अदरक वाली या साधारण?", en: "Ginger or plain?" },
          { who: "u", n: "अदरक वाली, धन्यवाद।", fb: "Perfect — “अदरक वाली” = the ginger one" },
          { who: "p", n: "बस दस रुपये।", en: "Just ten rupees." }
        ],
        debrief: [
          { title: "“धन्यवाद” vs “शुक्रिया”", body: "Both mean thanks — “शुक्रिया” sounds warmer and more everyday." },
          { title: "Retroflex “ट”", body: "Your “t” was soft — Hindi “ट” curls the tongue back a touch." }
        ],
        clip: "पुरानी दिल्ली की चाय, लोगों के साथ", podcast: "रवि के साथ चाय — एपिसोड 4", article: "चाय का छोटा सा रिवाज़",
        reader: [
          { t: "भारत में, सुबह की शुरुआत अक्सर एक गरम " },
          { w: "चाय", d: "chai — spiced milk tea" },
          { t: " से होती है। लोग सड़क किनारे खड़े होकर, छोटे गिलास में चाय " },
          { w: "पीते हैं", d: "drink (they drink — from पीना, to drink)" },
          { t: " और एक-दूसरे से " },
          { w: "बातें करते हैं", d: "chat / talk to each other" },
          { t: "। यह दिन का सबसे प्यारा पल है।" }
        ],
        grammarMini: "मुझे … चाहिए", grammarTitle: "“मुझे … चाहिए” — how to say “I want”",
        grammarIntro: "Hindi doesn't say “I want” directly. It says “to me, X is wanted”:",
        gTermA: "मुझे (mujhe)", gDescA: "“to me” — the experiencer", gExA: "मुझे चाय चाहिए।",
        gTermB: "चाहिए (chahiye)", gDescB: "“is wanted / needed” — stays the same", gExB: "मुझे पानी चाहिए।",
        reviewWord: "चाहिए", reviewSource: "from your chai order, 3 days ago", reviewMeaning: "is wanted / needed (used for “I'd like”)"
      },
      ja: {
        name: "Japanese", flag: "🇯🇵", code: "JA", font: "jp", locale: "ja-JP",
        greeting: "おはよう, Maya", chapter: "喫茶店 Kissaten", cultureTeaser: "Quiet is the service",
        goalLine: "Order a coffee — politely, in Japanese.", goalShort: "order a coffee", accent: "Japan (Tokyo)",
        partnerName: "ハルカ Haruka", partnerInitial: "H", partnerRole: "staff", partnerPlace: "Kyoto kissaten",
        scenarioTitle: "喫茶店 · Kyoto", scenarioSub: "Roleplay · order & a polite exchange",
        lessonPromptEn: "A coffee, please. (Please give me a coffee.)", lessonHint: "Why “を”?",
        bank: ["コーヒー", "を", "ください", "お願いします", "一つ", "は"], correct: [0, 1, 2],
        lessonCorrectTitle: "完璧！ (Perfect!) 🎉",
        lessonCorrectBody: "“を” marks the thing you want; “ください” is the polite “please give me.”",
        lessonWrongBody: "Name the item, mark it with “を,” then “ください.”",
        cultureCaption: "A kissaten in Kyoto · morning", cultureTitle: "Silence is service, not rudeness",
        cultureBody: "In a Japanese kissaten the staff won't chat or rush you — quiet, attentive service is the height of politeness. A small bow and “どうも” does the thanking.",
        culturePhrase: "“お願いします (onegaishimasu)” — the all-purpose polite “please” when you hand over your order.",
        milestoneTitle: "You can now order a coffee — politely, in Japanese.",
        convo: [
          { who: "p", n: "いらっしゃいませ。ご注文は？", en: "Welcome! What would you like to order?" },
          { who: "u", n: "コーヒーを一つ、お願いします。", fb: "Great — “一つ (one)” makes it natural" },
          { who: "p", n: "かしこまりました。以上ですか？", en: "Certainly. Is that all?" },
          { who: "u", n: "はい、それで大丈夫です。", fb: "Perfect — “大丈夫です” is a natural “that's fine”" },
          { who: "p", n: "ありがとうございます。", en: "Thank you very much." }
        ],
        debrief: [
          { title: "“一つ” counter", body: "You added “one (一つ)” — counters make Japanese sound fluent, not robotic." },
          { title: "Pitch on “コーヒー”", body: "Stress stayed flat — try a slight drop on “ko-,” closer to native pitch-accent." }
        ],
        clip: "京都の朝、地元の人と", podcast: "ハルカの喫茶店ラジオ #4", article: "喫茶店の静かな時間",
        reader: [
          { t: "日本の" },
          { w: "喫茶店", d: "kissaten — a traditional coffee house" },
          { t: "では、お客さんは" },
          { w: "静かに", d: "quietly (from 静か — quiet / calm)" },
          { t: "コーヒーを楽しみます。店員さんはあまり" },
          { w: "話しません", d: "doesn't talk much (polite negative of 話す — to talk)" },
          { t: "。それがおもてなしです。" }
        ],
        grammarMini: "は vs を", grammarTitle: "“は” vs “を” — topic vs object",
        grammarIntro: "Two little particles that trip up every beginner. The trick:",
        gTermA: "は (wa)", gDescA: "marks the topic — “as for…”", gExA: "コーヒーは好きです。",
        gTermB: "を (o)", gDescB: "marks the object — what the verb acts on", gExB: "コーヒーをください。",
        reviewWord: "ください", reviewSource: "from your kissaten order, 3 days ago", reviewMeaning: "please give me (polite request)"
      },
      ko: {
        name: "Korean", flag: "🇰🇷", code: "KO", font: "kr", locale: "ko-KR",
        greeting: "안녕하세요, Maya", chapter: "카페 Cafe culture", cultureTeaser: "Politeness in the verb",
        goalLine: "Order a coffee — politely, in Korean.", goalShort: "order a coffee", accent: "Korea (Seoul)",
        partnerName: "지은 Jieun", partnerInitial: "J", partnerRole: "barista", partnerPlace: "Seoul cafe",
        scenarioTitle: "카페 · Seoul", scenarioSub: "Roleplay · order & a polite exchange",
        lessonPromptEn: "One coffee, please.", lessonHint: "Why “주세요”?",
        bank: ["커피", "한", "잔", "주세요", "물", "두"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "완벽해요! 🎉",
        lessonCorrectBody: "“주세요” is the polite “please give me”; “한 잔” = “one cup” with the counter 잔.",
        lessonWrongBody: "Name the item, then the count “한 잔,” then “주세요.”",
        cultureCaption: "A cafe in Seoul · afternoon", cultureTitle: "Politeness lives in the verb ending",
        cultureBody: "Korean bakes respect into the grammar itself. Ending a request with “-주세요” keeps you polite with anyone; drop it and you'd sound blunt. Cafés are a second living room — students linger for hours over one americano.",
        culturePhrase: "“여기요!” (yeogiyo!) — a friendly “excuse me / over here!” to get the staff's attention.",
        milestoneTitle: "You can now order a coffee — politely, in Korean.",
        convo: [
          { who: "p", n: "어서 오세요! 주문하시겠어요?", en: "Welcome! Would you like to order?" },
          { who: "u", n: "커피 한 잔 주세요.", fb: "Great — “한 잔” with the counter sounds natural" },
          { who: "p", n: "따뜻한 걸로 드릴까요?", en: "Shall I make it hot?" },
          { who: "u", n: "네, 따뜻한 걸로 주세요.", fb: "Perfect — “걸로” = “the … one”" },
          { who: "p", n: "네, 삼천 원입니다.", en: "Sure — that's 3,000 won." }
        ],
        debrief: [
          { title: "Counter 잔", body: "You used “한 잔” (one cup) — Korean counts almost everything with a counter." },
          { title: "Aspirate 커", body: "“커피” started soft — give the “k” a touch more air for a native sound." }
        ],
        clip: "서울의 아침, 동네 사람들과", podcast: "지은의 카페 라디오 #4", article: "카페에서 보내는 조용한 시간",
        reader: [
          { t: "한국에서 많은 사람들이 " },
          { w: "카페", d: "cafe" },
          { t: "에서 시간을 보냅니다. 학생들은 커피 한 잔으로 몇 시간 동안 " },
          { w: "공부해요", d: "study (polite — from 공부하다, to study)" },
          { t: ". 점원에게는 항상 " },
          { w: "주세요", d: "please give me (polite request ending)" },
          { t: " 라고 말해요. 그것이 예의입니다." }
        ],
        grammarMini: "-주세요", grammarTitle: "“-주세요” — the polite “please”",
        grammarIntro: "Attach 주세요 to a noun (or verb stem) to make a polite request:",
        gTermA: "주세요 (juseyo)", gDescA: "“please give me” — polite, safe with anyone", gExA: "커피 주세요.",
        gTermB: "-요 (yo)", gDescB: "the politeness ending on verbs", gExB: "여기 있어요.",
        reviewWord: "주세요", reviewSource: "from your cafe order, 3 days ago", reviewMeaning: "please give me (polite request)"
      },
      de: {
        name: "German", flag: "🇩🇪", code: "DE", font: "", locale: "de-DE",
        greeting: "Guten Morgen, Maya", chapter: "Im Café", cultureTeaser: "Cash, and a polite Sie",
        goalLine: "Order a coffee — politely, in German.", goalShort: "order a coffee", accent: "Germany (Standard)",
        partnerName: "Lukas", partnerInitial: "L", partnerRole: "Kellner", partnerPlace: "Berlin café",
        scenarioTitle: "Im Café · Berlin", scenarioSub: "Roleplay · order & a little small talk",
        lessonPromptEn: "I'd like a coffee with milk, please.", lessonHint: "Why “mit”?",
        bank: ["Ich hätte gern", "einen Kaffee", "mit Milch", "bitte", "die Rechnung", "ohne"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "Perfekt! 🎉",
        lessonCorrectBody: "“Ich hätte gern” (I'd like) is the polite order — softer than “Ich will” (I want).",
        lessonWrongBody: "Start with the polite “I'd like,” then what you want.",
        cultureCaption: "A café in Berlin · 10am", cultureTitle: "Bring cash, and keep it formal",
        cultureBody: "Many German cafés still prefer cash — don't assume cards. With staff you don't know, use the formal “Sie,” not “du.” And tipping is modest: round up or add a euro, said out loud as you pay.",
        culturePhrase: "“Stimmt so” — “keep the change,” the normal way to tip.",
        milestoneTitle: "You can now order a coffee — politely, in German.",
        convo: [
          { who: "p", n: "Guten Tag! Was darf es sein?", en: "Hello! What would you like?" },
          { who: "u", n: "Ich hätte gern einen Kaffee mit Milch, bitte.", fb: "Great — “Ich hätte gern” is very polite" },
          { who: "p", n: "Gerne. Sonst noch etwas?", en: "Of course. Anything else?" },
          { who: "u", n: "Nein, danke. Die Rechnung, bitte.", fb: "Perfect — natural and polite" },
          { who: "p", n: "Das macht drei Euro.", en: "That'll be three euros." }
        ],
        debrief: [
          { title: "Use formal “Sie”", body: "With staff you don't know, “Sie” is expected — “du” feels too casual." },
          { title: "Accusative “einen”", body: "“einen Kaffee” — masculine nouns take “einen” as the object. You nailed it." }
        ],
        clip: "Der Wochenmarkt in Berlin, mit Einheimischen", podcast: "Kaffee mit Lukas — Folge 4", article: "Das kleine Ritual des deutschen Kaffees",
        reader: [
          { t: "In Deutschland trinken viele Menschen ihren Kaffee in einem " },
          { w: "Café", d: "café" },
          { t: ". Man bestellt höflich und zahlt oft mit " },
          { w: "Bargeld", d: "cash" },
          { t: ". Beim Bezahlen sagt man freundlich " },
          { w: "stimmt so", d: "“keep the change” — the usual way to tip" },
          { t: ". Es ist eine kleine, ruhige Pause am Tag." }
        ],
        grammarMini: "der/die/das", grammarTitle: "“der · die · das” — the three genders",
        grammarIntro: "German nouns are masculine, feminine or neuter — and the article changes as the object:",
        gTermA: "der → den", gDescA: "masculine — becomes “den” as object", gExA: "Ich nehme den Kaffee.",
        gTermB: "die / das", gDescB: "feminine / neuter — stay the same", gExB: "Ich nehme die Milch.",
        reviewWord: "Rechnung", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "the bill / check (feminine: die Rechnung)"
      },
      it: {
        name: "Italian", flag: "🇮🇹", code: "IT", font: "", locale: "it-IT",
        greeting: "Buongiorno, Maya", chapter: "Al bar", cultureTeaser: "Coffee is standing, and quick",
        goalLine: "Order a coffee — the Italian way.", goalShort: "order a coffee", accent: "Italy (Standard)",
        partnerName: "Giulia", partnerInitial: "G", partnerRole: "barista", partnerPlace: "Roma bar",
        scenarioTitle: "Al bar · Roma", scenarioSub: "Roleplay · order & a little small talk",
        lessonPromptEn: "I'd like a coffee with milk, please.", lessonHint: "Why “vorrei”?",
        bank: ["Vorrei", "un caffè", "con latte", "per favore", "il conto", "senza"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "Perfetto! 🎉",
        lessonCorrectBody: "“Vorrei” (I'd like) is the polite order — gentler than “Voglio” (I want).",
        lessonWrongBody: "Start with the polite “I'd like,” then what you want.",
        cultureCaption: "A bar in Roma · 8am", cultureTitle: "Coffee is a quick ritual, standing up",
        cultureBody: "In Italy you drink your espresso “al banco” — standing at the counter, in a minute or two. Sitting at a table can cost double. And never order a cappuccino after 11am: it's a breakfast drink, and locals will notice.",
        culturePhrase: "“Un caffè” means an espresso — ask for “un americano” if you want it long.",
        milestoneTitle: "You can now order a coffee — the Italian way.",
        convo: [
          { who: "p", n: "Buongiorno! Cosa le porto?", en: "Good morning! What can I get you?" },
          { who: "u", n: "Vorrei un caffè con latte, per favore.", fb: "Great — “Vorrei” is polite and natural" },
          { who: "p", n: "Subito. Altro?", en: "Right away. Anything else?" },
          { who: "u", n: "No, grazie. Il conto, per favore.", fb: "Perfect — “il conto” is exactly right" },
          { who: "p", n: "Certo, un euro e dieci.", en: "Of course — one euro ten." }
        ],
        debrief: [
          { title: "“un caffè” = espresso", body: "If you want a longer coffee, say “un americano” — “un caffè” is always an espresso." },
          { title: "Stress on caffè", body: "The accent falls on the last syllable: caf-FÈ — you had it." }
        ],
        clip: "Il mercato di Campo de' Fiori, dal vivo", podcast: "Un caffè con Giulia — ep. 4", article: "Il piccolo rito del caffè italiano",
        reader: [
          { t: "In Italia molte persone bevono il caffè " },
          { w: "al banco", d: "at the counter — standing, and cheaper than sitting" },
          { t: ". Si ordina, si beve in fretta e si " },
          { w: "paga", d: "pay (one pays — from pagare, to pay)" },
          { t: " alla cassa. Il cappuccino si prende solo la " },
          { w: "mattina", d: "morning" },
          { t: ". È un piccolo rito quotidiano." }
        ],
        grammarMini: "il / la", grammarTitle: "“il · la” — masculine and feminine “the”",
        grammarIntro: "Italian nouns are masculine or feminine, and “the” changes to match:",
        gTermA: "il (m.)", gDescA: "masculine singular", gExA: "il caffè, il conto",
        gTermB: "la (f.)", gDescB: "feminine singular", gExB: "la mattina, la cassa",
        reviewWord: "conto", reviewSource: "from your bar visit, 2 days ago", reviewMeaning: "the bill / check (il conto)"
      },
      pt: {
        name: "Portuguese", flag: "🇧🇷", code: "PT", font: "", locale: "pt-BR",
        greeting: "Bom dia, Maya", chapter: "No café", cultureTeaser: "A cafezinho is an invitation",
        goalLine: "Order a coffee and chat — Brazilian style.", goalShort: "order a coffee", accent: "Brazil (São Paulo)",
        partnerName: "Bruno", partnerInitial: "B", partnerRole: "garçom", partnerPlace: "São Paulo café",
        scenarioTitle: "No café · São Paulo", scenarioSub: "Roleplay · order & warm small talk",
        lessonPromptEn: "I'd like a coffee with milk, please.", lessonHint: "Why “gostaria”?",
        bank: ["Eu gostaria de", "um café", "com leite", "por favor", "a conta", "sem"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "Perfeito! 🎉",
        lessonCorrectBody: "“Eu gostaria de” (I'd like) is the polite order — warmer than “Eu quero” (I want).",
        lessonWrongBody: "Start with the polite “I'd like,” then what you want.",
        cultureCaption: "A café in São Paulo · 9am", cultureTitle: "The cafezinho is about warmth, not caffeine",
        cultureBody: "In Brazil, offering someone a “cafezinho” (little coffee) is a gesture of welcome — at home, at work, everywhere. It's small, strong and sweet, and refusing one can feel cold. Conversation is warm and physical: expect to be called “querido/a.”",
        culturePhrase: "“Aceita um cafezinho?” — “care for a little coffee?”, an offer of friendship.",
        milestoneTitle: "You can now order a coffee — and chat warmly while you do.",
        convo: [
          { who: "p", n: "Bom dia! O que vai querer?", en: "Good morning! What would you like?" },
          { who: "u", n: "Eu gostaria de um café com leite, por favor.", fb: "Great — “gostaria” sounds polite and natural" },
          { who: "p", n: "Saindo! Mais alguma coisa?", en: "Coming up! Anything else?" },
          { who: "u", n: "Não, obrigada. A conta, por favor.", fb: "Perfect — “a conta” is exactly right" },
          { who: "p", n: "Claro, são cinco reais.", en: "Sure — that's five reais." }
        ],
        debrief: [
          { title: "“obrigada” vs “obrigado”", body: "It matches YOUR gender: a woman says “obrigada,” a man “obrigado.”" },
          { title: "Nasal “ã” in São", body: "“São” has a nasal sound — let it resonate through the nose a little." }
        ],
        clip: "A feira de rua em São Paulo, com os locais", podcast: "Um café com o Bruno — ep. 4", article: "O pequeno ritual do cafezinho",
        reader: [
          { t: "No Brasil, oferecer um " },
          { w: "cafezinho", d: "little coffee — a warm gesture of welcome" },
          { t: " é um sinal de carinho. Ele é pequeno, forte e " },
          { w: "doce", d: "sweet" },
          { t: ". As pessoas conversam e " },
          { w: "riem", d: "laugh (they laugh — from rir, to laugh)" },
          { t: " juntas. É o jeito brasileiro de receber alguém." }
        ],
        grammarMini: "ser vs estar", grammarTitle: "“ser” vs “estar” — two ways to “be”",
        grammarIntro: "Portuguese splits “to be” into permanent vs temporary:",
        gTermA: "ser", gDescA: "permanent — who/what something is", gExA: "O café é forte.",
        gTermB: "estar", gDescB: "temporary — a state right now", gExB: "O café está quente.",
        reviewWord: "conta", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "the bill / check (a conta)"
      },
      zh: {
        name: "Mandarin", flag: "🇨🇳", code: "ZH", font: "zh", locale: "zh-CN",
        greeting: "早上好, Maya", chapter: "咖啡馆 Coffee culture", cultureTeaser: "Tones change meaning",
        goalLine: "Order a coffee — politely, in Mandarin.", goalShort: "order a coffee", accent: "China (Mainland)",
        partnerName: "小美 Xiǎoměi", partnerInitial: "美", partnerRole: "店员 clerk", partnerPlace: "Shanghai café",
        scenarioTitle: "咖啡馆 · Shanghai", scenarioSub: "Roleplay · order & a short exchange",
        lessonPromptEn: "I want a coffee. (I'd like a coffee.)", lessonHint: "Why “要”?",
        bank: ["我", "要", "一杯", "咖啡", "水", "茶"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "完美！(Perfect!) 🎉",
        lessonCorrectBody: "“我要 (wǒ yào)” = “I want”; “一杯 (yì bēi)” = “one cup,” the measure word for drinks.",
        lessonWrongBody: "Start with “我” (I), then “要” (want), then “一杯” (one cup), then the drink.",
        cultureCaption: "A café in Shanghai · morning", cultureTitle: "Four tones, four meanings",
        cultureBody: "Mandarin is tonal: the same syllable means different things at different pitches. “mā / má / mǎ / mà” are mother, hemp, horse, scold. Getting tones roughly right matters more than perfect grammar — locals listen for the melody.",
        culturePhrase: "“谢谢 (xièxie)” — thank you; a smile and a nod carry it the rest of the way.",
        milestoneTitle: "You can now order a coffee — politely, in Mandarin.",
        convo: [
          { who: "p", n: "你好！要点什么？", en: "Hello! What would you like to order?" },
          { who: "u", n: "我要一杯咖啡。", fb: "Great — “一杯” (one cup) is the right measure word" },
          { who: "p", n: "热的还是冰的？", en: "Hot or iced?" },
          { who: "u", n: "热的，谢谢。", fb: "Perfect — “热的” = the hot one" },
          { who: "p", n: "好的，十五块。", en: "Okay — fifteen kuai." }
        ],
        debrief: [
          { title: "Measure word 杯", body: "You used “一杯” (one cup) — Mandarin needs a measure word between number and noun." },
          { title: "Tone on 要 (yào)", body: "“要” is a falling 4th tone — say it firmly, like a short command." }
        ],
        clip: "上海的早晨，和本地人", podcast: "和小美喝咖啡 — 第4集", article: "咖啡馆里的安静时光",
        reader: [
          { t: "在中国，越来越多的人喜欢去" },
          { w: "咖啡馆", d: "café (kāfēiguǎn)" },
          { t: "。他们点一杯咖啡，安静地" },
          { w: "看书", d: "read a book (kàn shū)" },
          { t: "或者工作。对店员要说" },
          { w: "谢谢", d: "thank you (xièxie)" },
          { t: "，这是礼貌。" }
        ],
        grammarMini: "measure words", grammarTitle: "Measure words — the “一杯” rule",
        grammarIntro: "Mandarin puts a measure word between a number and a noun. The word depends on the object's shape:",
        gTermA: "杯 (bēi)", gDescA: "for cups / glasses of drink", gExA: "一杯咖啡 — a cup of coffee",
        gTermB: "个 (gè)", gDescB: "the all-purpose default measure word", gExB: "一个人 — one person",
        reviewWord: "一杯", reviewSource: "from your café order, 3 days ago", reviewMeaning: "one cup (number + measure word for drinks)"
      },
      ar: {
        name: "Arabic", flag: "🇸🇦", code: "AR", font: "ar", locale: "ar-SA",
        greeting: "صباح الخير, Maya", chapter: "في المقهى Café culture", cultureTeaser: "Coffee means hospitality",
        goalLine: "Order coffee — politely, in Arabic.", goalShort: "order coffee", accent: "Modern Standard Arabic",
        partnerName: "ليلى Layla", partnerInitial: "ل", partnerRole: "نادلة waiter", partnerPlace: "a café",
        scenarioTitle: "في المقهى · Café", scenarioSub: "Roleplay · order & a warm exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “أريد”?",
        bank: ["أريد", "قهوة", "من فضلك", "الحساب", "ماء", "شاي"], correct: [0, 1, 2],
        lessonCorrectTitle: "ممتاز! (Excellent!) 🎉",
        lessonCorrectBody: "“أريد (urīd)” = “I want/would like”; “من فضلك (min faḍlik)” = “please.” Read right-to-left.",
        lessonWrongBody: "Start with “أريد” (I'd like), then the item, then “من فضلك” (please).",
        cultureCaption: "A café · afternoon", cultureTitle: "Refusing coffee can refuse the welcome",
        cultureBody: "Across the Arab world, offering coffee (qahwa) is the heart of hospitality. A host may insist; accepting, even a small cup, honors them. Arabic is written right-to-left, and a warm “shukran” (thank you) goes a long way.",
        culturePhrase: "“شكراً (shukran)” — thank you; reply to thanks with “عفواً (ʿafwan).”",
        milestoneTitle: "You can now order coffee — politely, in Arabic.",
        convo: [
          { who: "p", n: "مرحباً! ماذا تريد؟", en: "Hello! What would you like?" },
          { who: "u", n: "أريد قهوة من فضلك.", fb: "Great — “من فضلك” makes it polite" },
          { who: "p", n: "حاضر. أي شيء آخر؟", en: "Right away. Anything else?" },
          { who: "u", n: "لا، شكراً. الحساب من فضلك.", fb: "Perfect — “الحساب” = the bill" },
          { who: "p", n: "تفضّل، خمسة ريال.", en: "Here you go — five riyals." }
        ],
        debrief: [
          { title: "Right-to-left", body: "Arabic reads right-to-left — your sentence flowed in the right direction." },
          { title: "The “ḥ” in الحساب", body: "“ḥisāb” uses a breathy H from the throat — softer than a hard K." }
        ],
        clip: "السوق في الصباح، مع السكان المحليين", podcast: "قهوة مع ليلى — الحلقة 4", article: "طقس القهوة الصغير",
        reader: [
          { t: "في العالم العربي، تقديم " },
          { w: "القهوة", d: "coffee (al-qahwa)" },
          { t: " علامة كرم. الضيف " },
          { w: "يشرب", d: "drinks (he drinks — from شرب)" },
          { t: " فنجاناً صغيراً ويقول " },
          { w: "شكراً", d: "thank you (shukran)" },
          { t: ". إنها لحظة جميلة من اليوم." }
        ],
        grammarMini: "ال the", grammarTitle: "“ال” — the one word for “the”",
        grammarIntro: "Arabic has no “a/an,” and a single prefix “ال (al-)” means “the,” attached to the word:",
        gTermA: "قهوة", gDescA: "“coffee” — no article = a coffee", gExA: "أريد قهوة.",
        gTermB: "القهوة", gDescB: "“ال” + word = the coffee", gExB: "القهوة لذيذة.",
        reviewWord: "الحساب", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "the bill / check (al-ḥisāb)"
      },
      ru: {
        name: "Russian", flag: "🇷🇺", code: "RU", font: "", locale: "ru-RU",
        greeting: "Доброе утро, Maya", chapter: "В кафе", cultureTeaser: "Warmth under a formal surface",
        goalLine: "Order a coffee — politely, in Russian.", goalShort: "order a coffee", accent: "Russia (Standard)",
        partnerName: "Аня Anya", partnerInitial: "А", partnerRole: "официант", partnerPlace: "Moscow café",
        scenarioTitle: "В кафе · Moscow", scenarioSub: "Roleplay · order & a short exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “хотел бы”?",
        bank: ["Я хотел бы", "кофе", "с молоком", "пожалуйста", "счёт", "без"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "Отлично! 🎉",
        lessonCorrectBody: "“Я хотел бы (ya khotel by)” = “I would like” — politer than “Я хочу” (I want).",
        lessonWrongBody: "Start with the polite “I'd like,” then what you want.",
        cultureCaption: "A café in Moscow · morning", cultureTitle: "Reserved on the surface, warm underneath",
        cultureBody: "Russians can seem formal with strangers — smiles aren't handed out freely — but warmth runs deep once you're let in. Tea and coffee come with long conversation, and a guest is always offered something. Politeness lives in the word “пожалуйста.”",
        culturePhrase: "“Спасибо (spasibo)” — thank you; “пожалуйста” covers both “please” and “you're welcome.”",
        milestoneTitle: "You can now order a coffee — politely, in Russian.",
        convo: [
          { who: "p", n: "Здравствуйте! Что будете заказывать?", en: "Hello! What will you order?" },
          { who: "u", n: "Я хотел бы кофе с молоком, пожалуйста.", fb: "Great — “хотел бы” is polite and natural" },
          { who: "p", n: "Хорошо. Что-нибудь ещё?", en: "Okay. Anything else?" },
          { who: "u", n: "Нет, спасибо. Счёт, пожалуйста.", fb: "Perfect — “счёт” = the bill" },
          { who: "p", n: "Конечно, двести рублей.", en: "Of course — two hundred rubles." }
        ],
        debrief: [
          { title: "“хотел” vs “хотела”", body: "A man says “хотел бы,” a woman “хотела бы” — the verb agrees with your gender." },
          { title: "Rolled “р” in счёт", body: "Russian “р” is lightly rolled — let the tongue tap the ridge." }
        ],
        clip: "Утренний рынок в Москве, с местными", podcast: "Кофе с Аней — выпуск 4", article: "Маленький ритуал русского кофе",
        reader: [
          { t: "В России многие любят проводить время в " },
          { w: "кафе", d: "café (kafe)" },
          { t: ". Люди заказывают кофе и долго " },
          { w: "разговаривают", d: "talk / converse (from разговаривать)" },
          { t: ". Официанту говорят " },
          { w: "спасибо", d: "thank you (spasibo)" },
          { t: ". Это приятная часть дня." }
        ],
        grammarMini: "cases", grammarTitle: "Cases — why “молоко” becomes “молоком”",
        grammarIntro: "Russian nouns change endings by role. “With milk” puts milk in the instrumental case:",
        gTermA: "молоко", gDescA: "base form (nominative) — the milk", gExA: "Это молоко.",
        gTermB: "с молоком", gDescB: "instrumental — “with” triggers the -ом ending", gExB: "кофе с молоком",
        reviewWord: "счёт", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "the bill / check (schyot)"
      },
      tr: {
        name: "Turkish", flag: "🇹🇷", code: "TR", font: "", locale: "tr-TR",
        greeting: "Günaydın, Maya", chapter: "Kahvede", cultureTeaser: "Coffee builds friendship",
        goalLine: "Order a coffee — politely, in Turkish.", goalShort: "order a coffee", accent: "Turkey (Istanbul)",
        partnerName: "Emre", partnerInitial: "E", partnerRole: "garson", partnerPlace: "Istanbul café",
        scenarioTitle: "Kahvede · Istanbul", scenarioSub: "Roleplay · order & a warm exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “istiyorum”?",
        bank: ["Bir kahve", "istiyorum", "lütfen", "hesap", "su", "çay"], correct: [0, 1, 2],
        lessonCorrectTitle: "Mükemmel! 🎉",
        lessonCorrectBody: "“istiyorum” = “I want/would like” and goes at the END — Turkish verbs come last.",
        lessonWrongBody: "Name the item first, then “istiyorum” (I'd like) at the end, then “lütfen.”",
        cultureCaption: "A café in Istanbul · afternoon", cultureTitle: "“A coffee is remembered for 40 years”",
        cultureBody: "There's a Turkish saying: one cup of coffee earns forty years of friendship. Turkish coffee is slow, thick and social — served with water and often a sweet. To offer it is to offer your time, and reading the grounds afterward is half the fun.",
        culturePhrase: "“Teşekkürler (teşekkür ederim)” — thank you; “lütfen” is please.",
        milestoneTitle: "You can now order a coffee — politely, in Turkish.",
        convo: [
          { who: "p", n: "Merhaba! Ne alırsınız?", en: "Hello! What will you have?" },
          { who: "u", n: "Bir kahve istiyorum, lütfen.", fb: "Great — verb “istiyorum” at the end, very natural" },
          { who: "p", n: "Tabii. Başka bir şey?", en: "Of course. Anything else?" },
          { who: "u", n: "Hayır, teşekkürler. Hesap, lütfen.", fb: "Perfect — “hesap” = the bill" },
          { who: "p", n: "Tabii, otuz lira.", en: "Sure — thirty lira." }
        ],
        debrief: [
          { title: "Verb goes last", body: "Turkish word order is Subject–Object–Verb: “Bir kahve istiyorum.” You placed it right." },
          { title: "Dotless ı in hesap", body: "Turkish has “ı” (no dot) — a back vowel, like the 'a' in “sofa.”" }
        ],
        clip: "İstanbul'da sabah pazarı, yerlilerle", podcast: "Emre ile kahve — bölüm 4", article: "Türk kahvesinin küçük ritüeli",
        reader: [
          { t: "Türkiye'de insanlar " },
          { w: "kahve", d: "coffee" },
          { t: " içmeyi sever. Kahve yavaş içilir ve insanlar uzun uzun " },
          { w: "sohbet eder", d: "chat / converse (from sohbet etmek)" },
          { t: ". Garsona " },
          { w: "teşekkürler", d: "thank you (teşekkürler)" },
          { t: " denir. Bu, günün güzel bir anıdır." }
        ],
        grammarMini: "vowel harmony", grammarTitle: "Vowel harmony — endings that match",
        grammarIntro: "Turkish suffixes change vowels to harmonize with the word. The plural is -ler or -lar:",
        gTermA: "-ler", gDescA: "after front vowels (e, i, ö, ü)", gExA: "ev → evler (houses)",
        gTermB: "-lar", gDescB: "after back vowels (a, ı, o, u)", gExB: "kitap → kitaplar (books)",
        reviewWord: "hesap", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "the bill / check (hesap)"
      },
      vi: {
        name: "Vietnamese", flag: "🇻🇳", code: "VI", font: "", locale: "vi-VN",
        greeting: "Chào buổi sáng, Maya", chapter: "Ở quán cà phê", cultureTeaser: "Coffee is slow and sweet",
        goalLine: "Order a coffee — politely, in Vietnamese.", goalShort: "order coffee", accent: "Vietnam (Southern)",
        partnerName: "Linh", partnerInitial: "L", partnerRole: "nhân viên", partnerPlace: "Saigon café",
        scenarioTitle: "Quán cà phê · Saigon", scenarioSub: "Roleplay · order & a short exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “cho tôi”?",
        bank: ["Cho tôi", "một", "cà phê", "nhé", "nước", "trà"], correct: [0, 1, 2],
        lessonCorrectTitle: "Tuyệt vời! 🎉",
        lessonCorrectBody: "“Cho tôi (give me)” + “một (one)” is the natural, polite way to order; “nhé” softens it.",
        lessonWrongBody: "Start with “Cho tôi” (give me), then “một” (one), then the drink.",
        cultureCaption: "A café in Saigon · morning", cultureTitle: "Coffee is something you sit with",
        cultureBody: "Vietnamese coffee is strong, slow-dripped and often sweetened with condensed milk. People sit on low stools for hours, watching the street go by — “cà phê” is a pastime, not a to-go habit. Tones matter: the same word said six ways means six things.",
        culturePhrase: "“Cảm ơn (cám ơn)” — thank you; add “nhé” to sound friendly and soft.",
        milestoneTitle: "You can now order a coffee — politely, in Vietnamese.",
        convo: [
          { who: "p", n: "Xin chào! Bạn muốn dùng gì?", en: "Hello! What would you like?" },
          { who: "u", n: "Cho tôi một cà phê nhé.", fb: "Great — “cho tôi … nhé” is friendly and natural" },
          { who: "p", n: "Nóng hay đá?", en: "Hot or iced?" },
          { who: "u", n: "Đá, cảm ơn.", fb: "Perfect — “đá” = iced, the local favorite" },
          { who: "p", n: "Được, hai mươi nghìn.", en: "Okay — twenty thousand." }
        ],
        debrief: [
          { title: "“nhé” softens it", body: "Ending with “nhé” makes a request warm and polite — you used it well." },
          { title: "Tone on cà phê", body: "“cà” carries a falling tone — let the pitch drop, it changes the word." }
        ],
        clip: "Buổi sáng ở Sài Gòn, với người địa phương", podcast: "Cà phê với Linh — tập 4", article: "Nghi thức nhỏ của cà phê Việt",
        reader: [
          { t: "Ở Việt Nam, nhiều người thích ngồi ở " },
          { w: "quán cà phê", d: "café / coffee shop" },
          { t: ". Họ uống cà phê chậm rãi và " },
          { w: "trò chuyện", d: "chat / converse" },
          { t: " với nhau. Với nhân viên, mình nói " },
          { w: "cảm ơn", d: "thank you (cảm ơn)" },
          { t: ". Đó là khoảnh khắc đẹp trong ngày." }
        ],
        grammarMini: "classifiers", grammarTitle: "Classifiers — the “một cái” idea",
        grammarIntro: "Vietnamese puts a classifier between a number and a noun, by type of thing:",
        gTermA: "cái", gDescA: "for objects / things in general", gExA: "một cái bàn — one table",
        gTermB: "ly / cốc", gDescB: "for glasses / cups of drink", gExB: "một ly cà phê — a coffee",
        reviewWord: "cảm ơn", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "thank you (cảm ơn)"
      },
      nl: {
        name: "Dutch", flag: "🇳🇱", code: "NL", font: "", locale: "nl-NL",
        greeting: "Goedemorgen, Maya", chapter: "In het café", cultureTeaser: "Direct, and that's kind",
        goalLine: "Order a coffee — the Dutch way.", goalShort: "order a coffee", accent: "Netherlands (Standard)",
        partnerName: "Sanne", partnerInitial: "S", partnerRole: "ober", partnerPlace: "Amsterdam café",
        scenarioTitle: "In het café · Amsterdam", scenarioSub: "Roleplay · order & a short exchange",
        lessonPromptEn: "I would like a coffee with milk, please.", lessonHint: "Why “graag”?",
        bank: ["Ik wil graag", "een koffie", "met melk", "alstublieft", "de rekening", "zonder"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "Perfect! 🎉",
        lessonCorrectBody: "“Ik wil graag” (I'd like) with “graag” is the polite order; “alstublieft” is the formal please.",
        lessonWrongBody: "Start with the polite “I'd like,” then what you want.",
        cultureCaption: "A café in Amsterdam · 10am", cultureTitle: "Directness is a form of respect",
        cultureBody: "The Dutch are famously direct — they'll say exactly what they mean, and they expect the same back. It isn't rudeness; it's honesty and efficiency. Coffee usually comes with a small cookie on the side, and splitting the bill is completely normal.",
        culturePhrase: "“Dank je wel” — thank you (informal); “dank u wel” is the polite form.",
        milestoneTitle: "You can now order a coffee — the Dutch way.",
        convo: [
          { who: "p", n: "Goedemorgen! Wat wilt u?", en: "Good morning! What would you like?" },
          { who: "u", n: "Ik wil graag een koffie met melk, alstublieft.", fb: "Great — “graag” makes it polite" },
          { who: "p", n: "Prima. Anders nog iets?", en: "Fine. Anything else?" },
          { who: "u", n: "Nee, dank u. De rekening, alstublieft.", fb: "Perfect — “de rekening” = the bill" },
          { who: "p", n: "Natuurlijk, dat is drie euro.", en: "Of course — that's three euros." }
        ],
        debrief: [
          { title: "“u” vs “je”", body: "With staff you don't know, “u” (and “dank u”) is polite; “je” is casual." },
          { title: "Guttural “g” in graag", body: "Dutch “g” is a throaty sound — let it scrape softly at the back." }
        ],
        clip: "De markt in Amsterdam, met de locals", podcast: "Koffie met Sanne — aflevering 4", article: "Het kleine ritueel van Nederlandse koffie",
        reader: [
          { t: "In Nederland drinken veel mensen koffie in een " },
          { w: "café", d: "café" },
          { t: ". Erbij krijg je vaak een " },
          { w: "koekje", d: "little cookie / biscuit" },
          { t: ". Mensen zijn direct en " },
          { w: "praten", d: "talk (to talk — from praten)" },
          { t: " openhartig. Het is een fijn moment van de dag." }
        ],
        grammarMini: "de / het", grammarTitle: "“de” vs “het” — the two “the”s",
        grammarIntro: "Dutch nouns take either “de” or “het.” Most are “de”; you learn the “het” ones word by word:",
        gTermA: "de", gDescA: "common gender — the majority of nouns", gExA: "de koffie, de rekening",
        gTermB: "het", gDescB: "neuter — a smaller set, memorized", gExB: "het café, het koekje",
        reviewWord: "rekening", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "the bill / check (de rekening)"
      },
      pl: {
        name: "Polish", flag: "🇵🇱", code: "PL", font: "", locale: "pl-PL",
        greeting: "Dzień dobry, Maya", chapter: "W kawiarni", cultureTeaser: "Formal titles matter",
        goalLine: "Order a coffee — politely, in Polish.", goalShort: "order a coffee", accent: "Poland (Standard)",
        partnerName: "Kasia", partnerInitial: "K", partnerRole: "kelner", partnerPlace: "Kraków café",
        scenarioTitle: "W kawiarni · Kraków", scenarioSub: "Roleplay · order & a short exchange",
        lessonPromptEn: "I would like a coffee with milk, please.", lessonHint: "Why “poproszę”?",
        bank: ["Poproszę", "kawę", "z mlekiem", "proszę", "rachunek", "bez"], correct: [0, 1, 2],
        lessonCorrectTitle: "Świetnie! 🎉",
        lessonCorrectBody: "“Poproszę” (I'd like / may I have) is the warm, polite way to order in a café.",
        lessonWrongBody: "Start with “Poproszę,” then the item, then any extra like “z mlekiem.”",
        cultureCaption: "A café in Kraków · morning", cultureTitle: "Titles and “Pan/Pani” show respect",
        cultureBody: "Politeness in Poland runs through forms of address: you call a stranger “Pan” (sir) or “Pani” (madam), not by name. Cafés are cosy and unhurried, often serving coffee with a slice of cake. A warm “dziękuję” closes any exchange.",
        culturePhrase: "“Dziękuję” — thank you; “proszę” means both please and you're welcome.",
        milestoneTitle: "You can now order a coffee — politely, in Polish.",
        convo: [
          { who: "p", n: "Dzień dobry! Co podać?", en: "Hello! What can I get you?" },
          { who: "u", n: "Poproszę kawę z mlekiem.", fb: "Great — “Poproszę” is warm and polite" },
          { who: "p", n: "Jasne. Coś jeszcze?", en: "Sure. Anything else?" },
          { who: "u", n: "Nie, dziękuję. Rachunek poproszę.", fb: "Perfect — “rachunek” = the bill" },
          { who: "p", n: "Oczywiście, dziesięć złotych.", en: "Of course — ten złoty." }
        ],
        debrief: [
          { title: "“Poproszę” is your friend", body: "It politely means “I'd like / may I have” for almost anything — you used it perfectly." },
          { title: "Nasal “ę” in kawę", body: "The ę at the end is lightly nasal — let a hint of “n” colour it." }
        ],
        clip: "Poranny targ w Krakowie, z mieszkańcami", podcast: "Kawa z Kasią — odcinek 4", article: "Mały rytuał polskiej kawy",
        reader: [
          { t: "W Polsce wiele osób spędza czas w " },
          { w: "kawiarni", d: "café (in the café — from kawiarnia)" },
          { t: ". Zamawiają kawę i spokojnie " },
          { w: "rozmawiają", d: "talk / converse (from rozmawiać)" },
          { t: ". Do kelnera mówi się " },
          { w: "dziękuję", d: "thank you (dziękuję)" },
          { t: ". To miły moment dnia." }
        ],
        grammarMini: "cases", grammarTitle: "Cases — why “kawa” becomes “kawę”",
        grammarIntro: "Polish nouns change endings by role. The object of “I'd like” takes the accusative:",
        gTermA: "kawa", gDescA: "base form (nominative) — coffee", gExA: "To jest kawa.",
        gTermB: "kawę", gDescB: "accusative — the thing you want", gExB: "Poproszę kawę.",
        reviewWord: "rachunek", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "the bill / check (rachunek)"
      },
      id: {
        name: "Indonesian", flag: "🇮🇩", code: "ID", font: "", locale: "id-ID",
        greeting: "Selamat pagi, Maya", chapter: "Di kafe", cultureTeaser: "Warmth and a smile first",
        goalLine: "Order a coffee — politely, in Indonesian.", goalShort: "order a coffee", accent: "Indonesia (Jakarta)",
        partnerName: "Budi", partnerInitial: "B", partnerRole: "barista", partnerPlace: "Jakarta kopi shop",
        scenarioTitle: "Di kafe · Jakarta", scenarioSub: "Roleplay · order & a friendly chat",
        lessonPromptEn: "I would like one coffee, please.", lessonHint: "Why “minta”?",
        bank: ["Saya", "minta", "satu kopi", "tolong", "air", "teh"], correct: [0, 1, 2],
        lessonCorrectTitle: "Sempurna! 🎉",
        lessonCorrectBody: "“minta” = “ask for / I'd like” — the easy, polite way to order anything.",
        lessonWrongBody: "Start with “Saya” (I), then “minta” (would like), then the item.",
        cultureCaption: "A kopi shop in Jakarta · morning", cultureTitle: "Kopi is slow, sweet, and social",
        cultureBody: "Indonesia grows some of the world's best coffee, and ordering it comes wrapped in warmth — a smile and a soft word go further than speed. Kopi tubruk is served unfiltered, the grounds settling as you chat. Politeness and patience are the whole vibe.",
        culturePhrase: "“Terima kasih” — thank you; “tolong” softens any request into a polite please.",
        milestoneTitle: "You can now order a coffee — politely, in Indonesian.",
        convo: [
          { who: "p", n: "Selamat pagi! Mau pesan apa?", en: "Good morning! What would you like to order?" },
          { who: "u", n: "Saya minta satu kopi, tolong.", fb: "Great — “minta … tolong” is warm and polite" },
          { who: "p", n: "Baik. Ada lagi?", en: "Alright. Anything else?" },
          { who: "u", n: "Tidak, terima kasih.", fb: "Perfect — simple and natural" },
          { who: "p", n: "Sama-sama, dua puluh ribu rupiah.", en: "You're welcome — twenty thousand rupiah." }
        ],
        debrief: [
          { title: "“minta” vs “mau”", body: "“minta” (request) is softer than “mau” (want) — you chose the polite one." },
          { title: "Reduplication", body: "“Sama-sama” (you're welcome) doubles the word — common and friendly in Indonesian." }
        ],
        clip: "Pasar pagi di Jakarta, bersama warga", podcast: "Kopi bareng Budi — episode 4", article: "Ritual kecil kopi Indonesia",
        reader: [
          { t: "Di Indonesia, banyak orang suka menghabiskan waktu di " },
          { w: "kafe", d: "café" },
          { t: ". Mereka minum kopi pelan-pelan sambil " },
          { w: "mengobrol", d: "chatting (from obrol — to chat)" },
          { t: ". Kepada pelayan, kita berkata " },
          { w: "terima kasih", d: "thank you" },
          { t: ". Itu momen yang menyenangkan." }
        ],
        grammarMini: "no tenses", grammarTitle: "No verb tenses — use time words instead",
        grammarIntro: "Indonesian verbs don't change for time. You add a little word to say when:",
        gTermA: "sudah", gDescA: "“already” — marks the past", gExA: "Saya sudah minum. — I already drank.",
        gTermB: "akan", gDescB: "“will” — marks the future", gExB: "Saya akan minum. — I will drink.",
        reviewWord: "terima kasih", reviewSource: "from your kopi order, 3 days ago", reviewMeaning: "thank you"
      },
      th: {
        name: "Thai", flag: "🇹🇭", code: "TH", font: "th", locale: "th-TH",
        greeting: "สวัสดี, Maya", chapter: "ที่ร้านกาแฟ Café", cultureTeaser: "End with politeness",
        goalLine: "Order a coffee — politely, in Thai.", goalShort: "order a coffee", accent: "Thailand (Bangkok)",
        partnerName: "นภา Napha", partnerInitial: "N", partnerRole: "barista", partnerPlace: "Bangkok café",
        scenarioTitle: "ร้านกาแฟ · Bangkok", scenarioSub: "Roleplay · order & a polite exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “ขอ … ครับ/ค่ะ”?",
        bank: ["ขอ", "กาแฟ", "หนึ่งแก้ว", "ค่ะ", "น้ำ", "ชา"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "เยี่ยมมาก! (Perfect!) 🎉",
        lessonCorrectBody: "“ขอ” = “may I have,” and ending with “ค่ะ” (female) / “ครับ” (male) makes it polite.",
        lessonWrongBody: "Start with “ขอ” (may I have), name the item, then the polite particle.",
        cultureCaption: "A café in Bangkok · morning", cultureTitle: "Politeness rides on the last word",
        cultureBody: "Thai politeness lives in tiny ending particles — “ครับ” for men, “ค่ะ” for women — added to almost every sentence. Skip them and you sound abrupt. A gentle smile (and the wai, a slight bow with palms together) carries enormous social warmth.",
        culturePhrase: "“ขอบคุณค่ะ/ครับ (khop khun)” — thank you, with the polite particle.",
        milestoneTitle: "You can now order a coffee — politely, in Thai.",
        convo: [
          { who: "p", n: "สวัสดีค่ะ รับอะไรดีคะ?", en: "Hello! What would you like?" },
          { who: "u", n: "ขอกาแฟหนึ่งแก้วค่ะ", fb: "Great — “ขอ … ค่ะ” is the polite request" },
          { who: "p", n: "ได้ค่ะ รับอย่างอื่นไหมคะ?", en: "Sure. Anything else?" },
          { who: "u", n: "ไม่ค่ะ ขอบคุณค่ะ", fb: "Perfect — polite particle “ค่ะ” at the end" },
          { who: "p", n: "หกสิบบาทค่ะ", en: "Sixty baht." }
        ],
        debrief: [
          { title: "ครับ vs ค่ะ", body: "The polite particle depends on YOUR gender, not the listener's — men say ครับ, women ค่ะ." },
          { title: "Mid vs falling tone", body: "“กาแฟ” has specific tones — getting them right is what makes it understood." }
        ],
        clip: "ตลาดเช้าในกรุงเทพฯ กับคนท้องถิ่น", podcast: "กาแฟกับนภา — ตอนที่ 4", article: "พิธีกรรมเล็ก ๆ ของกาแฟไทย",
        reader: [
          { t: "ในประเทศไทย หลายคนชอบใช้เวลาที่" },
          { w: "ร้านกาแฟ", d: "café / coffee shop" },
          { t: " พวกเขาดื่มกาแฟช้า ๆ และ" },
          { w: "พูดคุย", d: "chat / talk together" },
          { t: "กัน กับพนักงานเราพูดว่า" },
          { w: "ขอบคุณ", d: "thank you (khop khun)" },
          { t: " มันเป็นช่วงเวลาที่ดีของวัน" }
        ],
        grammarMini: "ครับ / ค่ะ", grammarTitle: "Polite particles — ครับ and ค่ะ",
        grammarIntro: "Thai politeness is added at the very end of a sentence, chosen by your own gender:",
        gTermA: "ครับ (khrap)", gDescA: "added by male speakers", gExA: "ขอบคุณครับ",
        gTermB: "ค่ะ (kha)", gDescB: "added by female speakers", gExB: "ขอบคุณค่ะ",
        reviewWord: "ขอบคุณ", reviewSource: "from your café order, 3 days ago", reviewMeaning: "thank you (khop khun)"
      },
      el: {
        name: "Greek", flag: "🇬🇷", code: "EL", font: "noto", locale: "el-GR",
        greeting: "Καλημέρα, Maya", chapter: "Στο καφενείο", cultureTeaser: "Coffee is for lingering",
        goalLine: "Order a coffee — the Greek way.", goalShort: "order a coffee", accent: "Greece (Athens)",
        partnerName: "Γιώργος Giorgos", partnerInitial: "Γ", partnerRole: "σερβιτόρος", partnerPlace: "Athens kafeneio",
        scenarioTitle: "Στο καφενείο · Athens", scenarioSub: "Roleplay · order & a slow chat",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “θα ήθελα”?",
        bank: ["Θα ήθελα", "έναν καφέ", "παρακαλώ", "το λογαριασμό", "νερό", "χωρίς"], correct: [0, 1, 2],
        lessonCorrectTitle: "Τέλεια! 🎉",
        lessonCorrectBody: "“Θα ήθελα” (I would like) is the polite, conditional way to order — softer than “θέλω” (I want).",
        lessonWrongBody: "Start with the polite “I would like,” then what you want, then “παρακαλώ.”",
        cultureCaption: "A kafeneio in Athens · noon", cultureTitle: "The coffee is an excuse to stay",
        cultureBody: "In Greece a frappé or freddo can last two hours — the point was never the caffeine, it's the company. The kafeneio is where friendships, gossip and politics unfold slowly. No one will ever bring your bill until you ask; rushing you would be rude.",
        culturePhrase: "“Τον λογαριασμό, παρακαλώ” — the bill, please; “ευχαριστώ” is thank you.",
        milestoneTitle: "You can now order a coffee — the Greek way.",
        convo: [
          { who: "p", n: "Καλημέρα! Τι θα πάρετε;", en: "Good morning! What will you have?" },
          { who: "u", n: "Θα ήθελα έναν καφέ, παρακαλώ.", fb: "Great — “θα ήθελα” is polite and natural" },
          { who: "p", n: "Βεβαίως. Τίποτε άλλο;", en: "Of course. Anything else?" },
          { who: "u", n: "Όχι, ευχαριστώ. Τον λογαριασμό, παρακαλώ.", fb: "Perfect — that's how you ask for the bill" },
          { who: "p", n: "Αμέσως, τρία ευρώ.", en: "Right away — three euros." }
        ],
        debrief: [
          { title: "“έναν” gender", body: "Καφές is masculine, so “a coffee” is “έναν καφέ” — the article agrees with gender." },
          { title: "Stress mark", body: "Greek words carry an accent (ó) showing which syllable to stress — it changes meaning." }
        ],
        clip: "Πρωινή αγορά στην Αθήνα, με ντόπιους", podcast: "Καφές με τη Μαρία — επεισόδιο 4", article: "Η μικρή τελετουργία του ελληνικού καφέ",
        reader: [
          { t: "Στην Ελλάδα, πολλοί περνούν ώρες στο " },
          { w: "καφενείο", d: "kafeneio — traditional coffee house" },
          { t: ". Πίνουν τον καφέ αργά και " },
          { w: "συζητούν", d: "discuss / chat (from συζητώ)" },
          { t: ". Στον σερβιτόρο λένε " },
          { w: "ευχαριστώ", d: "thank you (efcharistó)" },
          { t: ". Είναι η πιο όμορφη στιγμή της ημέρας." }
        ],
        grammarMini: "genders", grammarTitle: "Three genders — ο, η, το",
        grammarIntro: "Every Greek noun is masculine, feminine or neuter, and the word for “the” changes:",
        gTermA: "ο καφές", gDescA: "masculine — the coffee", gExA: "ο καφές είναι ζεστός",
        gTermB: "η / το", gDescB: "feminine (η) and neuter (το)", gExB: "η ζάχαρη, το νερό",
        reviewWord: "λογαριασμό", reviewSource: "from your kafeneio visit, 2 days ago", reviewMeaning: "the bill / check (logariasmó)"
      },
      he: {
        name: "Hebrew", flag: "🇮🇱", code: "HE", font: "he", rtl: true, locale: "he-IL",
        greeting: "בוקר טוב, Maya", chapter: "בבית קפה Café", cultureTeaser: "Direct and warm at once",
        goalLine: "Order a coffee — politely, in Hebrew.", goalShort: "order a coffee", accent: "Israel (Standard)",
        partnerName: "נועה Noa", partnerInitial: "נ", partnerRole: "barista", partnerPlace: "Tel Aviv café",
        scenarioTitle: "בית קפה · Tel Aviv", scenarioSub: "Roleplay · order & a friendly chat",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “אפשר”?",
        bank: ["אפשר", "קפה", "בבקשה", "החשבון", "מים", "תה"], correct: [0, 1, 2],
        lessonCorrectTitle: "מושלם! (Perfect!) 🎉",
        lessonCorrectBody: "“אפשר” literally means “is it possible” — the everyday polite way to ask for something.",
        lessonWrongBody: "Start with “אפשר” (may I), name the item, then “בבקשה” (please).",
        cultureCaption: "A café in Tel Aviv · morning", cultureTitle: "Bluntness here is a kind of intimacy",
        cultureBody: "Israeli café culture is famously direct — people skip the small talk and speak plainly, which locals experience as warmth and honesty, not rudeness. Cafés are second offices and living rooms; sitting for hours over one coffee is completely normal.",
        culturePhrase: "“תודה (toda)” — thank you; “בבקשה (bevakasha)” is both please and you're welcome.",
        milestoneTitle: "You can now order a coffee — politely, in Hebrew.",
        convo: [
          { who: "p", n: "בוקר טוב! מה תרצי?", en: "Good morning! What would you like?" },
          { who: "u", n: "אפשר קפה, בבקשה.", fb: "Great — “אפשר … בבקשה” is the natural polite request" },
          { who: "p", n: "בטח. עוד משהו?", en: "Sure. Anything else?" },
          { who: "u", n: "לא, תודה. החשבון בבקשה.", fb: "Perfect — “החשבון” = the bill" },
          { who: "p", n: "בוודאי, שנים עשר שקל.", en: "Of course — twelve shekels." }
        ],
        debrief: [
          { title: "Gendered verbs", body: "“תרצי” is said to a woman, “תרצה” to a man — Hebrew verbs mark gender." },
          { title: "Guttural ח", body: "The ח in “החשבון” is a soft throat sound — let it rasp gently." }
        ],
        clip: "שוק הבוקר בתל אביב, עם המקומיים", podcast: "קפה עם נועה — פרק 4", article: "הטקס הקטן של הקפה הישראלי",
        reader: [
          { t: "בישראל, אנשים רבים אוהבים לשבת ב" },
          { w: "בית קפה", d: "café (beit kafe)" },
          { t: ". הם שותים קפה לאט ו" },
          { w: "מדברים", d: "talk / chat (medabrim)" },
          { t: " זה עם זה. למלצר אומרים " },
          { w: "תודה", d: "thank you (toda)" },
          { t: ". זה רגע נעים ביום." }
        ],
        grammarMini: "gender", grammarTitle: "Gendered verbs — speaking to him vs her",
        grammarIntro: "Hebrew verbs change by the gender of the person spoken to:",
        gTermA: "תרצה", gDescA: "said to a man — “would you like”", gExA: "מה תרצה?",
        gTermB: "תרצי", gDescB: "said to a woman — “would you like”", gExB: "מה תרצי?",
        reviewWord: "החשבון", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "the bill / check (ha-kheshbon)"
      },
      uk: {
        name: "Ukrainian", flag: "🇺🇦", code: "UK", font: "noto", locale: "uk-UA",
        greeting: "Доброго ранку, Maya", chapter: "У кафе", cultureTeaser: "Coffee is a Lviv ritual",
        goalLine: "Order a coffee — politely, in Ukrainian.", goalShort: "order a coffee", accent: "Ukraine (Kyiv)",
        partnerName: "Олена Olena", partnerInitial: "О", partnerRole: "бариста", partnerPlace: "Lviv café",
        scenarioTitle: "У кафе · Lviv", scenarioSub: "Roleplay · order & a warm exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “хотів/хотіла би”?",
        bank: ["Я хотів би", "каву", "будь ласка", "рахунок", "воду", "чай"], correct: [0, 1, 2],
        lessonCorrectTitle: "Чудово! 🎉",
        lessonCorrectBody: "“хотів би” (m.) / “хотіла би” (f.) is the polite conditional “I would like.”",
        lessonWrongBody: "Start with the polite “I would like,” then the item, then “будь ласка.”",
        cultureCaption: "A café in Lviv · morning", cultureTitle: "Lviv runs on coffee and conversation",
        cultureBody: "Lviv is Ukraine's coffee capital, with a café culture going back centuries — rich, ritual, and proudly local. Coffee comes strong and slow, often with a pastry, and the talk around the table matters as much as the cup. Warmth opens every exchange.",
        culturePhrase: "“Дякую (dyakuyu)” — thank you; “будь ласка” is please and you're welcome.",
        milestoneTitle: "You can now order a coffee — politely, in Ukrainian.",
        convo: [
          { who: "p", n: "Доброго ранку! Що бажаєте?", en: "Good morning! What would you like?" },
          { who: "u", n: "Я хотів би каву, будь ласка.", fb: "Great — “хотів би … будь ласка” is polite" },
          { who: "p", n: "Звичайно. Ще щось?", en: "Of course. Anything else?" },
          { who: "u", n: "Ні, дякую. Рахунок, будь ласка.", fb: "Perfect — “рахунок” = the bill" },
          { who: "p", n: "Звісно, тридцять гривень.", en: "Sure — thirty hryvnias." }
        ],
        debrief: [
          { title: "“хотів” vs “хотіла”", body: "A man says “хотів би,” a woman “хотіла би” — past-form verbs mark gender." },
          { title: "Soft “і” vs “и”", body: "Ukrainian distinguishes і and и — different vowels that change words." }
        ],
        clip: "Ранковий ринок у Львові, з місцевими", podcast: "Кава з Оленою — випуск 4", article: "Маленький ритуал української кави",
        reader: [
          { t: "В Україні багато людей люблять проводити час у " },
          { w: "кафе", d: "café (kafe)" },
          { t: ". Вони п'ють каву поволі та " },
          { w: "розмовляють", d: "talk / converse (rozmovляють)" },
          { t: ". Офіціанту кажуть " },
          { w: "дякую", d: "thank you (dyakuyu)" },
          { t: ". Це приємний момент дня." }
        ],
        grammarMini: "cases", grammarTitle: "Cases — why “кава” becomes “каву”",
        grammarIntro: "Ukrainian nouns change endings by role. The object of “I'd like” takes the accusative:",
        gTermA: "кава", gDescA: "base form (nominative) — coffee", gExA: "Це кава.",
        gTermB: "каву", gDescB: "accusative — the thing you want", gExB: "Я хотів би каву.",
        reviewWord: "рахунок", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "the bill / check (rakhunok)"
      },
      sw: {
        name: "Swahili", flag: "🇰🇪", code: "SW", font: "", locale: "sw-KE",
        greeting: "Habari ya asubuhi, Maya", chapter: "Kwenye mkahawa", cultureTeaser: "Greet, always greet",
        goalLine: "Order a coffee — politely, in Swahili.", goalShort: "order a coffee", accent: "Kenya / Tanzania",
        partnerName: "Amani", partnerInitial: "A", partnerRole: "mhudumu", partnerPlace: "Nairobi café",
        scenarioTitle: "Mkahawani · Nairobi", scenarioSub: "Roleplay · greet, order & chat",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “naomba”?",
        bank: ["Naomba", "kahawa", "tafadhali", "bili", "maji", "chai"], correct: [0, 1, 2],
        lessonCorrectTitle: "Vizuri sana! 🎉",
        lessonCorrectBody: "“Naomba” literally “I request” — the warm, polite way to ask for anything.",
        lessonWrongBody: "Start with “Naomba” (I'd like), name the item, then “tafadhali.”",
        cultureCaption: "A café in Nairobi · morning", cultureTitle: "Greetings come before everything",
        cultureBody: "In East Africa you greet before you ask for anything — skipping “Habari?” (how are you?) is unthinkable. The exchange of greetings can be long and is the heart of courtesy. Coffee and chai are shared slowly; relationships always come before the transaction.",
        culturePhrase: "“Asante (sana)” — thank you (very much); “tafadhali” is please.",
        milestoneTitle: "You can now order a coffee — politely, in Swahili.",
        convo: [
          { who: "p", n: "Habari ya asubuhi! Karibu, unataka nini?", en: "Good morning! Welcome, what would you like?" },
          { who: "u", n: "Naomba kahawa, tafadhali.", fb: "Great — “Naomba … tafadhali” is warm and polite" },
          { who: "p", n: "Sawa. Kitu kingine?", en: "Okay. Anything else?" },
          { who: "u", n: "Hapana, asante.", fb: "Perfect — “asante” = thank you" },
          { who: "p", n: "Karibu, shilingi mia mbili.", en: "You're welcome — two hundred shillings." }
        ],
        debrief: [
          { title: "Greet first", body: "You can add “Habari?” before ordering — greetings open every Swahili exchange." },
          { title: "“Karibu”", body: "It means both “welcome” and “you're welcome” — a lovely all-purpose warmth word." }
        ],
        clip: "Soko la asubuhi Nairobi, na wenyeji", podcast: "Kahawa na Amani — kipindi 4", article: "Desturi ndogo ya kahawa ya Afrika Mashariki",
        reader: [
          { t: "Afrika Mashariki, watu wengi hupenda kukaa " },
          { w: "mkahawani", d: "at the café (from mkahawa — café)" },
          { t: ". Hunywa kahawa polepole na " },
          { w: "kuzungumza", d: "to chat / converse" },
          { t: ". Kwa mhudumu, tunasema " },
          { w: "asante", d: "thank you" },
          { t: ". Ni wakati mzuri wa siku." }
        ],
        grammarMini: "noun classes", grammarTitle: "Noun classes — the “m-/wa-” idea",
        grammarIntro: "Swahili sorts nouns into classes; prefixes change for singular and plural:",
        gTermA: "mtu", gDescA: "person (m-/wa- class, singular)", gExA: "mtu mmoja — one person",
        gTermB: "watu", gDescB: "people (plural of the same class)", gExB: "watu wawili — two people",
        reviewWord: "asante", reviewSource: "from your café visit, 3 days ago", reviewMeaning: "thank you"
      },
      sv: {
        name: "Swedish", flag: "🇸🇪", code: "SV", font: "", locale: "sv-SE",
        greeting: "God morgon, Maya", chapter: "På fiket", cultureTeaser: "Fika is sacred",
        goalLine: "Order a coffee — and learn to fika.", goalShort: "order a coffee", accent: "Sweden (Stockholm)",
        partnerName: "Elsa", partnerInitial: "E", partnerRole: "barista", partnerPlace: "Stockholm fik",
        scenarioTitle: "På fiket · Stockholm", scenarioSub: "Roleplay · order & a cozy chat",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “skulle vilja”?",
        bank: ["Jag skulle vilja ha", "en kaffe", "tack", "notan", "vatten", "utan"], correct: [0, 1, 2],
        lessonCorrectTitle: "Perfekt! 🎉",
        lessonCorrectBody: "“skulle vilja ha” (would like to have) is the polite order; “tack” covers both please and thanks.",
        lessonWrongBody: "Start with the polite “I would like to have,” then the item.",
        cultureCaption: "A fik in Stockholm · 3pm", cultureTitle: "Fika is a national pause",
        cultureBody: "“Fika” is more than a coffee break — it's a daily ritual of slowing down, usually with a cinnamon bun, alone or with others. Swedes take it seriously; workplaces stop for it. There's no rushing, no upselling, and “lagom” (just the right amount) rules everything.",
        culturePhrase: "“Tack” does a lot of work — it's please, thank you, and yes please, depending on tone.",
        milestoneTitle: "You can now order a coffee — and fika like a Swede.",
        convo: [
          { who: "p", n: "God morgon! Vad vill du ha?", en: "Good morning! What would you like?" },
          { who: "u", n: "Jag skulle vilja ha en kaffe, tack.", fb: "Great — “skulle vilja ha” is nicely polite" },
          { who: "p", n: "Visst. Något mer?", en: "Sure. Anything else?" },
          { who: "u", n: "Nej tack. Notan, tack.", fb: "Perfect — “notan” = the bill" },
          { who: "p", n: "Självklart, trettio kronor.", en: "Of course — thirty kronor." }
        ],
        debrief: [
          { title: "“tack” is everything", body: "You used it for both please and thanks — exactly how Swedes do." },
          { title: "Pitch accent", body: "Swedish has a melodic two-tone accent — “kaffe” rises then falls slightly." }
        ],
        clip: "Morgonmarknaden i Stockholm, med lokalbor", podcast: "Kaffe med Elsa — avsnitt 4", article: "Den lilla ritualen som heter fika",
        reader: [
          { t: "I Sverige tar många en paus på ett " },
          { w: "fik", d: "café (a cozy coffee spot)" },
          { t: ". De dricker kaffe långsamt och " },
          { w: "pratar", d: "talk / chat (from prata)" },
          { t: ". Till servitören säger man " },
          { w: "tack", d: "thanks / please" },
          { t: ". Det kallas fika — en mysig stund." }
        ],
        grammarMini: "en / ett", grammarTitle: "“en” vs “ett” — the two genders",
        grammarIntro: "Swedish nouns are either “en” words or “ett” words — you simply learn which:",
        gTermA: "en kaffe", gDescA: "common gender (most nouns)", gExA: "en kaffe, en bulle",
        gTermB: "ett bord", gDescB: "neuter gender", gExB: "ett bord, ett glas",
        reviewWord: "notan", reviewSource: "from your fika, 2 days ago", reviewMeaning: "the bill / check (notan)"
      },
      ro: {
        name: "Romanian", flag: "🇷🇴", code: "RO", font: "", locale: "ro-RO",
        greeting: "Bună dimineața, Maya", chapter: "La cafenea", cultureTeaser: "Warm, Latin hospitality",
        goalLine: "Order a coffee — politely, in Romanian.", goalShort: "order a coffee", accent: "Romania (Bucharest)",
        partnerName: "Andrei", partnerInitial: "A", partnerRole: "ospătar", partnerPlace: "Bucharest café",
        scenarioTitle: "La cafenea · Bucharest", scenarioSub: "Roleplay · order & a warm exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “aș dori”?",
        bank: ["Aș dori", "o cafea", "vă rog", "nota", "apă", "ceai"], correct: [0, 1, 2],
        lessonCorrectTitle: "Perfect! 🎉",
        lessonCorrectBody: "“Aș dori” (I would like) is the polite conditional — softer than “vreau” (I want).",
        lessonWrongBody: "Start with the polite “I would like,” then the item, then “vă rog.”",
        cultureCaption: "A café in Bucharest · morning", cultureTitle: "A Latin soul in Eastern Europe",
        cultureBody: "Romanian is a Romance language in a Slavic neighbourhood, and the culture mixes Latin warmth with local depth. Coffee comes with unhurried conversation, and hospitality runs deep — a guest is often pressed to eat and stay. Politeness with “vă rog” opens every door.",
        culturePhrase: "“Mulțumesc” — thank you; “vă rog” is please (and “poftiți” means here you go).",
        milestoneTitle: "You can now order a coffee — politely, in Romanian.",
        convo: [
          { who: "p", n: "Bună dimineața! Ce doriți?", en: "Good morning! What would you like?" },
          { who: "u", n: "Aș dori o cafea, vă rog.", fb: "Great — “aș dori … vă rog” is polite and natural" },
          { who: "p", n: "Sigur. Altceva?", en: "Sure. Anything else?" },
          { who: "u", n: "Nu, mulțumesc. Nota, vă rog.", fb: "Perfect — “nota” = the bill" },
          { who: "p", n: "Desigur, cinci lei.", en: "Of course — five lei." }
        ],
        debrief: [
          { title: "Gender of nouns", body: "“Cafea” is feminine, so it's “o cafea” — the article matches gender." },
          { title: "Special letters ă, î, ș", body: "Romanian has its own diacritics — “ș” is “sh,” “ț” is “ts.”" }
        ],
        clip: "Piața de dimineață din București, cu localnicii", podcast: "Cafea cu Andrei — episodul 4", article: "Micul ritual al cafelei românești",
        reader: [
          { t: "În România, mulți oameni petrec timp la o " },
          { w: "cafenea", d: "café (cafenea)" },
          { t: ". Beau cafeaua încet și " },
          { w: "vorbesc", d: "talk / chat (from a vorbi)" },
          { t: ". Ospătarului îi spun " },
          { w: "mulțumesc", d: "thank you (mulțumesc)" },
          { t: ". E un moment plăcut al zilei." }
        ],
        grammarMini: "articles", grammarTitle: "The article hides at the end of the word",
        grammarIntro: "Romanian sticks “the” onto the END of the noun, unlike most Romance languages:",
        gTermA: "o cafea", gDescA: "“a coffee” — article before", gExA: "Aș dori o cafea.",
        gTermB: "cafeaua", gDescB: "“the coffee” — article suffixed", gExB: "Cafeaua e bună.",
        reviewWord: "nota", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "the bill / check (nota)"
      },
      cs: {
        name: "Czech", flag: "🇨🇿", code: "CS", font: "", locale: "cs-CZ",
        greeting: "Dobré ráno, Maya", chapter: "V kavárně", cultureTeaser: "Café houses are institutions",
        goalLine: "Order a coffee — politely, in Czech.", goalShort: "order a coffee", accent: "Czechia (Prague)",
        partnerName: "Petra", partnerInitial: "P", partnerRole: "číšnice", partnerPlace: "Prague kavárna",
        scenarioTitle: "V kavárně · Prague", scenarioSub: "Roleplay · order & a quiet exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “bych chtěl(a)”?",
        bank: ["Chtěl bych", "kávu", "prosím", "účet", "vodu", "čaj"], correct: [0, 1, 2],
        lessonCorrectTitle: "Výborně! 🎉",
        lessonCorrectBody: "“Chtěl bych” (m.) / “Chtěla bych” (f.) is the polite “I would like”; “prosím” is please.",
        lessonWrongBody: "Start with the polite “I would like,” then the item, then “prosím.”",
        cultureCaption: "A kavárna in Prague · morning", cultureTitle: "The café as a second home",
        cultureBody: "Prague's grand café houses are cultural institutions — places writers and thinkers lingered for hours over a single coffee. The atmosphere is calm and a touch formal; you greet, you order with “prosím,” and you're never hurried. Beer may be cheaper than water, but coffee culture runs deep too.",
        culturePhrase: "“Děkuji” — thank you; “prosím” is please (and also “you're welcome”).",
        milestoneTitle: "You can now order a coffee — politely, in Czech.",
        convo: [
          { who: "p", n: "Dobré ráno! Co si dáte?", en: "Good morning! What will you have?" },
          { who: "u", n: "Chtěl bych kávu, prosím.", fb: "Great — “chtěl bych … prosím” is polite" },
          { who: "p", n: "Jistě. Ještě něco?", en: "Sure. Anything else?" },
          { who: "u", n: "Ne, děkuji. Účet, prosím.", fb: "Perfect — “účet” = the bill" },
          { who: "p", n: "Samozřejmě, padesát korun.", en: "Of course — fifty crowns." }
        ],
        debrief: [
          { title: "“chtěl” vs “chtěla”", body: "A man says “chtěl bych,” a woman “chtěla bych” — the verb marks gender." },
          { title: "The “ř” sound", body: "Czech “ř” (in “tři”) is a famous rolled-buzzed sound — even locals praise foreigners who try." }
        ],
        clip: "Ranní trh v Praze, s místními", podcast: "Káva s Petrou — díl 4", article: "Malý rituál české kávy",
        reader: [
          { t: "V Česku lidé rádi tráví čas v " },
          { w: "kavárně", d: "café (in the café — from kavárna)" },
          { t: ". Pijí kávu pomalu a " },
          { w: "povídají si", d: "chat together (from povídat)" },
          { t: ". Číšníkovi řeknou " },
          { w: "děkuji", d: "thank you (děkuji)" },
          { t: ". Je to příjemná chvíle dne." }
        ],
        grammarMini: "cases", grammarTitle: "Cases — why “káva” becomes “kávu”",
        grammarIntro: "Czech nouns change endings by role. The object of “I'd like” takes the accusative:",
        gTermA: "káva", gDescA: "base form (nominative) — coffee", gExA: "To je káva.",
        gTermB: "kávu", gDescB: "accusative — the thing you want", gExB: "Chtěl bych kávu.",
        reviewWord: "účet", reviewSource: "from your kavárna visit, 2 days ago", reviewMeaning: "the bill / check (účet)"
      },
      hu: {
        name: "Hungarian", flag: "🇭🇺", code: "HU", font: "", locale: "hu-HU",
        greeting: "Jó reggelt, Maya", chapter: "A kávézóban", cultureTeaser: "Grand café traditions",
        goalLine: "Order a coffee — politely, in Hungarian.", goalShort: "order a coffee", accent: "Hungary (Budapest)",
        partnerName: "Eszter", partnerInitial: "E", partnerRole: "pincér", partnerPlace: "Budapest kávéház",
        scenarioTitle: "A kávézóban · Budapest", scenarioSub: "Roleplay · order & a polite exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “kérek”?",
        bank: ["Kérek", "egy kávét", "legyen szíves", "a számlát", "vizet", "teát"], correct: [0, 1, 2],
        lessonCorrectTitle: "Tökéletes! 🎉",
        lessonCorrectBody: "“Kérek” = “I ask for / I'd like”; “kávét” takes a -t ending because it's the object.",
        lessonWrongBody: "Start with “Kérek” (I'd like), then the item with its -t ending.",
        cultureCaption: "A kávéház in Budapest · morning", cultureTitle: "The coffee house as a salon",
        cultureBody: "Budapest's ornate kávéház (coffee houses) were once literary salons — writers had their own marble tables and wrote whole novels there. The tradition of lingering, reading and talking over coffee survives. Service is gracious and a little formal; “legyen szíves” (please) goes a long way.",
        culturePhrase: "“Köszönöm” — thank you; “legyen szíves” is a polite “please / be so kind.”",
        milestoneTitle: "You can now order a coffee — politely, in Hungarian.",
        convo: [
          { who: "p", n: "Jó reggelt! Mit kér?", en: "Good morning! What would you like?" },
          { who: "u", n: "Kérek egy kávét, legyen szíves.", fb: "Great — “kérek … legyen szíves” is polite" },
          { who: "p", n: "Rendben. Még valamit?", en: "Alright. Anything else?" },
          { who: "u", n: "Nem, köszönöm. A számlát, legyen szíves.", fb: "Perfect — “a számlát” = the bill" },
          { who: "p", n: "Természetesen, hatszáz forint.", en: "Of course — six hundred forint." }
        ],
        debrief: [
          { title: "The object ending -t", body: "“kávé” → “kávét” — Hungarian marks the object with a -t suffix." },
          { title: "Vowel harmony", body: "Suffixes change to match the vowels in the word — “kávét,” not “kávöt.”" }
        ],
        clip: "Reggeli piac Budapesten, helyiekkel", podcast: "Kávé Eszterrel — 4. rész", article: "A magyar kávé kis rituáléja",
        reader: [
          { t: "Magyarországon sokan szeretnek időt tölteni egy " },
          { w: "kávézóban", d: "in a café (from kávézó)" },
          { t: ". Lassan isszák a kávét és " },
          { w: "beszélgetnek", d: "chat / converse (from beszélget)" },
          { t: ". A pincérnek azt mondják, " },
          { w: "köszönöm", d: "thank you (köszönöm)" },
          { t: ". Ez a nap egyik kedves pillanata." }
        ],
        grammarMini: "vowel harmony", grammarTitle: "Vowel harmony — suffixes that match",
        grammarIntro: "Hungarian endings change their vowels to harmonise with the word's own vowels:",
        gTermA: "-ban", gDescA: "“in” after back vowels", gExA: "kávézóban — in a café",
        gTermB: "-ben", gDescB: "“in” after front vowels", gExB: "kertben — in a garden",
        reviewWord: "számla", reviewSource: "from your kávéház visit, 2 days ago", reviewMeaning: "the bill / check (számla)"
      },
      fi: {
        name: "Finnish", flag: "🇫🇮", code: "FI", font: "", locale: "fi-FI",
        greeting: "Hyvää huomenta, Maya", chapter: "Kahvilassa", cultureTeaser: "World's top coffee drinkers",
        goalLine: "Order a coffee — politely, in Finnish.", goalShort: "order a coffee", accent: "Finland (Helsinki)",
        partnerName: "Aino", partnerInitial: "A", partnerRole: "tarjoilija", partnerPlace: "Helsinki kahvila",
        scenarioTitle: "Kahvilassa · Helsinki", scenarioSub: "Roleplay · order & a calm exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “saisinko”?",
        bank: ["Saisinko", "kahvin", "kiitos", "laskun", "vettä", "teetä"], correct: [0, 1, 2],
        lessonCorrectTitle: "Täydellistä! 🎉",
        lessonCorrectBody: "“Saisinko” = “could I have” — the polite request; “kahvin” takes an -n ending as the object.",
        lessonWrongBody: "Start with “Saisinko” (could I have), then the item with its -n ending.",
        cultureCaption: "A kahvila in Helsinki · morning", cultureTitle: "The world's heaviest coffee drinkers",
        cultureBody: "Finns drink more coffee per person than anyone on Earth, and the workday even guarantees coffee breaks by tradition. Yet the culture is quiet and unfussy — comfortable silences are normal, small talk is minimal, and a calm “kiitos” is all the warmth a moment needs.",
        culturePhrase: "“Kiitos” — thank you (and please, in requests); a little goes a long way.",
        milestoneTitle: "You can now order a coffee — politely, in Finnish.",
        convo: [
          { who: "p", n: "Hyvää huomenta! Mitä saisi olla?", en: "Good morning! What would you like?" },
          { who: "u", n: "Saisinko kahvin, kiitos.", fb: "Great — “saisinko … kiitos” is polite and natural" },
          { who: "p", n: "Toki. Jotain muuta?", en: "Sure. Anything else?" },
          { who: "u", n: "Ei, kiitos. Laskun, kiitos.", fb: "Perfect — “laskun” = the bill" },
          { who: "p", n: "Tottakai, kolme euroa.", en: "Of course — three euros." }
        ],
        debrief: [
          { title: "The object ending -n", body: "“kahvi” → “kahvin” — Finnish marks a whole, completed object with -n." },
          { title: "Double letters matter", body: "“tuli” (fire) vs “tuuli” (wind) — length of vowels/consonants changes meaning." }
        ],
        clip: "Aamutori Helsingissä, paikallisten kanssa", podcast: "Kahvit Ainon kanssa — jakso 4", article: "Suomalaisen kahvin pieni rituaali",
        reader: [
          { t: "Suomessa moni viettää aikaa " },
          { w: "kahvilassa", d: "in a café (from kahvila)" },
          { t: ". He juovat kahvia rauhassa ja " },
          { w: "juttelevat", d: "chat (from jutella)" },
          { t: ". Tarjoilijalle sanotaan " },
          { w: "kiitos", d: "thank you / please (kiitos)" },
          { t: ". Se on päivän mukava hetki." }
        ],
        grammarMini: "cases", grammarTitle: "Cases — endings instead of prepositions",
        grammarIntro: "Finnish has no word for “in” — it adds an ending to the noun instead:",
        gTermA: "kahvila", gDescA: "café (base form)", gExA: "Tämä on kahvila.",
        gTermB: "kahvilassa", gDescB: "“in the café” — the -ssa ending", gExB: "Olen kahvilassa.",
        reviewWord: "lasku", reviewSource: "from your kahvila visit, 2 days ago", reviewMeaning: "the bill / check (lasku)"
      },
      no: {
        name: "Norwegian", flag: "🇳🇴", code: "NO", font: "", locale: "nb-NO",
        greeting: "God morgen, Maya", chapter: "På kafé", cultureTeaser: "Kos and quiet equality",
        goalLine: "Order a coffee — politely, in Norwegian.", goalShort: "order a coffee", accent: "Norway (Oslo)",
        partnerName: "Ingrid", partnerInitial: "I", partnerRole: "servitør", partnerPlace: "Oslo kafé",
        scenarioTitle: "På kafé · Oslo", scenarioSub: "Roleplay · order & a cozy exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “kunne jeg få”?",
        bank: ["Kan jeg få", "en kaffe", "takk", "regningen", "vann", "uten"], correct: [0, 1, 2],
        lessonCorrectTitle: "Perfekt! 🎉",
        lessonCorrectBody: "“Kan jeg få …, takk” (may I have …, please) is the everyday polite order; “takk” covers please & thanks.",
        lessonWrongBody: "Start with “Kan jeg få” (may I have), then the item, then “takk.”",
        cultureCaption: "A kafé in Oslo · morning", cultureTitle: "Equality, quiet, and kos",
        cultureBody: "Norwegians value equality and understatement — you won't see much fuss or hierarchy, and first names are used with everyone. The cosy ideal of “kos” means a warm coffee, soft light and easy company. Politeness is gentle and brief; over-the-top service would feel out of place.",
        culturePhrase: "“Takk” does double duty as please and thank you; “tusen takk” is a warm “thanks a lot.”",
        milestoneTitle: "You can now order a coffee — politely, in Norwegian.",
        convo: [
          { who: "p", n: "God morgen! Hva vil du ha?", en: "Good morning! What would you like?" },
          { who: "u", n: "Kan jeg få en kaffe, takk.", fb: "Great — “kan jeg få … takk” is natural and polite" },
          { who: "p", n: "Selvsagt. Noe mer?", en: "Of course. Anything more?" },
          { who: "u", n: "Nei takk. Regningen, takk.", fb: "Perfect — “regningen” = the bill" },
          { who: "p", n: "Klart, tretti kroner.", en: "Sure — thirty kroner." }
        ],
        debrief: [
          { title: "“takk” everywhere", body: "You used it for both please and thanks — exactly the Norwegian way." },
          { title: "Pitch accent", body: "Norwegian is a tonal-ish language — words have a gentle rising/falling melody." }
        ],
        clip: "Morgenmarkedet i Oslo, med lokale", podcast: "Kaffe med Ingrid — episode 4", article: "Det lille ritualet rundt norsk kaffe",
        reader: [
          { t: "I Norge liker mange å tilbringe tid på en " },
          { w: "kafé", d: "café" },
          { t: ". De drikker kaffe rolig og " },
          { w: "prater", d: "chat / talk (from prate)" },
          { t: ". Til servitøren sier man " },
          { w: "takk", d: "thanks / please (takk)" },
          { t: ". Det er et koselig øyeblikk." }
        ],
        grammarMini: "en / et", grammarTitle: "“en” vs “et” — the two genders",
        grammarIntro: "Norwegian nouns are mostly “en” words or “et” words; the article also attaches to the end:",
        gTermA: "en kaffe", gDescA: "common gender — a coffee", gExA: "en kaffe → kaffen (the coffee)",
        gTermB: "et bord", gDescB: "neuter gender — a table", gExB: "et bord → bordet (the table)",
        reviewWord: "regningen", reviewSource: "from your kafé visit, 2 days ago", reviewMeaning: "the bill / check (regningen)"
      },
      da: {
        name: "Danish", flag: "🇩🇰", code: "DA", font: "", locale: "da-DK",
        greeting: "Godmorgen, Maya", chapter: "På caféen", cultureTeaser: "Hygge is the whole point",
        goalLine: "Order a coffee — politely, in Danish.", goalShort: "order a coffee", accent: "Denmark (Copenhagen)",
        partnerName: "Mette", partnerInitial: "M", partnerRole: "tjener", partnerPlace: "Copenhagen café",
        scenarioTitle: "På caféen · Copenhagen", scenarioSub: "Roleplay · order & a hyggelig exchange",
        lessonPromptEn: "I would like a coffee, please.", lessonHint: "Why “må jeg få”?",
        bank: ["Må jeg få", "en kaffe", "tak", "regningen", "vand", "uden"], correct: [0, 1, 2],
        lessonCorrectTitle: "Perfekt! 🎉",
        lessonCorrectBody: "“Må jeg få …, tak” (may I have …, please) is the everyday polite order; “tak” means please/thanks.",
        lessonWrongBody: "Start with “Må jeg få” (may I have), then the item, then “tak.”",
        cultureCaption: "A café in Copenhagen · morning", cultureTitle: "Hygge: warmth, candles, calm",
        cultureBody: "“Hygge” — cosy, content togetherness — is the heart of Danish life, and the café is its natural home: candles even by day, soft seating, no rush. Danes are relaxed and egalitarian; service is friendly and informal, and lingering over coffee is exactly the point.",
        culturePhrase: "“Tak” covers thanks and please; “tusind tak” is a heartfelt “a thousand thanks.”",
        milestoneTitle: "You can now order a coffee — politely, in Danish.",
        convo: [
          { who: "p", n: "Godmorgen! Hvad vil du have?", en: "Good morning! What would you like?" },
          { who: "u", n: "Må jeg få en kaffe, tak.", fb: "Great — “må jeg få … tak” is natural and polite" },
          { who: "p", n: "Selvfølgelig. Andet?", en: "Of course. Anything else?" },
          { who: "u", n: "Nej tak. Regningen, tak.", fb: "Perfect — “regningen” = the bill" },
          { who: "p", n: "Klart, femogtyve kroner.", en: "Sure — twenty-five kroner." }
        ],
        debrief: [
          { title: "“tak” for everything", body: "You used it for please and thanks — just like Danes do." },
          { title: "The soft “d”", body: "The Danish soft “d” (in “mad”) sounds almost like an English “l” — tricky but charming." }
        ],
        clip: "Morgenmarkedet i København, med lokale", podcast: "Kaffe med Mette — afsnit 4", article: "Det lille ritual omkring dansk kaffe",
        reader: [
          { t: "I Danmark kan man godt lide at bruge tid på en " },
          { w: "café", d: "café" },
          { t: ". De drikker kaffe i ro og " },
          { w: "snakker", d: "chat / talk (from snakke)" },
          { t: ". Til tjeneren siger man " },
          { w: "tak", d: "thanks / please (tak)" },
          { t: ". Det er et hyggeligt øjeblik." }
        ],
        grammarMini: "en / et", grammarTitle: "“en” vs “et” — the two genders",
        grammarIntro: "Danish nouns are “en” or “et” words, and the article attaches to the end of the word:",
        gTermA: "en kaffe", gDescA: "common gender — a coffee", gExA: "en kaffe → kaffen (the coffee)",
        gTermB: "et bord", gDescB: "neuter gender — a table", gExB: "et bord → bordet (the table)",
        reviewWord: "regningen", reviewSource: "from your café visit, 2 days ago", reviewMeaning: "the bill / check (regningen)"
      },
      tl: {
        name: "Filipino", flag: "🇵🇭", code: "TL", font: "", locale: "fil-PH",
        greeting: "Magandang umaga, Maya", chapter: "Sa kapehan", cultureTeaser: "“Po” makes it respectful",
        goalLine: "Order a coffee — politely, in Filipino.", goalShort: "order a coffee", accent: "Philippines (Manila)",
        partnerName: "Liza", partnerInitial: "L", partnerRole: "barista", partnerPlace: "Manila kapehan",
        scenarioTitle: "Sa kapehan · Manila", scenarioSub: "Roleplay · order & a warm exchange",
        lessonPromptEn: "I would like one coffee, please.", lessonHint: "Why “po”?",
        bank: ["Pwede", "po", "isang kape", "salamat", "tubig", "tsaa"], correct: [0, 1, 2],
        lessonCorrectTitle: "Ang galing! 🎉",
        lessonCorrectBody: "“Pwede po …” = “may I please …” — the little word “po” adds respect to anything.",
        lessonWrongBody: "Start with “Pwede” (may I), add “po” for respect, then the item.",
        cultureCaption: "A kapehan in Manila · morning", cultureTitle: "Respect lives in one word: “po”",
        cultureBody: "Filipino warmth and respect run through the language — adding “po” (and “opo” for yes) to your speech shows courtesy to elders and strangers alike. Hospitality is huge: you'll be offered food and coffee constantly, and refusing too firmly can seem cold. A smile carries everything.",
        culturePhrase: "“Salamat (po)” — thank you; add “po” to sound respectful to anyone older or in service.",
        milestoneTitle: "You can now order a coffee — politely, in Filipino.",
        convo: [
          { who: "p", n: "Magandang umaga! Ano po ang gusto ninyo?", en: "Good morning! What would you like?" },
          { who: "u", n: "Pwede po isang kape, salamat.", fb: "Great — “po” makes it nicely respectful" },
          { who: "p", n: "Sige po. May iba pa po ba?", en: "Sure. Anything else?" },
          { who: "u", n: "Wala na po, salamat.", fb: "Perfect — “wala na po” = nothing more, thanks" },
          { who: "p", n: "Salamat po, singkwenta pesos.", en: "Thank you — fifty pesos." }
        ],
        debrief: [
          { title: "The magic of “po”", body: "Sprinkling “po” through a sentence is the core of Filipino politeness — you used it well." },
          { title: "Spanish loanwords", body: "Many words (kape, mesa, silya) come from Spanish — a head start if you know it." }
        ],
        clip: "Umagang palengke sa Maynila, kasama ang mga lokal", podcast: "Kape kasama si Liza — episode 4", article: "Ang maliit na ritwal ng kapeng Pinoy",
        reader: [
          { t: "Sa Pilipinas, maraming tao ang gustong mag-stay sa " },
          { w: "kapehan", d: "café / coffee shop" },
          { t: ". Dahan-dahan silang umiinom ng kape at " },
          { w: "nag-uusap", d: "talking together (from usap)" },
          { t: ". Sa barista, sinasabi nila ang " },
          { w: "salamat", d: "thank you (salamat)" },
          { t: ". Masayang bahagi ito ng araw." }
        ],
        grammarMini: "po / opo", grammarTitle: "“po” and “opo” — politeness markers",
        grammarIntro: "Filipino shows respect by inserting little particles, not by changing verbs:",
        gTermA: "po", gDescA: "respect particle, slipped into a sentence", gExA: "Salamat po.",
        gTermB: "opo", gDescB: "respectful “yes” (vs casual “oo”)", gExB: "Opo, gusto ko po.",
        reviewWord: "salamat", reviewSource: "from your kapehan visit, 3 days ago", reviewMeaning: "thank you"
      },
      bn: {
        name: "Bengali", flag: "🇧🇩", code: "BN", font: "bn", locale: "bn-BD",
        greeting: "সুপ্রভাত, Maya", chapter: "চায়ের দোকান Tea culture", cultureTeaser: "Adda over endless cha",
        goalLine: "Order cha and chat — Bengali style.", goalShort: "order cha", accent: "Bangladesh / Kolkata",
        partnerName: "রিয়া Riya", partnerInitial: "R", partnerRole: "cha wala", partnerPlace: "Dhaka tea stall",
        scenarioTitle: "চায়ের দোকান · Dhaka", scenarioSub: "Roleplay · order cha & adda",
        lessonPromptEn: "I would like one cup of tea.", lessonHint: "Why “এক কাপ”?",
        bank: ["আমি", "এক কাপ", "চা", "চাই", "পানি", "দুই"], correct: [0, 1, 2, 3],
        lessonCorrectTitle: "চমৎকার! (Wonderful!) 🎉",
        lessonCorrectBody: "“আমি … চাই” = “I want”; “এক কাপ চা” is “one cup of tea,” with the counter কাপ.",
        lessonWrongBody: "Start with “আমি” (I), then “এক কাপ” (one cup), then “চা,” then “চাই.”",
        cultureCaption: "A tea stall in Dhaka · evening", cultureTitle: "Cha and adda: the art of hanging out",
        cultureBody: "In Bengal, the roadside tea stall is a social institution and “adda” — long, rambling, joyful conversation — is practically a cultural art form. A tiny glass of sweet, milky cha fuels hours of talk about everything and nothing. To share cha is to share time and friendship.",
        culturePhrase: "“ধন্যবাদ (dhonnobad)” — thank you; “কত? (koto?)” means “how much?”",
        milestoneTitle: "You can now order cha — and settle in for adda.",
        convo: [
          { who: "p", n: "সুপ্রভাত! কী খাবেন?", en: "Good morning! What will you have?" },
          { who: "u", n: "আমি এক কাপ চা চাই।", fb: "Great — “এক কাপ চা” with the counter is natural" },
          { who: "p", n: "দুধ চা না রং চা?", en: "Milk tea or black tea?" },
          { who: "u", n: "দুধ চা, ধন্যবাদ।", fb: "Perfect — “দুধ চা” = milk tea" },
          { who: "p", n: "মাত্র দশ টাকা।", en: "Just ten taka." }
        ],
        debrief: [
          { title: "Counter “কাপ”", body: "You said “এক কাপ চা” (one cup tea) — counters make Bengali sound fluent." },
          { title: "Aspirated “ধ”", body: "“ধন্যবাদ” starts with a breathy “dh” — let a puff of air follow the d." }
        ],
        clip: "ঢাকার সকালের বাজার, স্থানীয়দের সঙ্গে", podcast: "রিয়ার সঙ্গে চা — পর্ব ৪", article: "বাঙালি চায়ের ছোট্ট রীতি",
        reader: [
          { t: "বাংলায়, সকাল শুরু হয় এক কাপ গরম " },
          { w: "চা", d: "cha — sweet milky tea" },
          { t: " দিয়ে। মানুষ রাস্তার ধারে দাঁড়িয়ে চা " },
          { w: "খায়", d: "drinks / consumes (from খাওয়া)" },
          { t: " আর একসঙ্গে " },
          { w: "আড্ডা দেয়", d: "hangs out / chats (adda dey)" },
          { t: "। এটাই দিনের সেরা সময়।" }
        ],
        grammarMini: "আমি … চাই", grammarTitle: "“আমি … চাই” — how to say “I want”",
        grammarIntro: "Bengali puts the verb at the end. “I want X” is literally “I X want”:",
        gTermA: "আমি (ami)", gDescA: "“I” — the subject, comes first", gExA: "আমি চা চাই।",
        gTermB: "চাই (chai)", gDescB: "“want” — the verb, comes last", gExB: "আমি পানি চাই।",
        reviewWord: "ধন্যবাদ", reviewSource: "from your cha order, 3 days ago", reviewMeaning: "thank you (dhonnobad)"
      }
    };
