import type { ChapterInput } from '../indic/build';

// Chapters 3–6 (family, hotel, market, emergency). Chapters 1–2 come from the base course.
export const dutchExtra: ChapterInput[] = [
  {
    ct: 'Familie Family',
    partner: 'Lotte Lotte', role: 'friend', place: 'home', scenarioTitle: 'Thuis · Utrecht',
    prompt: 'This is my father.', hint: '“Dit is mijn …” works for any person.',
    bank: ['Dit', 'is', 'mijn', 'vader', 'moeder', 'zus'],
    bankEn: ['this', 'is', 'my', 'father', 'mother', 'sister'],
    correct: [0, 1, 2, 3],
    okTitle: 'Goed zo! 🎉', okBody: '“Dit is mijn vader” — “mijn” stays the same for every noun.',
    noBody: 'Order: “Dit” + “is” + “mijn” + “vader”.',
    cultureCaption: 'A birthday circle in Utrecht', cultureTitle: 'The birthday circle',
    cultureBody: 'At Dutch birthdays, guests sit in a circle and congratulate everyone in the family, not just the birthday person — “gefeliciteerd met je vader!”. Coffee and cake (taart) are served first.',
    culturePhrase: '“Gefeliciteerd!” — “Congratulations!”', milestone: 'You can now introduce your family.',
    convo: [
      ['p', 'Hoi! Wie is dat?', 'Hi! Who is that?'],
      ['u', 'Dit is mijn vader.', 'Perfect — “mijn” works for any noun'],
      ['p', 'Leuk je te ontmoeten! En waar is je moeder?', 'Nice to meet you! And where is your mother?'],
      ['u', 'Ze is thuis.', 'Good — “ze” = she'],
      ['p', 'Wat fijn! Ik wil haar graag ontmoeten.', "How nice! I'd love to meet her."],
    ],
    debrief: [['“Je” vs “u”', '“Je” is informal; “u” is formal. Use “u” with older strangers.'], ['“Leuk je te ontmoeten”', 'The warm, standard way to say “nice to meet you”.']],
    grammarMini: 'Dit is mijn …', grammarTitle: '“mijn / jouw” — my / your', grammarIntro: 'Possessives don’t change with gender in Dutch:',
    A: ['mijn (mine)', '“my”', 'Dit is mijn vader.'], B: ['jouw (yow)', '“your” (informal)', 'Is dit jouw zus?'],
    clip: 'Verjaardag in de kring', podcast: 'Lotte en de familie — aflevering 3', article: 'Mijn familie',
    reader: ['Mijn familie is groot. Dit is mijn ', ['vader', 'father'], ' en dit is mijn ', ['moeder', 'mother'], '. Ik heb een ', ['zus', 'sister'], ' en een broer.'],
    reviewWord: 'vader', reviewSource: 'from your family introduction, 2 days ago', reviewMeaning: 'father',
  },
  {
    ct: 'Hotel Hotel',
    partner: 'Pieter Pieter', role: 'hotel receptionist', place: 'Amsterdam hotel', scenarioTitle: 'In het hotel · Amsterdam',
    prompt: 'I have a reservation.', hint: '“Ik heb een reservering.”',
    bank: ['Ik', 'heb', 'een', 'reservering', 'kamer', 'sleutel'],
    bankEn: ['I', 'have', 'a', 'reservation', 'room', 'key'],
    correct: [0, 1, 2, 3],
    okTitle: 'Uitstekend! 🎉', okBody: '“Ik heb een reservering” — the verb comes second in a Dutch sentence.',
    noBody: 'Order: “Ik” + “heb” + “een” + “reservering”.',
    cultureCaption: 'A canal-side hotel in Amsterdam', cultureTitle: 'Small rooms, big breakfasts',
    cultureBody: 'Dutch hotels are often small and compact, with steep stairs. Breakfast usually means bread, cheese, cold cuts and hagelslag (chocolate sprinkles). Staff speak good English but appreciate an attempt at Dutch.',
    culturePhrase: '“Hoe laat is het ontbijt?” — “What time is breakfast?”', milestone: 'You can now check into a hotel.',
    convo: [
      ['p', 'Goedemiddag! Waarmee kan ik u helpen?', 'Good afternoon! How can I help you?'],
      ['u', 'Goedemiddag. Ik heb een reservering.', 'Great — clear and polite'],
      ['p', 'Op welke naam?', 'Under what name?'],
      ['u', 'Op naam van De Vries.', 'Good — “op naam van” = under the name of'],
      ['p', 'Prima. Hier is uw sleutel.', "Fine. Here's your key."],
    ],
    debrief: [['“Goedemiddag”', 'Use “goedemorgen”, “goedemiddag”, “goedenavond” by time of day.'], ['“Alstublieft”', '“Alstublieft” (please / here you go) is used all the time.']],
    grammarMini: 'Ik heb …', grammarTitle: '“hebben” — to have', grammarIntro: 'The verb comes second in the sentence:',
    A: ['heb (hep)', '“I have”', 'Ik heb een reservering.'], B: ['heeft (hayft)', '“he / she / it has”', 'Het hotel heeft een restaurant.'],
    clip: 'Aankomst aan de gracht', podcast: 'Pieter bij de receptie — aflevering 4', article: 'Een nacht in het hotel',
    reader: ['In het hotel heb ik een ', ['kamer', 'room'], '. Hij is schoon en rustig. Ik blijf twee ', ['nachten', 'nights'], '.'],
    reviewWord: 'kamer', reviewSource: 'from your hotel booking, 5 days ago', reviewMeaning: 'room',
  },
  {
    ct: 'Markt Market',
    partner: 'Mevrouw Smit Mrs Smit', role: 'cheese seller', place: 'Dutch market', scenarioTitle: 'Op de markt · Alkmaar',
    prompt: 'How much is this?', hint: '“Hoeveel kost dit?”',
    bank: ['Hoeveel', 'kost', 'dit', 'duur', 'goedkoop', 'alstublieft'],
    bankEn: ['how much', 'costs', 'this', 'expensive', 'cheap', 'please'],
    correct: [0, 1, 2],
    okTitle: 'Prima! 🎉', okBody: '“Hoeveel kost dit?” is short and natural — verb in second place again.',
    noBody: 'Order: “Hoeveel” + “kost” + “dit”.',
    cultureCaption: 'The cheese market in Alkmaar', cultureTitle: 'Cheese and “proeven”',
    cultureBody: 'At Dutch markets you are encouraged to taste (“proeven”) the cheese before buying. Prices are fixed — bargaining is not common in the Netherlands.',
    culturePhrase: '“Mag ik even proeven?” — “May I taste?”', milestone: 'You can now shop at a market.',
    convo: [
      ['p', 'Goedemorgen! Kan ik u helpen?', 'Good morning! Can I help you?'],
      ['u', 'Hoeveel kost deze kaas?', 'Good — “deze” = this (de-words)'],
      ['p', 'Zes euro per stuk.', 'Six euros each.'],
      ['u', 'Mag ik even proeven?', 'Nice — very Dutch market etiquette'],
      ['p', 'Natuurlijk, alstublieft.', 'Of course, here you go.'],
    ],
    debrief: [['“Dit” vs “deze”', '“Dit” is for het-words, “deze” for de-words.'], ['No haggling', 'Dutch prices are fixed; ask for a taste, not a discount.']],
    grammarMini: 'Hoeveel kost …?', grammarTitle: '“Hoeveel kost?” — asking the price', grammarIntro: '“Kost” is for one item, “kosten” for several:',
    A: ['kost (kost)', '“costs” — one thing', 'Hoeveel kost dit?'], B: ['kosten (KOS-ten)', '“cost” — several', 'Hoeveel kosten de appels?'],
    clip: 'Kaasmarkt in Alkmaar', podcast: 'Mevrouw Smit op de markt — aflevering 5', article: 'De markt op zaterdag',
    reader: ['Op de markt zijn verse ', ['kaas', 'cheese'], ' en groente. Ik vroeg: “Hoeveel ', ['kost', 'costs'], ' dit?” Ze zei: “Zes euro.” Ik mocht eerst ', ['proeven', 'taste'], '.'],
    reviewWord: 'proeven', reviewSource: 'from your market visit, 1 day ago', reviewMeaning: 'to taste',
  },
  {
    ct: 'Noodgeval Emergency',
    partner: 'Operator Operator', role: 'emergency responder', place: 'helpline', scenarioTitle: 'Noodgeval · 112',
    prompt: 'I need an ambulance.', hint: '“Ik heb een ambulance nodig.” — “nodig” goes at the end.',
    bank: ['Ik', 'heb', 'een', 'ambulance', 'nodig', 'hulp'],
    bankEn: ['I', 'have', 'an', 'ambulance', 'needed', 'help'],
    correct: [0, 1, 2, 3, 4],
    okTitle: 'Perfect! 🎉', okBody: '“Ik heb … nodig” frames the thing you need — and “nodig” goes at the end.',
    noBody: 'Order: “Ik heb een ambulance nodig”.',
    cultureCaption: 'An ambulance in Amsterdam', cultureTitle: '112 across Europe',
    cultureBody: 'The Netherlands uses 112 for police, fire and ambulance — the same number as the rest of the EU. Operators speak English, but answer in Dutch if you can: say your address first.',
    culturePhrase: '“Help!” — “Help!”', milestone: 'You can now call for help in an emergency.',
    convo: [
      ['p', 'Alarmcentrale, wat is uw noodgeval?', "Emergency centre, what's your emergency?"],
      ['u', 'Ik heb een ambulance nodig. Er is een ongeluk gebeurd.', 'Clear — “ongeluk” = accident'],
      ['p', 'Wat is het adres?', "What's the address?"],
      ['u', 'Ik ben bij het station.', 'Good — “bij” = at / near'],
      ['p', 'Blijf rustig, de hulp is onderweg.', 'Stay calm, help is on its way.'],
    ],
    debrief: [['“Blijf rustig”', '“Blijf rustig” (stay calm) is what responders say.'], ['Address first', 'Say where you are before the details.']],
    grammarMini: 'Ik heb … nodig', grammarTitle: '“… nodig hebben” — to need', grammarIntro: 'The thing needed sits between “heb” and “nodig”:',
    A: ['heb … nodig', '“I need”', 'Ik heb hulp nodig.'], B: ['gebeurd (huh-BURT)', '“happened”', 'Er is een ongeluk gebeurd.'],
    clip: '112 — één nummer voor alles', podcast: 'Noodoproep — aflevering 6', article: 'Wat te doen bij een noodgeval',
    reader: ['Bij een ongeluk bel je ', ['112', 'the emergency number'], '. Zeg waar je bent en vraag om ', ['hulp', 'help'], '. De ', ['ambulance', 'ambulance'], ' komt snel.'],
    reviewWord: 'hulp', reviewSource: 'from your emergency call, 6 days ago', reviewMeaning: 'help',
  },
];
