import type { ChapterInput } from '../indic/build';

// Chapters 3–6 (family, hotel, market, emergency). Chapters 1–2 come from the base course.
export const hebrewExtra: ChapterInput[] = [
  {
    ct: 'משפחה Family',
    partner: 'מיכל Michal', role: 'friend', place: 'home', scenarioTitle: 'בבית · תל אביב',
    prompt: 'This is my father.', hint: '“זה אבא שלי” — “שלי” (of mine) goes after the noun.',
    bank: ['זה', 'אבא', 'שלי', 'אמא', 'אחות', 'הוא'],
    bankEn: ['this', 'father / dad', 'mine', 'mother / mom', 'sister', 'he'],
    correct: [0, 1, 2],
    okTitle: 'כל הכבוד! 🎉', okBody: 'Hebrew puts “שלי” (of mine) after the noun: “אבא שלי” — “dad of mine”.',
    noBody: 'Order: “זה” + “אבא” + “שלי”.',
    cultureCaption: 'Friday dinner in Tel Aviv', cultureTitle: 'Shabbat dinner',
    cultureBody: 'On Friday evening many Israeli families gather for Shabbat dinner — candles, challah bread and a long meal with grandparents, cousins and friends. Guests are always welcome to join.',
    culturePhrase: '“שבת שלום” (Shabbat shalom) — the Friday-evening greeting.', milestone: 'You can now introduce your family.',
    convo: [
      ['p', 'שלום! מי זה?', 'Hello! Who is that?'],
      ['u', 'זה אבא שלי.', 'Perfect — “שלי” after the noun'],
      ['p', 'נעים מאוד! ואיפה אמא שלך?', 'Nice to meet you! And where is your mother?'],
      ['u', 'היא בבית.', 'Good — “היא” = she'],
      ['p', 'איזה כיף! אשמח לפגוש אותה.', "How nice! I'd love to meet her."],
    ],
    debrief: [['“אבא” and “אמא”', '“אבא” and “אמא” are the everyday words for dad and mom, used at every age.'], ['Reading right to left', 'Hebrew reads right to left — take a moment to scan each word from the right.']],
    grammarMini: '… שלי', grammarTitle: '“שלי” — my / mine', grammarIntro: 'Possession comes after the noun:',
    A: ['שלי (sheli)', '“mine / my”', 'אבא שלי'], B: ['שלך (shelkha)', '“yours” (to a man)', 'אמא שלך'],
    clip: 'ארוחת שישי עם המשפחה', podcast: 'מיכל והמשפחה — פרק 3', article: 'המשפחה שלי',
    reader: ['המשפחה שלי גדולה. זה ', ['אבא', 'dad'], ' שלי וזאת ', ['אמא', 'mom'], ' שלי. יש לי ', ['אחות', 'sister'], ' אחת.'],
    reviewWord: 'אבא', reviewSource: 'from your family introduction, 2 days ago', reviewMeaning: 'dad',
  },
  {
    ct: 'מלון Hotel',
    partner: 'דני Danny', role: 'hotel receptionist', place: 'Tel Aviv hotel', scenarioTitle: 'במלון · תל אביב',
    prompt: 'I have a reservation.', hint: '“יש לי הזמנה” — literally “there is to me a reservation”.',
    bank: ['יש', 'לי', 'הזמנה', 'חדר', 'מפתח', 'בבקשה'],
    bankEn: ['there is', 'to me', 'a reservation', 'room', 'key', 'please'],
    correct: [0, 1, 2],
    okTitle: 'מצוין! 🎉', okBody: 'Hebrew has no verb “to have”: “יש לי” (“there is to me”) is how you say “I have”.',
    noBody: 'Order: “יש” + “לי” + “הזמנה”.',
    cultureCaption: 'A hotel on the Tel Aviv seafront', cultureTitle: 'The Israeli breakfast',
    cultureBody: 'Israeli hotel breakfast is a big buffet — salads, hummus, eggs, cheeses and fresh bread. Staff are direct and friendly, and a little informal.',
    culturePhrase: '“באיזו שעה ארוחת הבוקר?” — “What time is breakfast?”', milestone: 'You can now check into a hotel.',
    convo: [
      ['p', 'ערב טוב! איך אפשר לעזור?', 'Good evening! How can I help?'],
      ['u', 'ערב טוב. יש לי הזמנה.', 'Great — clear and polite'],
      ['p', 'על איזה שם?', 'Under what name?'],
      ['u', 'על שם כהן.', 'Good — “על שם” = under the name'],
      ['p', 'מצוין. הנה המפתח שלך.', "Excellent. Here's your key."],
    ],
    debrief: [['“בבקשה”', '“בבקשה” means both “please” and “you’re welcome”.'], ['No “to have”', 'Use “יש ל…” (there is to…) for possession.']],
    grammarMini: 'יש לי …', grammarTitle: '“יש לי” — I have', grammarIntro: 'Combine “יש” with “ל” + person:',
    A: ['יש לי (yesh li)', '“I have”', 'יש לי הזמנה.'], B: ['יש לך (yesh lekha)', '“you have” (to a man)', 'יש לך חדר.'],
    clip: 'הגעה למלון', podcast: 'דני בקבלה — פרק 4', article: 'לילה במלון',
    reader: ['במלון יש לי ', ['חדר', 'room'], '. הוא נקי ושקט. אני נשאר שני ', ['לילות', 'nights'], '.'],
    reviewWord: 'חדר', reviewSource: 'from your hotel booking, 5 days ago', reviewMeaning: 'room',
  },
  {
    ct: 'שוק Market',
    partner: 'אבי Avi', role: 'fruit vendor', place: 'Carmel Market', scenarioTitle: 'שוק הכרמל · תל אביב',
    prompt: 'How much does this cost?', hint: '“כמה זה עולה?” — “כמה” = how much.',
    bank: ['כמה', 'זה', 'עולה', 'יקר', 'זול', 'בבקשה'],
    bankEn: ['how much', 'this', 'costs', 'expensive', 'cheap', 'please'],
    correct: [0, 1, 2],
    okTitle: 'יפה! 🎉', okBody: '“כמה זה עולה?” — the standard way to ask a price.',
    noBody: 'Order: “כמה” + “זה” + “עולה”.',
    cultureCaption: 'Carmel Market, Tel Aviv', cultureTitle: 'Bargaining is expected',
    cultureBody: 'In Israeli markets vendors call out prices and bargaining is part of the fun. A friendly “אחי” (bro) or “יפה” (lovely) helps — and walking away slowly often lowers the price.',
    culturePhrase: '“אפשר הנחה?” — “Can I get a discount?”', milestone: 'You can now shop and bargain.',
    convo: [
      ['p', 'בואו, בואו! עגבניות טריות!', 'Come, come! Fresh tomatoes!'],
      ['u', 'כמה זה עולה?', 'Good — short and natural'],
      ['p', 'עשרה שקל לקילו.', 'Ten shekels a kilo.'],
      ['u', 'אפשר הנחה?', 'Nice — a polite way to bargain'],
      ['p', 'בשבילך, שמונה שקל.', 'For you, eight shekels.'],
    ],
    debrief: [['“שקל”', 'The currency is the “שקל” (shekel); the plural is “שקלים”, but after numbers you hear “שקל”.'], ['“בשבילך”', '“בשבילך” (for you) is the classic vendor’s line.']],
    grammarMini: 'כמה … עולה?', grammarTitle: '“כמה?” — asking how much', grammarIntro: 'Use “כמה” + “זה” + “עולה”:',
    A: ['כמה (kama)', '“how much / how many”', 'כמה זה עולה?'], B: ['הנחה (hanakha)', '“discount”', 'אפשר הנחה?'],
    clip: 'בוקר בשוק הכרמל', podcast: 'אבי בשוק — פרק 5', article: 'השוק בימי שישי',
    reader: ['בשוק יש פירות וירקות ', ['טריים', 'fresh'], '. שאלתי: “כמה זה ', ['עולה', 'costs'], '?” הוא אמר: “עשרה שקל.” ביקשתי ', ['הנחה', 'a discount'], '.'],
    reviewWord: 'הנחה', reviewSource: 'from your haggling session, 1 day ago', reviewMeaning: 'discount',
  },
  {
    ct: 'חירום Emergency',
    partner: 'מוקדן Operator', role: 'emergency responder', place: 'helpline', scenarioTitle: 'חירום · 101',
    prompt: 'I need an ambulance.', hint: '“אני צריך אמבולנס” — “צריך” = need (to a man speaking).',
    bank: ['אני', 'צריך', 'אמבולנס', 'עזרה', 'רופא', 'מהר'],
    bankEn: ['I', 'need (m.)', 'an ambulance', 'help', 'doctor', 'quickly'],
    correct: [0, 1, 2],
    okTitle: 'מעולה! 🎉', okBody: '“צריך” changes with the speaker: “צריך” (m.), “צריכה” (f.).',
    noBody: 'Order: “אני” + “צריך” + “אמבולנס”.',
    cultureCaption: 'An ambulance (Magen David Adom) in Israel', cultureTitle: '101 for the ambulance',
    cultureBody: 'In Israel, ambulance is 101 (Magen David Adom), police is 100 and fire is 102. Say your location first, then what happened.',
    culturePhrase: '“תעזרו לי!” — “Help me!”', milestone: 'You can now call for help in an emergency.',
    convo: [
      ['p', 'מגן דוד אדום, מה קרה?', 'Magen David Adom, what happened?'],
      ['u', 'אני צריך אמבולנס. הייתה תאונה.', 'Clear — “תאונה” = accident'],
      ['p', 'איפה אתה נמצא?', 'Where are you?'],
      ['u', 'אני ליד התחנה.', 'Good — “ליד” = next to'],
      ['p', 'תישאר רגוע, עזרה בדרך.', 'Stay calm, help is on the way.'],
    ],
    debrief: [['“תישאר רגוע”', '“תישאר רגוע” (stay calm) is what responders say.'], ['Gender endings', 'Verbs and adjectives change for men and women.']],
    grammarMini: 'אני צריך …', grammarTitle: '“צריך / צריכה” — need', grammarIntro: 'Pick the form that matches the speaker:',
    A: ['צריך (tsarikh)', '“I need” — man', 'אני צריך עזרה.'], B: ['צריכה (tsrikha)', '“I need” — woman', 'אני צריכה עזרה.'],
    clip: '101 — מד״א בפעולה', podcast: 'שיחת חירום — פרק 6', article: 'מה עושים בשעת חירום',
    reader: ['אם יש תאונה, מתקשרים ל־', ['101', 'the ambulance number'], '. אומרים איפה אתה ומבקשים ', ['עזרה', 'help'], '. ה', ['אמבולנס', 'ambulance'], ' מגיע מהר.'],
    reviewWord: 'עזרה', reviewSource: 'from your emergency call, 6 days ago', reviewMeaning: 'help',
  },
];
