import type { ChapterInput } from '../indic/build';

// Chapters 3–6 (family, hotel, market, emergency). Chapters 1–2 come from the base course.
export const portugueseExtra: ChapterInput[] = [
  {
    ct: 'Família Family',
    partner: 'Marina Marina', role: 'friend', place: 'home', scenarioTitle: 'Em casa · São Paulo',
    prompt: 'This is my father.', hint: 'Use “Este é o meu …” for a man, “Esta é a minha …” for a woman.',
    bank: ['Este', 'é', 'o meu', 'pai', 'mãe', 'irmã'],
    bankEn: ['this (m.)', 'is', 'my (m.)', 'father', 'mother', 'sister'],
    correct: [0, 1, 2, 3],
    okTitle: 'Muito bem! 🎉', okBody: '“Este é o meu pai” — “meu” matches a masculine noun; for “mãe” you say “a minha mãe”.',
    noBody: 'Order: “Este” + “é” + “o meu” + “pai”.',
    cultureCaption: 'Sunday lunch in São Paulo', cultureTitle: 'Sunday lunch is sacred',
    cultureBody: 'In Brazil, Sunday lunch is a long family event — grandparents, cousins and neighbours around one table, with churrasco or feijoada. Guests are always told to “sirva-se” (help yourself).',
    culturePhrase: '“Fique à vontade” — “make yourself at home.”', milestone: 'You can now introduce your family.',
    convo: [
      ['p', 'Oi! Quem é essa pessoa?', 'Hi! Who is this person?'],
      ['u', 'Este é o meu pai.', 'Perfect — “meu” agrees with “pai”'],
      ['p', 'Prazer! E a sua mãe, onde está?', 'Nice to meet you! And where is your mother?'],
      ['u', 'Ela está em casa.', 'Good — “ela” = she'],
      ['p', 'Que bom! Quero conhecê-la.', "Great! I'd love to meet her."],
    ],
    debrief: [['“Prazer”', '“Prazer” (pleasure) is the standard reply when meeting someone.'], ['“Mãe” vs “mamãe”', '“Mamãe” and “papai” are the warm, informal forms Brazilians use even as adults.']],
    grammarMini: 'o meu / a minha', grammarTitle: '“meu / minha” — my', grammarIntro: 'Possessives agree with the noun that follows:',
    A: ['o meu (u MEH-oo)', '“my” — masculine', 'Este é o meu pai.'], B: ['a minha (a MEEN-ya)', '“my” — feminine', 'Esta é a minha mãe.'],
    clip: 'Almoço de domingo em família', podcast: 'Marina e a família — episódio 3', article: 'A minha família',
    reader: ['A minha família é grande. Este é o meu ', ['pai', 'father'], ' e esta é a minha ', ['mãe', 'mother'], '. Eu tenho uma ', ['irmã', 'sister'], ' e dois primos.'],
    reviewWord: 'pai', reviewSource: 'from your family introduction, 2 days ago', reviewMeaning: 'father',
  },
  {
    ct: 'Hotel Hotel',
    partner: 'Ricardo Ricardo', role: 'hotel receptionist', place: 'São Paulo hotel', scenarioTitle: 'No hotel · São Paulo',
    prompt: 'I have a reservation.', hint: '“Tenho” = I have; “uma reserva” = a reservation.',
    bank: ['Eu', 'tenho', 'uma', 'reserva', 'quarto', 'chave'],
    bankEn: ['I', 'have', 'a', 'reservation', 'room', 'key'],
    correct: [0, 1, 2, 3],
    okTitle: 'Excelente! 🎉', okBody: '“Tenho uma reserva” — you can drop “Eu”; the verb ending already shows who is speaking.',
    noBody: 'Order: “Eu” + “tenho” + “uma” + “reserva”.',
    cultureCaption: 'A pousada breakfast table', cultureTitle: 'Breakfast is included — and generous',
    cultureBody: 'Brazilian hotels almost always include “café da manhã”: fresh fruit, bread, cheese, cake and strong coffee. Reception staff are warm and happy to chat.',
    culturePhrase: '“A que horas é o café da manhã?” — “What time is breakfast?”', milestone: 'You can now check into a hotel.',
    convo: [
      ['p', 'Boa tarde! Em que posso ajudar?', 'Good afternoon! How can I help?'],
      ['u', 'Boa tarde. Tenho uma reserva.', 'Great — clear and polite'],
      ['p', 'Em nome de quem, por favor?', 'Under whose name, please?'],
      ['u', 'Em nome de Silva.', 'Good — “em nome de” = under the name of'],
      ['p', 'Perfeito. Aqui está a sua chave.', "Perfect. Here's your key."],
    ],
    debrief: [['“Boa tarde”', 'Use “bom dia” until noon, “boa tarde” until evening, “boa noite” after.'], ['“Por favor”', 'Always add “por favor” — Brazilians value politeness.']],
    grammarMini: 'Eu tenho …', grammarTitle: '“ter” — to have', grammarIntro: 'The verb “ter” is used for reservations and for possession:',
    A: ['tenho (TEN-yoo)', '“I have”', 'Tenho uma reserva.'], B: ['tem (teng)', '“you / he / she has”', 'O hotel tem piscina.'],
    clip: 'Chegada à pousada', podcast: 'Ricardo na recepção — episódio 4', article: 'Uma noite no hotel',
    reader: ['No hotel eu tenho uma ', ['reserva', 'reservation'], '. O ', ['quarto', 'room'], ' é limpo e tranquilo. Vou ficar duas ', ['noites', 'nights'], '.'],
    reviewWord: 'reserva', reviewSource: 'from your hotel booking, 5 days ago', reviewMeaning: 'reservation',
  },
  {
    ct: 'Mercado Market',
    partner: 'Dona Lúcia Dona Lúcia', role: 'fruit vendor', place: 'São Paulo market', scenarioTitle: 'Na feira · São Paulo',
    prompt: 'How much is this?', hint: '“Quanto custa isto?” — “quanto” = how much.',
    bank: ['Quanto', 'custa', 'isto', 'caro', 'barato', 'por favor'],
    bankEn: ['how much', 'costs', 'this', 'expensive', 'cheap', 'please'],
    correct: [0, 1, 2],
    okTitle: 'Ótimo! 🎉', okBody: '“Quanto custa?” is the everyday way to ask a price; add “isto” (this) or point.',
    noBody: 'Order: “Quanto” + “custa” + “isto”.',
    cultureCaption: 'A street feira in São Paulo', cultureTitle: 'The feira and the pastel',
    cultureBody: 'Brazilian street markets (“feiras”) are weekly neighbourhood events. Vendors shout prices, offer samples and call everyone “freguês”. A pastel and sugarcane juice is the classic snack.',
    culturePhrase: '“Dá um desconto?” — “Can you give a discount?”', milestone: 'You can now shop and bargain.',
    convo: [
      ['p', 'Olha a banana! Fresquinha!', 'Look at the bananas! Fresh!'],
      ['u', 'Quanto custa a dúzia?', 'Good — “a dúzia” = a dozen'],
      ['p', 'Dez reais a dúzia.', 'Ten reais a dozen.'],
      ['u', 'Dá um desconto?', 'Nice — a friendly way to bargain'],
      ['p', 'Para você, oito reais.', 'For you, eight reais.'],
    ],
    debrief: [['“Dá um desconto?”', 'Literally “does it give a discount?” — polite and common at markets.'], ['Numbers', '“Oito” (8) and “dez” (10) come up constantly — practise them.']],
    grammarMini: 'Quanto custa …?', grammarTitle: '“Quanto custa?” — asking the price', grammarIntro: 'Use “custa” for one item and “custam” for several:',
    A: ['custa (KOOS-ta)', '“costs” — one thing', 'Quanto custa isto?'], B: ['custam (KOOS-tam)', '“cost” — several things', 'Quanto custam as maçãs?'],
    clip: 'Manhã na feira', podcast: 'Dona Lúcia e a feira — episódio 5', article: 'A feira de domingo',
    reader: ['Na feira há frutas e legumes ', ['frescos', 'fresh'], '. Eu perguntei: “Quanto ', ['custa', 'costs'], ' a dúzia?” A vendedora respondeu: “Dez reais.” Eu pedi um ', ['desconto', 'discount'], '.'],
    reviewWord: 'desconto', reviewSource: 'from your haggling session, 1 day ago', reviewMeaning: 'discount',
  },
  {
    ct: 'Emergência Emergency',
    partner: 'Operador Operator', role: 'emergency responder', place: 'helpline', scenarioTitle: 'Emergência · 192',
    prompt: 'I need an ambulance.', hint: '“Preciso de” = I need; “de” is required before the noun.',
    bank: ['Preciso', 'de', 'uma', 'ambulância', 'médico', 'ajuda'],
    bankEn: ['I need', 'of', 'an', 'ambulance', 'doctor', 'help'],
    correct: [0, 1, 2, 3],
    okTitle: 'Perfeito! 🎉', okBody: '“Preciso de” always takes “de”: “preciso de ajuda”, “preciso de um médico”.',
    noBody: 'Order: “Preciso” + “de” + “uma” + “ambulância”.',
    cultureCaption: 'An ambulance in São Paulo', cultureTitle: '192 for the ambulance',
    cultureBody: 'In Brazil the ambulance (SAMU) is 192, police is 190 and fire brigade is 193. Give your address first — a street and a landmark — then say what happened.',
    culturePhrase: '“Socorro!” — “Help!”', milestone: 'You can now call for help in an emergency.',
    convo: [
      ['p', 'SAMU, qual é a emergência?', "SAMU, what's the emergency?"],
      ['u', 'Preciso de uma ambulância. Houve um acidente.', 'Clear — “houve um acidente” = there was an accident'],
      ['p', 'Qual é o endereço?', "What's the address?"],
      ['u', 'Estou na Rua das Flores, perto da estação.', 'Good — “perto de” = near'],
      ['p', 'Fique calmo, a ajuda já está a caminho.', 'Stay calm, help is on its way.'],
    ],
    debrief: [['“Fique calmo”', '“Fique calmo” (stay calm) is what responders say.'], ['Address first', 'Give the location before the details.']],
    grammarMini: 'Preciso de …', grammarTitle: '“precisar de” — to need', grammarIntro: '“Precisar” is always followed by “de”:',
    A: ['preciso de (preh-SEE-zoo dee)', '“I need”', 'Preciso de ajuda.'], B: ['houve (OH-vee)', '“there was”', 'Houve um acidente.'],
    clip: '192 — SAMU em ação', podcast: 'Chamada de emergência — episódio 6', article: 'O que fazer numa emergência',
    reader: ['Se há um acidente, ligue para o ', ['192', 'the ambulance number'], '. Diga onde você está e peça ', ['ajuda', 'help'], '. A ', ['ambulância', 'ambulance'], ' chega rápido.'],
    reviewWord: 'ambulância', reviewSource: 'from your emergency call, 6 days ago', reviewMeaning: 'ambulance',
  },
];
