import { course, type ChapterInput } from './build';

const chapters: ChapterInput[] = [
  {
    ct: 'চাহ Tea culture',
    partner: 'ৰাজু Raju',
    role: 'tea seller',
    place: 'Guwahati tea stall',
    scenarioTitle: 'চাহৰ দোকান · Guwahati',
    goalTitle: 'Build it: order tea',
    goalLine: 'Order tea and make small talk.',
    goalShort: 'order tea',
    scenarioSub: 'Roleplay · order tea & chat',
    prompt: "I'd like a tea.",
    hint: 'Why “মোক … লাগে”?',
    bank: ['মোক', 'এটা', 'চাহ', 'লাগে', 'পানী', 'দুটা'],
    bankEn: ['to me', 'one (a)', 'tea', 'is needed', 'water', 'two'],
    correct: [0, 1, 2, 3],
    okTitle: 'বঢ়িয়া! 🎉',
    okBody: '“মোক … লাগে” is the natural “I’d like” — literally “to me … is needed.”',
    noBody: 'Start with “মোক” (to me), then “এটা” (one), the item, then “লাগে.”',
    cultureCaption: 'A tea stall in Guwahati · morning',
    cultureTitle: 'Assam is tea',
    cultureBody:
      "Assam grows more than half of India's tea. Locals often drink it strong — a favourite is “ৰঙা চাহ” (red tea, without milk) — and tea is offered to every guest.",
    culturePhrase: '“কিমান টকা?” (kimaan taka?) — “how much?”',
    milestone: 'You can now order tea — and chat while it brews.',
    convo: [
      ['p', 'নমস্কাৰ! কি দিম?', 'Hello! What shall I give you?'],
      ['u', 'মোক এটা চাহ লাগে।', 'Nice — “মোক … লাগে” is very natural'],
      ['p', 'গাখীৰ দি নে ৰঙা চাহ?', 'With milk, or red tea (black)?'],
      ['u', 'ৰঙা চাহ, ধন্যবাদ।', 'Perfect — “ৰঙা চাহ” = black tea'],
      ['p', 'দহ টকা হ’ল।', "That's ten rupees."],
    ],
    debrief: [
      ['“ধন্যবাদ”', '“ধন্যবাদ” is the standard thanks; “বহুত ধন্যবাদ” = thank you very much.'],
      ['The letters “ৰ” and “ৱ”', 'Assamese has its own letters “ৰ” (r) and “ৱ” (w) — and a soft “x” sound for “চ / ছ / স”.'],
    ],
    grammarMini: 'মোক … লাগে',
    grammarTitle: '“মোক … লাগে” — how to say “I want”',
    grammarIntro: 'Assamese says “to me, X is needed”:',
    A: ['মোক (mok)', '“to me” — the wanter', 'মোক চাহ লাগে।'],
    B: ['লাগে (lage)', '“is needed”', 'মোক পানী লাগে।'],
    clip: 'গুৱাহাটীৰ চাহ, মানুহৰ লগত',
    podcast: 'ৰাজুৰ লগত চাহ — ভাগ ৪',
    article: 'চাহৰ সৰু পৰম্পৰা',
    reader: [
      'অসমত পুৱাটো প্ৰায়ে এটা গৰম ',
      ['চাহ', 'tea'],
      ' ৰ লগত আৰম্ভ হয়। মানুহে দোকানৰ কাষত বহি সৰু কাপত চাহ ',
      ['খায়', 'drink (from খোৱা, to eat / drink)'],
      ' আৰু ',
      ['কথা পাতে', 'chat'],
      '। এইটো দিনটোৰ আটাইতকৈ মৰমলগা মুহূৰ্ত।',
    ],
    reviewWord: 'লাগে',
    reviewSource: 'from your tea order, 3 days ago',
    reviewMeaning: 'is needed (used for “I’d like”)',
  },
  {
    ct: 'দিশ Directions',
    partner: 'ৰূপা Rupa',
    role: 'local resident',
    place: 'Guwahati street',
    scenarioTitle: 'গুৱাহাটীৰ বাট · Guwahati',
    prompt: 'Where is the market?',
    hint: 'Start with the place: “বজাৰ কত আছে?”',
    bank: ['বজাৰ', 'কত', 'আছে', 'মই', 'যাওঁ', 'বাওঁফালে'],
    bankEn: ['market', 'where', 'is', 'I', 'go', 'to the left'],
    correct: [0, 1, 2],
    okTitle: 'বৰ ভাল! 🎉',
    okBody: 'Put the place first, then “কত আছে?” — literally “market where is?”',
    noBody: 'Name the place first, then ask “কত আছে?”.',
    cultureCaption: 'Fancy Bazaar, Guwahati · afternoon',
    cultureTitle: 'Directions by landmark',
    cultureBody:
      "In Indian cities people often give directions by landmarks — “after the temple, near the big tree” — rather than street names. It's normal to ask two or three people to be sure.",
    culturePhrase: '“ইয়াৰ পৰা কিমান দূৰ?” (iyar para kimaan dur?) — “how far from here?”',
    milestone: 'You can now ask your way around town.',
    convo: [
      ['p', 'নমস্কাৰ! সহায় লাগিবনে?', 'Hello! Do you need help?'],
      ['u', 'হয়, বজাৰ কত আছে?', 'Great — “কত আছে?” is the key question'],
      ['p', 'পোনে পোনে যাওক আৰু দ্বিতীয়টো চকত সোঁফালে ঘূৰক।', 'Go straight and turn right at the second crossing.'],
      ['u', 'ধন্যবাদ! ওচৰতে নেকি?', 'Nice — “ওচৰতে নেকি?” = is it near?'],
      ['p', 'হয়, পাঁচ মিনিটমান।', 'Yes, about five minutes.'],
    ],
    debrief: [
      ['“বাওঁ / সোঁ”', 'Left is “বাওঁ”, right is “সোঁ” — add “-ফালে” for “towards”: “সোঁফালে”.'],
      ['Polite endings', 'The polite imperative ends in “-ক”: “যাওক” (please go), “ঘূৰক” (please turn).'],
    ],
    grammarMini: '… কত আছে?',
    grammarTitle: '“… কত আছে?” — asking where something is',
    grammarIntro: 'Place first, then “কত আছে?”:',
    A: ['কত (kot)', '“where”', 'বজাৰ কত আছে?'],
    B: ['আছে (ase)', '“is / exists”', 'ষ্টেচন কত আছে?'],
    clip: 'ফান্সী বজাৰত ফুৰা',
    podcast: 'ৰূপাৰ লগত বাট বিচাৰি — ভাগ ৫',
    article: 'গুৱাহাটীত বাট সোধা',
    reader: [
      'গুৱাহাটীত বাট সুধিলে মানুহে সদায় সহায় কৰে। তেওঁলোকে কয়, “পোনে পোনে যাওক আৰু ',
      ['সোঁফালে', 'to the right'],
      ' ঘূৰক।” ওচৰতে ',
      ['বজাৰ', 'market'],
      ' আছে।',
    ],
    reviewWord: 'সোঁফালে',
    reviewSource: 'from your last direction request, 3 days ago',
    reviewMeaning: 'to the right',
  },
  {
    ct: 'পৰিয়াল Family',
    partner: 'মিনা Mina',
    role: 'friend',
    place: 'home',
    scenarioTitle: 'আমাৰ ঘৰ · Jorhat',
    prompt: 'This is my father.',
    hint: 'Use “এওঁ মোৰ …” for respectful introductions.',
    bank: ['এওঁ', 'মোৰ', 'দেউতা', 'মা', 'ভনী', 'আছে'],
    bankEn: ['this person (respectful)', 'my', 'father', 'mother', 'younger sister', 'is'],
    correct: [0, 1, 2],
    okTitle: 'অতি উত্তম! 🎉',
    okBody: '“এওঁ” is the respectful “this person” — use it for elders; “এয়া” is for things or children.',
    noBody: 'Say “এওঁ” (this person), then “মোৰ” (my), then the relation.',
    cultureCaption: 'A family feast at Bihu · evening',
    cultureTitle: 'Family at Bihu',
    cultureBody:
      "Bihu, the Assamese festival, is when families gather: elders are greeted with a 'gamosa' — a woven cloth — and blessed, and meals are shared.",
    culturePhrase: '“আই” (aai) — “mother” (also grandmother), a deeply loved word in Assamese.',
    milestone: 'You can now introduce your family.',
    convo: [
      ['p', 'নমস্কাৰ! এওঁ কোন?', 'Hello! Who is this?'],
      ['u', 'এওঁ মোৰ দেউতা।', 'Perfect — “এওঁ” shows respect'],
      ['p', 'ভাল! আৰু আপোনাৰ মা কত আছে?', 'Lovely! And where is your mother?'],
      ['u', 'তেওঁ ঘৰত আছে।', 'Good — “ঘৰত” = at home'],
      ['p', 'মই তেওঁক লগ পাব বিচাৰো।', "I'd love to meet her."],
    ],
    debrief: [
      ['“দেউতা” and “আই”', '“দেউতা” (father) and “আই” (mother) are the warm everyday words; “মা” is common in modern speech too.'],
      ['Respect for elders', 'Elders are addressed with the respectful “আপুনি”, not the casual “তুমি”.'],
    ],
    grammarMini: 'এওঁ …',
    grammarTitle: '“এওঁ” — introducing people respectfully',
    grammarIntro: 'Use “এওঁ” for a respected person, “এয়া” for things or children:',
    A: ['এওঁ (eu)', '“this person” — respectful', 'এওঁ মোৰ দেউতা।'],
    B: ['মোৰ (mur)', '“my”', 'মোৰ মা ঘৰত আছে।'],
    clip: 'দেওবাৰৰ ভোজ, সকলো লগত',
    podcast: 'মিনাৰ লগত ঘৰুৱা কথা — ভাগ ৬',
    article: 'মোৰ পৰিয়াল',
    reader: [
      'মোৰ পৰিয়াল ডাঙৰ। এওঁ মোৰ ',
      ['দেউতা', 'father'],
      ' আৰু তেওঁ মোৰ ',
      ['মা', 'mother'],
      '। মোৰ এজনী ',
      ['ভনী', 'younger sister'],
      ' আছে।',
    ],
    reviewWord: 'দেউতা',
    reviewSource: 'from your family introduction, 2 days ago',
    reviewMeaning: 'father',
  },
  {
    ct: 'হোটেল Hotel',
    partner: 'ৰাজেশ Rajesh',
    role: 'hotel receptionist',
    place: 'Guwahati hotel',
    scenarioTitle: 'হোটেল · Guwahati',
    prompt: 'I need a room for two nights.',
    hint: 'Say “দুৰাতিৰ বাবে” for “for two nights”.',
    bank: ['মোক', 'দুৰাতিৰ', 'বাবে', 'এটা', 'কোঠা', 'লাগে'],
    bankEn: ['to me', 'of two nights', 'for', 'one (a)', 'room', 'is needed'],
    correct: [0, 1, 2, 3, 4, 5],
    okTitle: 'সুন্দৰ! 🎉',
    okBody: '“বাবে” (for) follows the noun: “দুৰাতিৰ বাবে” — “for two nights”.',
    noBody: 'Order: “মোক” + “দুৰাতিৰ বাবে” + “এটা কোঠা” + “লাগে”.',
    cultureCaption: 'A hotel on the Brahmaputra · check-in',
    cultureTitle: 'A welcome with tea',
    cultureBody:
      'Hotels in Assam often greet guests with a cup of fresh Assam tea or a glass of water — and sometimes a gamosa for special visitors.',
    culturePhrase: '“কোঠাৰ ভাড়া কিমান?” (kothar bhara kimaan?) — “how much is the room?”',
    milestone: 'You can now check into a hotel.',
    convo: [
      ['p', 'নমস্কাৰ, আদৰণি! কি সহায় কৰিম?', 'Welcome! How can I help?'],
      ['u', 'মোক দুৰাতিৰ বাবে এটা কোঠা লাগে।', 'Great — a clear, polite request'],
      ['p', 'নিশ্চয়। ব্ৰেকফাষ্ট লাগিবনে?', 'Certainly. Would you like breakfast?'],
      ['u', 'হয়, অনুগ্ৰহ কৰি।', 'Polite — “অনুগ্ৰহ কৰি” = please'],
      ['p', 'ঠিক আছে, এইয়া আপোনাৰ চাবি।', "All right, here's your key."],
    ],
    debrief: [
      ['“অনুগ্ৰহ কৰি”', '“অনুগ্ৰহ কৰি” means “please” — a polite opener in service settings.'],
      ['Counting words', 'Assamese adds a counting word after numbers: “এটা কোঠা”, “দুটা কোঠা”.'],
    ],
    grammarMini: '… বাবে',
    grammarTitle: '“… বাবে” — “for”',
    grammarIntro: '“বাবে” follows the noun:',
    A: ['বাবে (babe)', '“for”', 'দুৰাতিৰ বাবে'],
    B: ['কোঠা (kotha)', '“room”', 'এটা কোঠা লাগে।'],
    clip: 'ব্ৰহ্মপুত্ৰৰ পাৰৰ ৰাতিপুৱা',
    podcast: 'ৰাজেশৰ লগত আতিথ্য — ভাগ ৭',
    article: 'হোটেলত থকা',
    reader: [
      'হোটেলত মই এটা ',
      ['কোঠা', 'room'],
      ' ল’লো। ই পৰিষ্কাৰ আৰু শান্ত। মই দুৰাতি ',
      ['থাকিম', 'will stay'],
      '।',
    ],
    reviewWord: 'কোঠা',
    reviewSource: 'from your hotel booking, 5 days ago',
    reviewMeaning: 'room',
  },
  {
    ct: 'বজাৰ Market',
    partner: 'ৰহিম Rahim',
    role: 'fruit vendor',
    place: 'Guwahati market',
    scenarioTitle: 'বজাৰ · Guwahati',
    prompt: 'How much is this?',
    hint: '“কিমান?” is how you ask “how much?”.',
    bank: ['এইটোৰ', 'দাম', 'কিমান', 'সস্তা', 'মোক', 'দুটা'],
    bankEn: ['of this', 'price', 'how much', 'cheap', 'to me', 'two'],
    correct: [0, 1, 2],
    okTitle: 'বাহ! 🎉',
    okBody: '“এইটোৰ দাম কিমান?” — literally “this-of price how-much?”',
    noBody: 'Say “এইটোৰ” (of this), “দাম” (price), then “কিমান?”.',
    cultureCaption: 'Paltan Bazaar, Guwahati · morning',
    cultureTitle: 'Bargaining is a friendly chat',
    cultureBody:
      'In Indian markets the first price is rarely the last. Bargaining is friendly, with a smile — and walking away slowly often gets you the best price.',
    culturePhrase: '“অলপ কমাই দিয়ক” (olop komai diyok) — “reduce it a little”.',
    milestone: 'You can now shop and bargain.',
    convo: [
      ['p', 'আহক, আহক! নতুন কল আছে।', 'Come, come! Fresh bananas!'],
      ['u', 'এইটোৰ দাম কিমান?', 'Good — short and natural'],
      ['p', 'চল্লিশ টকা ডজন।', 'Forty rupees a dozen.'],
      ['u', 'অলপ কমাই দিয়ক।', 'Nice — “কমাই দিয়ক” = please reduce'],
      ['p', 'ঠিক আছে, পঁয়ত্ৰিশ দিয়ক।', 'Okay, give thirty-five.'],
    ],
    debrief: [
      ['Numbers', 'Assamese numbers like “পঁয়ত্ৰিশ” (35) and “চল্লিশ” (40) are irregular — worth memorising.'],
      ['“অলপ”', '“অলপ” (a little) softens any request: “অলপ কমাই দিয়ক”.'],
    ],
    grammarMini: '… কিমান?',
    grammarTitle: '“কিমান?” — asking how much',
    grammarIntro: 'Name the item, then ask:',
    A: ['কিমান (kimaan)', '“how much / how many”', 'এইটোৰ দাম কিমান?'],
    B: ['কমাই (komai)', '“reducing”', 'অলপ কমাই দিয়ক।'],
    clip: 'পল্টন বজাৰৰ ৰাতিপুৱা',
    podcast: 'ৰহিমৰ লগত বজাৰ — ভাগ ৮',
    article: 'সপ্তাহিক বজাৰ',
    reader: [
      'বজাৰত নতুন ফল আৰু পাচলি পোৱা যায়। মই দোকানীক সুধিলো, “এইটোৰ দাম ',
      ['কিমান', 'how much'],
      '?” তেওঁ ক’লে, “চল্লিশ টকা।” মই অলপ ',
      ['কমাই', 'reduce'],
      ' দিবলৈ ক’লো।',
    ],
    reviewWord: 'কমাই',
    reviewSource: 'from your haggling session, 1 day ago',
    reviewMeaning: 'reducing / lowering',
  },
  {
    ct: 'জৰুৰী Emergency',
    partner: 'অপাৰেটৰ Operator',
    role: 'emergency responder',
    place: 'helpline',
    scenarioTitle: 'হেল্পলাইন · 112',
    prompt: 'Please call a doctor.',
    hint: '“মাতক” is the polite command: “please call”.',
    bank: ['অনুগ্ৰহ কৰি', 'ডাক্তৰক', 'মাতক', 'সহায়', 'মোৰ', 'কৰক'],
    bankEn: ['please', 'the doctor (to)', 'call', 'help', 'my', 'do'],
    correct: [0, 1, 2],
    okTitle: 'উত্তম! 🎉',
    okBody: 'Polite commands end in “-ক”: “মাতক”, “কৰক”, “যাওক”.',
    noBody: 'Say “অনুগ্ৰহ কৰি”, then who (“ডাক্তৰক”), then the command “মাতক”.',
    cultureCaption: 'An ambulance in Guwahati',
    cultureTitle: '112 — one number for everything',
    cultureBody:
      "India's single emergency number is 112, which connects to police, fire and ambulance. Say your location first — a landmark helps most — then what has happened.",
    culturePhrase: '“সহায় কৰক!” (xohay korok!) — “help!”',
    milestone: 'You can now call for help in an emergency.',
    convo: [
      ['p', 'হেল’, জৰুৰীকালীন সেৱা। কি হ’ল?', 'Hello, emergency service. What happened?'],
      ['u', 'সহায় কৰক! দুৰ্ঘটনা হৈছে।', 'Clear — “দুৰ্ঘটনা” = accident'],
      ['p', 'আপুনি কত আছে?', 'Where are you?'],
      ['u', 'মই ষ্টেচনৰ ওচৰত আছো।', 'Good — “ওচৰত” = near'],
      ['p', 'শান্ত থাকক, এম্বুলেন্স আহি আছে।', 'Stay calm, the ambulance is coming.'],
    ],
    debrief: [
      ['“শান্ত থাকক”', '“শান্ত থাকক” (stay calm) is what responders say — you will hear it.'],
      ['Say the place first', 'Name your location first: “মই ষ্টেচনৰ ওচৰত আছো।”'],
    ],
    grammarMini: 'মাতক / কৰক',
    grammarTitle: 'Polite commands end in “-ক”',
    grammarIntro: 'Add “-ক” to the verb stem:',
    A: ['মাতক (matok)', '“please call”', 'ডাক্তৰক মাতক।'],
    B: ['কৰক (korok)', '“please do”', 'সহায় কৰক।'],
    clip: '১১২ — এটা নম্বৰ, সকলো সহায়',
    podcast: 'জৰুৰী কল — ভাগ ৯',
    article: 'জৰুৰীকালীন অৱস্থাত কি কৰিব',
    reader: [
      'দুৰ্ঘটনা হ’লে ভয় নকৰিব। ',
      ['112', 'the emergency number'],
      ' ত ফোন কৰি কওক, “',
      ['সহায় কৰক', 'help'],
      '!” এম্বুলেন্স সোনকালে আহে।',
    ],
    reviewWord: 'এম্বুলেন্স',
    reviewSource: 'from your emergency call, 6 days ago',
    reviewMeaning: 'ambulance',
  },
];

export const assamese = course(
  { name: 'Assamese', code: 'AS', font: 'bn', locale: 'as-IN', greeting: 'নমস্কাৰ, Maya', accent: 'Assam (Guwahati)' },
  chapters
);
