import { course, type ChapterInput } from './build';

const chapters: ChapterInput[] = [
  {
    ct: 'ચા Chai culture',
    partner: 'કિશન Kishan',
    role: 'chai wala',
    place: 'Ahmedabad tea stall',
    scenarioTitle: 'ચાની કીટલી · Ahmedabad',
    goalTitle: 'Build it: order chai',
    goalLine: 'Order chai and make small talk.',
    goalShort: 'order chai',
    scenarioSub: 'Roleplay · order chai & chat',
    prompt: "I'd like one tea.",
    hint: 'Why “મને … જોઈએ છે”?',
    bank: ['મને', 'એક', 'ચા', 'જોઈએ છે', 'પાણી', 'બે'],
    bankEn: ['to me', 'one', 'tea', '(is) needed', 'water', 'two'],
    correct: [0, 1, 2, 3],
    okTitle: 'બહુ સરસ! 🎉',
    okBody: '“મને … જોઈએ છે” is the natural “I’d like” — literally “to me … is needed.”',
    noBody: 'Start with “મને” (to me), then the number, the item, then “જોઈએ છે.”',
    cultureCaption: 'A chai kitli in Ahmedabad · morning',
    cultureTitle: 'Chai, and a little something to nibble',
    cultureBody:
      'In Gujarat, chai rarely comes alone. It is paired with crunchy farsan, thepla or fafda-jalebi, and the stall becomes the neighbourhood meeting point.',
    culturePhrase: '“કેટલા થયા?” (ketla thayaa?) — “how much is it?”, used everywhere.',
    milestone: 'You can now order chai — and chat while it brews.',
    convo: [
      ['p', 'નમસ્તે! શું આપું?', 'Hello! What shall I give you?'],
      ['u', 'મને એક ચા જોઈએ છે.', 'Nice — “મને … જોઈએ છે” is very natural'],
      ['p', 'આદુવાળી કે સાદી?', 'Ginger or plain?'],
      ['u', 'આદુવાળી, આભાર.', 'Perfect — “આદુવાળી” = the ginger one'],
      ['p', 'બસ દસ રૂપિયા.', 'Just ten rupees.'],
    ],
    debrief: [
      ['“આભાર” vs “ધન્યવાદ”', '“આભાર” is the warm everyday thanks; “ધન્યવાદ” is more formal.'],
      ['Breathy consonants', 'Gujarati has breathy sounds like “ભ” (bh) and “ઘ” (gh) — release a little air.'],
    ],
    grammarMini: 'મને … જોઈએ છે',
    grammarTitle: '“મને … જોઈએ છે” — how to say “I want”',
    grammarIntro: 'Gujarati says “to me, X is needed”:',
    A: ['મને (mane)', '“to me” — the wanter', 'મને ચા જોઈએ છે.'],
    B: ['જોઈએ છે (joie chhe)', '“is needed / wanted” — doesn’t change', 'મને પાણી જોઈએ છે.'],
    clip: 'અમદાવાદની ચા, લોકો સાથે',
    podcast: 'કિશન સાથે ચા — એપિસોડ ૪',
    article: 'ચાની નાની પરંપરા',
    reader: [
      'ગુજરાતમાં સવારની શરૂઆત ઘણીવાર ગરમ ',
      ['ચા', 'chai — tea'],
      ' થી થાય છે. લોકો કીટલી પાસે ઊભા રહીને નાના કપમાં ચા ',
      ['પીએ છે', 'drink (they drink — from પીવું, to drink)'],
      ' અને ',
      ['વાતો કરે છે', 'chat'],
      '. આ દિવસની સૌથી મીઠી પળ છે.',
    ],
    reviewWord: 'જોઈએ',
    reviewSource: 'from your chai order, 3 days ago',
    reviewMeaning: 'needed / wanted (used for “I’d like”)',
  },
  {
    ct: 'દિશા Directions',
    partner: 'નીતા Neeta',
    role: 'local resident',
    place: 'Ahmedabad street',
    scenarioTitle: 'અમદાવાદની શેરી · Ahmedabad',
    prompt: 'Where is the market?',
    hint: 'Start with the place: “બજાર ક્યાં છે?”',
    bank: ['બજાર', 'ક્યાં', 'છે', 'હું', 'જાઉં', 'ડાબી બાજુ'],
    bankEn: ['market', 'where', 'is', 'I', 'go', 'left side'],
    correct: [0, 1, 2],
    okTitle: 'ખૂબ સરસ! 🎉',
    okBody: 'Put the place first, then “ક્યાં છે?” — literally “market where is?”',
    noBody: 'Name the place first, then ask “ક્યાં છે?”.',
    cultureCaption: 'A pol in Old Ahmedabad · afternoon',
    cultureTitle: 'Navigating the pols',
    cultureBody:
      "Old Ahmedabad is a maze of narrow 'pols' — gated neighbourhood lanes. Directions are given by landmarks like a temple, a chowk or a famous sweet shop.",
    culturePhrase: '“અહીંથી કેટલું દૂર છે?” (ahinthi ketlu door chhe?) — “how far is it from here?”',
    milestone: 'You can now ask your way around town.',
    convo: [
      ['p', 'નમસ્તે! મદદ જોઈએ છે?', 'Hello! Need help?'],
      ['u', 'હા, બજાર ક્યાં છે?', 'Great — “ક્યાં છે?” is the key question'],
      ['p', 'સીધા જાઓ અને બીજા ચોકમાંથી જમણી બાજુ વળો.', 'Go straight and turn right at the second crossing.'],
      ['u', 'આભાર! નજીક છે?', 'Nice — “નજીક છે?” = is it near?'],
      ['p', 'હા, પાંચ મિનિટ દૂર છે.', 'Yes, five minutes away.'],
    ],
    debrief: [
      ['“ડાબી / જમણી”', 'Left is “ડાબી”, right is “જમણી” — they agree with the feminine “બાજુ” (side).'],
      ['Polite “તમે”', 'With strangers use “તમે” (formal you), not “તું”.'],
    ],
    grammarMini: '… ક્યાં છે?',
    grammarTitle: '“… ક્યાં છે?” — asking where something is',
    grammarIntro: 'Place first, then “ક્યાં છે?”:',
    A: ['ક્યાં (kyaan)', '“where”', 'બજાર ક્યાં છે?'],
    B: ['છે (chhe)', '“is” — present tense of “to be”', 'સ્ટેશન ક્યાં છે?'],
    clip: 'પોળોમાં લટાર',
    podcast: 'નીતા સાથે રસ્તો શોધતાં — એપિસોડ ૫',
    article: 'અમદાવાદમાં રસ્તો પૂછવો',
    reader: [
      'અમદાવાદમાં રસ્તો પૂછવો સહેલો છે. લોકો હંમેશા મદદ કરે છે. તેઓ કહે છે, “સીધા જાઓ અને ',
      ['જમણી', 'right'],
      ' બાજુ વળો.” નજીકમાં જ ',
      ['બજાર', 'market'],
      ' છે.',
    ],
    reviewWord: 'જમણી',
    reviewSource: 'from your last direction request, 3 days ago',
    reviewMeaning: 'right',
  },
  {
    ct: 'પરિવાર Family',
    partner: 'મીરા Meera',
    role: 'friend',
    place: 'home',
    scenarioTitle: 'અમારું ઘર · Surat',
    prompt: 'This is my father.',
    hint: 'Use “આ મારા … છે” for introductions.',
    bank: ['આ', 'મારા', 'પિતા', 'છે', 'માતા', 'બહેન'],
    bankEn: ['this', 'my', 'father', 'is', 'mother', 'sister'],
    correct: [0, 1, 2, 3],
    okTitle: 'અદ્ભુત! 🎉',
    okBody: '“મારા” goes with a masculine word like “પિતા”; for a feminine word it becomes “મારી”.',
    noBody: 'Say “આ” (this), then “મારા” (my), the person, and finish with “છે”.',
    cultureCaption: 'A family thali in Surat · evening',
    cultureTitle: 'Family comes first',
    cultureBody:
      "In Gujarati homes, meals are shared and elders are served first. Introductions usually mention family and hometown, and relatives have precise names — for example 'mama' for mother's brother and 'kaka' for father's younger brother.",
    culturePhrase: '“બા” (baa) — “grandmother”, said with great affection.',
    milestone: 'You can now introduce your family.',
    convo: [
      ['p', 'નમસ્તે! આ કોણ છે?', 'Hello! Who is this?'],
      ['u', 'આ મારા પિતા છે.', 'Perfect — “મારા” fits “પિતા”'],
      ['p', 'સરસ! અને તમારી મમ્મી ક્યાં છે?', 'Lovely! And where is your mom?'],
      ['u', 'તે ઘરે છે.', 'Good — “તે” = she'],
      ['p', 'મને તેમને મળવાનું ગમશે.', "I'd love to meet her."],
    ],
    debrief: [
      ['“મમ્મી” and “પપ્પા”', '“મમ્મી” and “પપ્પા” are warm and common; “માતા” and “પિતા” are formal.'],
      ['“ભાઈ” and “બહેન”', 'Add “ભાઈ” or “બહેન” after a name for respect: “રમેશભાઈ”.'],
    ],
    grammarMini: 'આ … છે',
    grammarTitle: '“આ … છે” — introducing people',
    grammarIntro: 'Use “આ” (this) and “છે”:',
    A: ['આ (aa)', '“this”', 'આ મારા પિતા છે.'],
    B: ['છે (chhe)', '“is” — also used respectfully', 'તે મારી માતા છે.'],
    clip: 'રવિવારનું ભોજન, સૌ સાથે',
    podcast: 'મીરા સાથે ઘરની વાતો — એપિસોડ ૬',
    article: 'મારું કુટુંબ',
    reader: [
      'મારું કુટુંબ મોટું છે. આ મારા ',
      ['પિતા', 'father'],
      ' છે અને તે મારી ',
      ['માતા', 'mother'],
      ' છે. મારે એક ',
      ['બહેન', 'sister'],
      ' છે.',
    ],
    reviewWord: 'પિતા',
    reviewSource: 'from your family introduction, 2 days ago',
    reviewMeaning: 'father',
  },
  {
    ct: 'હોટેલ Hotel',
    partner: 'રાજેશ Rajesh',
    role: 'hotel receptionist',
    place: 'Ahmedabad hotel',
    scenarioTitle: 'હોટેલ · Ahmedabad',
    prompt: 'I need a room for two nights.',
    hint: 'Say “બે રાત માટે” for “for two nights”.',
    bank: ['મને', 'બે', 'રાત', 'માટે', 'રૂમ', 'જોઈએ છે'],
    bankEn: ['to me', 'two', 'night(s)', 'for', 'room', 'needed'],
    correct: [0, 1, 2, 3, 4, 5],
    okTitle: 'શાબાશ! 🎉',
    okBody: '“માટે” (for) follows the noun: “બે રાત માટે” — “two nights for”.',
    noBody: 'Order: “મને” + “બે રાત માટે” + “રૂમ” + “જોઈએ છે”.',
    cultureCaption: 'A heritage hotel in Ahmedabad · check-in',
    cultureTitle: 'A welcome with a drink',
    cultureBody:
      'Many Gujarati hotels welcome guests with a glass of chaas (buttermilk) or water. Breakfast often means theplas, khakhra and chai.',
    culturePhrase: '“રૂમનું ભાડું કેટલું?” (room nu bhaadu ketlu?) — “what is the room rent?”',
    milestone: 'You can now check into a hotel.',
    convo: [
      ['p', 'નમસ્તે, સ્વાગત છે! શું મદદ કરું?', 'Welcome! How can I help?'],
      ['u', 'મને બે રાત માટે રૂમ જોઈએ છે.', 'Great — a clear, polite request'],
      ['p', 'ચોક્કસ. નાસ્તો જોઈએ છે?', 'Certainly. Would you like breakfast?'],
      ['u', 'હા, કૃપા કરીને.', 'Polite — “કૃપા કરીને” = please'],
      ['p', 'બરાબર, આ તમારી ચાવી.', "All right, here's your key."],
    ],
    debrief: [
      ['“કૃપા કરીને”', '“કૃપા કરીને” is a polite “please”; friends just say “પ્લીઝ”.'],
      ['Numbers', '“બે” (two) comes before the noun: “બે રાત”.'],
    ],
    grammarMini: '… માટે',
    grammarTitle: '“… માટે” — “for”',
    grammarIntro: '“માટે” follows the noun:',
    A: ['માટે (maate)', '“for”', 'બે રાત માટે'],
    B: ['રાત (raat)', '“night”', 'એક રાત માટે'],
    clip: 'હવેલીની સવાર',
    podcast: 'રાજેશ સાથે મહેમાનગતિ — એપિસોડ ૭',
    article: 'હોટેલમાં રોકાણ',
    reader: [
      'હોટેલમાં મેં ',
      ['રૂમ', 'room'],
      ' લીધો. તે સ્વચ્છ અને શાંત છે. હું બે ',
      ['રાત', 'nights'],
      ' રોકાઈશ.',
    ],
    reviewWord: 'રૂમ',
    reviewSource: 'from your hotel booking, 5 days ago',
    reviewMeaning: 'room',
  },
  {
    ct: 'બજાર Market',
    partner: 'કાકા Kaka',
    role: 'fruit vendor',
    place: 'Ahmedabad market',
    scenarioTitle: 'માણેક ચોક · Ahmedabad',
    prompt: 'How much is this?',
    hint: '“કેટલાનું?” is the everyday way to ask a price.',
    bank: ['આ', 'કેટલાનું', 'છે', 'સસ્તું', 'મને', 'બે'],
    bankEn: ['this', 'how much (for)', 'is', 'cheap', 'to me', 'two'],
    correct: [0, 1, 2],
    okTitle: 'વાહ! 🎉',
    okBody: '“આ કેટલાનું છે?” is short and natural — literally “this how-much-of is?”',
    noBody: 'Point with “આ” (this), then ask “કેટલાનું છે?”.',
    cultureCaption: 'Manek Chowk, Ahmedabad · evening',
    cultureTitle: 'Bargaining is a friendly game',
    cultureBody:
      'In Indian markets the first price is rarely the last. Bargaining is friendly, with a smile — and walking away slowly often gets you the best price.',
    culturePhrase: '“થોડું ઓછું કરો” (thodu ochhu karo) — “reduce it a little”.',
    milestone: 'You can now shop and bargain.',
    convo: [
      ['p', 'આવો, આવો! તાજાં કેળાં છે.', 'Come, come! Fresh bananas!'],
      ['u', 'આ કેટલાનું છે?', 'Good — short and natural'],
      ['p', 'ચાલીસ રૂપિયા ડઝન.', 'Forty rupees a dozen.'],
      ['u', 'થોડું ઓછું કરો ને.', 'Nice — “ઓછું કરો” = lower it'],
      ['p', 'સારું, પાંત્રીસ આપો.', 'Okay, give thirty-five.'],
    ],
    debrief: [
      ['Numbers', 'Gujarati numbers like “પાંત્રીસ” (35) and “ચાલીસ” (40) are irregular — worth memorising.'],
      ['“ને” softener', '“ને” makes a request friendlier: “ઓછું કરો ને.”'],
    ],
    grammarMini: '… કેટલાનું?',
    grammarTitle: '“કેટલાનું?” — asking the price',
    grammarIntro: 'Point to the item, then ask:',
    A: ['કેટલાનું (ketlaanu)', '“how much (for)?”', 'આ કેટલાનું છે?'],
    B: ['ઓછું (ochhu)', '“less / lower”', 'થોડું ઓછું કરો.'],
    clip: 'માણેક ચોકની સાંજ',
    podcast: 'કાકા સાથે બજાર — એપિસોડ ૮',
    article: 'અઠવાડિક બજાર',
    reader: [
      'બજારમાં તાજાં ફળો અને શાકભાજી મળે છે. મેં દુકાનદારને પૂછ્યું, “આ ',
      ['કેટલાનું', 'how much for'],
      ' છે?” તેણે કહ્યું, “ચાલીસ રૂપિયા.” મેં થોડું ',
      ['ઓછું', 'less'],
      ' કરવા કહ્યું.',
    ],
    reviewWord: 'ઓછું',
    reviewSource: 'from your haggling session, 1 day ago',
    reviewMeaning: 'less / lower',
  },
  {
    ct: 'કટોકટી Emergency',
    partner: 'ઓપરેટર Operator',
    role: 'emergency responder',
    place: 'helpline',
    scenarioTitle: 'હેલ્પલાઇન · 112',
    prompt: 'Please call a doctor.',
    hint: '“બોલાવો” is the polite command: “please call”.',
    bank: ['કૃપા કરીને', 'ડૉક્ટરને', 'બોલાવો', 'મદદ', 'મારા', 'કરો'],
    bankEn: ['please', 'the doctor (to)', 'call', 'help', 'my', 'do'],
    correct: [0, 1, 2],
    okTitle: 'ઉત્તમ! 🎉',
    okBody: 'Polite commands end in “-ો”: “બોલાવો”, “કરો”, “આવો”.',
    noBody: 'Say “કૃપા કરીને”, then who (“ડૉક્ટરને”), then the command “બોલાવો”.',
    cultureCaption: 'An ambulance in Ahmedabad',
    cultureTitle: '112 — one number for everything',
    cultureBody:
      "India's single emergency number is 112, which connects to police, fire and ambulance. Say your location first — a landmark helps most — then what has happened.",
    culturePhrase: '“મદદ કરો!” (madad karo!) — “help!”',
    milestone: 'You can now call for help in an emergency.',
    convo: [
      ['p', 'હેલો, ઇમરજન્સી સેવા. શું થયું?', 'Hello, emergency service. What happened?'],
      ['u', 'મદદ કરો! અકસ્માત થયો છે.', 'Clear — “અકસ્માત” = accident'],
      ['p', 'તમે ક્યાં છો?', 'Where are you?'],
      ['u', 'હું સ્ટેશન પાસે છું.', 'Good — “પાસે” = near'],
      ['p', 'શાંત રહો, એમ્બ્યુલન્સ આવી રહી છે.', 'Stay calm, the ambulance is coming.'],
    ],
    debrief: [
      ['“શાંત રહો”', '“શાંત રહો” (stay calm) is what responders say — you will hear it.'],
      ['Say the place first', 'Name your location first: “હું સ્ટેશન પાસે છું.”'],
    ],
    grammarMini: 'બોલાવો / કરો',
    grammarTitle: 'Polite commands',
    grammarIntro: 'Polite commands end in “-ો”:',
    A: ['બોલાવો (bolaavo)', '“please call”', 'ડૉક્ટરને બોલાવો.'],
    B: ['કરો (karo)', '“please do”', 'મદદ કરો.'],
    clip: '૧૧૨ — એક નંબર, બધી મદદ',
    podcast: 'ઇમરજન્સી કૉલ — એપિસોડ ૯',
    article: 'કટોકટીમાં શું કરવું',
    reader: [
      'અકસ્માત થાય તો ગભરાશો નહીં. ',
      ['112', 'the emergency number'],
      ' પર ફોન કરો અને કહો, “',
      ['મદદ કરો', 'help'],
      '!” એમ્બ્યુલન્સ જલદી આવે છે.',
    ],
    reviewWord: 'એમ્બ્યુલન્સ',
    reviewSource: 'from your emergency call, 6 days ago',
    reviewMeaning: 'ambulance',
  },
];

export const gujarati = course(
  { name: 'Gujarati', code: 'GU', font: 'gu', locale: 'gu-IN', greeting: 'નમસ્તે, Maya', accent: 'Gujarat (Ahmedabad)' },
  chapters
);
