import { course, type ChapterInput } from './build';

const chapters: ChapterInput[] = [
  {
    ct: 'ಕಾಫಿ Coffee culture',
    partner: 'ರಮೇಶ್ Ramesh',
    role: 'darshini server',
    place: 'Bengaluru darshini',
    scenarioTitle: 'ದರ್ಶಿನಿ · Bengaluru',
    goalTitle: 'Build it: order coffee',
    goalLine: 'Order filter coffee and make small talk.',
    goalShort: 'order coffee',
    scenarioSub: 'Roleplay · order coffee & chat',
    prompt: "I'd like one coffee.",
    hint: 'Why “ನನಗೆ … ಬೇಕು”?',
    bank: ['ನನಗೆ', 'ಒಂದು', 'ಕಾಫಿ', 'ಬೇಕು', 'ನೀರು', 'ಎರಡು'],
    bankEn: ['to me', 'one', 'coffee', '(is) wanted', 'water', 'two'],
    correct: [0, 1, 2, 3],
    okTitle: 'ಚೆನ್ನಾಗಿದೆ! 🎉',
    okBody: '“ನನಗೆ … ಬೇಕು” is the natural “I’d like” — literally “to me … is wanted.”',
    noBody: 'Start with “ನನಗೆ” (to me), then “ಒಂದು” (one), the item, then “ಬೇಕು.”',
    cultureCaption: 'A darshini in Bengaluru · morning',
    cultureTitle: 'Filter coffee, standing up',
    cultureBody:
      "In Karnataka, strong filter coffee served in a small steel tumbler is a morning ritual. At a 'darshini' you stand, sip and chat, and a plate of idli-vada is the usual companion.",
    culturePhrase: '“ಎಷ್ಟು?” (eshtu?) — “how much?”, the one word you’ll use everywhere.',
    milestone: 'You can now order coffee — and chat while it brews.',
    convo: [
      ['p', 'ನಮಸ್ಕಾರ! ಏನು ಕೊಡಲಿ?', 'Hello! What shall I give you?'],
      ['u', 'ನನಗೆ ಒಂದು ಕಾಫಿ ಬೇಕು.', 'Nice — “ನನಗೆ … ಬೇಕು” is very natural'],
      ['p', 'ಸಕ್ಕರೆ ಹಾಕಿ ಅಥವಾ ಬೇಡವೇ?', 'With sugar or without?'],
      ['u', 'ಸಕ್ಕರೆ ಕಡಿಮೆ, ಧನ್ಯವಾದ.', 'Perfect — “ಕಡಿಮೆ” = less'],
      ['p', 'ಹತ್ತು ರೂಪಾಯಿ ಆಯಿತು.', "That's ten rupees."],
    ],
    debrief: [
      ['“ಧನ್ಯವಾದ”', '“ಧನ್ಯವಾದ” is the standard thanks; friends also say “ಥ್ಯಾಂಕ್ಸ್”.'],
      ['Retroflex “ಟ / ಡ”', "Kannada's “ಟ” and “ಡ” curl the tongue back — softer than English “t” and “d”."],
    ],
    grammarMini: 'ನನಗೆ … ಬೇಕು',
    grammarTitle: '“ನನಗೆ … ಬೇಕು” — how to say “I want”',
    grammarIntro: 'Kannada says “to me, X is wanted”:',
    A: ['ನನಗೆ (nanage)', '“to me” — the wanter', 'ನನಗೆ ಕಾಫಿ ಬೇಕು.'],
    B: ['ಬೇಕು (beku)', '“is wanted” — never changes', 'ನನಗೆ ನೀರು ಬೇಕು.'],
    clip: 'ಬೆಂಗಳೂರಿನ ಕಾಫಿ, ಜನರ ಜೊತೆ',
    podcast: 'ರಮೇಶ್ ಜೊತೆ ಕಾಫಿ — ಸಂಚಿಕೆ 4',
    article: 'ಕಾಫಿಯ ಚಿಕ್ಕ ಪದ್ಧತಿ',
    reader: [
      'ಕರ್ನಾಟಕದಲ್ಲಿ ಬೆಳಗಿನ ಆರಂಭ ಹೆಚ್ಚಾಗಿ ಒಂದು ಬಿಸಿ ',
      ['ಕಾಫಿ', 'coffee'],
      'ಯಿಂದ ಆಗುತ್ತದೆ. ಜನರು ದರ್ಶಿನಿಯಲ್ಲಿ ನಿಂತು ಸಣ್ಣ ಲೋಟದಲ್ಲಿ ಕಾಫಿ ',
      ['ಕುಡಿಯುತ್ತಾರೆ', 'drink (they drink — from ಕುಡಿ, to drink)'],
      ' ಮತ್ತು ',
      ['ಹರಟೆ ಹೊಡೆಯುತ್ತಾರೆ', 'chat'],
      '. ಇದು ದಿನದ ಅತ್ಯಂತ ಸಿಹಿಯಾದ ಕ್ಷಣ.',
    ],
    reviewWord: 'ಬೇಕು',
    reviewSource: 'from your coffee order, 3 days ago',
    reviewMeaning: 'is wanted (used for “I’d like”)',
  },
  {
    ct: 'ದಾರಿ Directions',
    partner: 'ಸುನೀತಾ Sunita',
    role: 'local resident',
    place: 'Bengaluru street',
    scenarioTitle: 'ಬೆಂಗಳೂರಿನ ರಸ್ತೆ · Bengaluru',
    prompt: 'Where is the market?',
    hint: 'Start with the place: “ಮಾರುಕಟ್ಟೆ ಎಲ್ಲಿದೆ?”',
    bank: ['ಮಾರುಕಟ್ಟೆ', 'ಎಲ್ಲಿದೆ', 'ನಾನು', 'ಹೋಗಬೇಕು', 'ಎಡಕ್ಕೆ', 'ಕಾಫಿ'],
    bankEn: ['market', 'where is', 'I', 'must go', 'to the left', 'coffee'],
    correct: [0, 1],
    okTitle: 'ಅದ್ಭುತ! 🎉',
    okBody: 'Put the place first, then “ಎಲ್ಲಿದೆ?” — literally “market where-is?”',
    noBody: 'Name the place first, then ask “ಎಲ್ಲಿದೆ?”.',
    cultureCaption: 'A lane in Basavanagudi, Bengaluru · afternoon',
    cultureTitle: 'Landmarks and circles',
    cultureBody:
      "In Bengaluru, directions use landmarks and 'circles' (traffic roundabouts) — 'turn at the Jayanagar circle, after the temple'. It's common to confirm with two people.",
    culturePhrase: '“ಇಲ್ಲಿಂದ ಎಷ್ಟು ದೂರ?” (illinda eshtu dura?) — “how far from here?”',
    milestone: 'You can now ask your way around town.',
    convo: [
      ['p', 'ನಮಸ್ಕಾರ! ಸಹಾಯ ಬೇಕೆ?', 'Hello! Need help?'],
      ['u', 'ಹೌದು, ಮಾರುಕಟ್ಟೆ ಎಲ್ಲಿದೆ?', 'Great — “ಎಲ್ಲಿದೆ?” is the key question'],
      ['p', 'ನೇರವಾಗಿ ಹೋಗಿ, ಎರಡನೇ ಸರ್ಕಲ್‌ನಲ್ಲಿ ಬಲಕ್ಕೆ ತಿರುಗಿ.', 'Go straight, and turn right at the second circle.'],
      ['u', 'ಧನ್ಯವಾದ! ಹತ್ತಿರವೇ?', 'Nice — “ಹತ್ತಿರವೇ?” = is it near?'],
      ['p', 'ಹೌದು, ಐದು ನಿಮಿಷ ಸಾಕು.', 'Yes, five minutes is enough.'],
    ],
    debrief: [
      ['“ಎಡ / ಬಲ”', 'Left is “ಎಡ”, right is “ಬಲ” — add “-ಕ್ಕೆ” for direction: “ಬಲಕ್ಕೆ” (to the right).'],
      ['Polite “ನೀವು”', 'With strangers use “ನೀವು” (formal you), not “ನೀನು”.'],
    ],
    grammarMini: '… ಎಲ್ಲಿದೆ?',
    grammarTitle: '“… ಎಲ್ಲಿದೆ?” — asking where something is',
    grammarIntro: 'Place first, then “ಎಲ್ಲಿದೆ?”:',
    A: ['ಎಲ್ಲಿ (elli)', '“where”', 'ಮಾರುಕಟ್ಟೆ ಎಲ್ಲಿದೆ?'],
    B: ['ಇದೆ (ide)', '“is / exists”', 'ಇಲ್ಲಿ ಬ್ಯಾಂಕ್ ಇದೆ.'],
    clip: 'ಬಸವನಗುಡಿಯ ಗಲ್ಲಿಗಳಲ್ಲಿ ನಡಿಗೆ',
    podcast: 'ಸುನೀತಾ ಜೊತೆ ದಾರಿ ಹುಡುಕುತ್ತಾ — ಸಂಚಿಕೆ 5',
    article: 'ಬೆಂಗಳೂರಿನಲ್ಲಿ ದಾರಿ ಕೇಳುವುದು',
    reader: [
      'ಬೆಂಗಳೂರಿನಲ್ಲಿ ದಾರಿ ಕೇಳುವುದು ಸುಲಭ. ಜನರು ಯಾವಾಗಲೂ ಸಹಾಯ ಮಾಡುತ್ತಾರೆ. ಅವರು ಹೇಳುತ್ತಾರೆ, “ನೇರವಾಗಿ ಹೋಗಿ ',
      ['ಬಲಕ್ಕೆ', 'to the right'],
      ' ತಿರುಗಿ.” ಹತ್ತಿರವೇ ',
      ['ಮಾರುಕಟ್ಟೆ', 'market'],
      ' ಇದೆ.',
    ],
    reviewWord: 'ಬಲಕ್ಕೆ',
    reviewSource: 'from your last direction request, 3 days ago',
    reviewMeaning: 'to the right',
  },
  {
    ct: 'ಕುಟುಂಬ Family',
    partner: 'ಮೀನಾ Meena',
    role: 'friend',
    place: 'home',
    scenarioTitle: 'ನಮ್ಮ ಮನೆ · Mysuru',
    prompt: 'This is my father.',
    hint: 'Use “ಇವರು ನನ್ನ …” for respectful introductions.',
    bank: ['ಇವರು', 'ನನ್ನ', 'ತಂದೆ', 'ತಾಯಿ', 'ತಂಗಿ', 'ಇದ್ದಾರೆ'],
    bankEn: ['this person (respectful)', 'my', 'father', 'mother', 'younger sister', 'is (respectful)'],
    correct: [0, 1, 2],
    okTitle: 'ಅತ್ಯುತ್ತಮ! 🎉',
    okBody: '“ಇವರು” is the respectful “this person” — use it for elders.',
    noBody: 'Say “ಇವರು” (this person), then “ನನ್ನ” (my), then the relation.',
    cultureCaption: 'A festival meal in Mysuru · evening',
    cultureTitle: 'Family at Dasara',
    cultureBody:
      "During Dasara, Mysuru's grand festival, families visit elders, share sweets like Mysore pak and watch the lit-up palace together.",
    culturePhrase: '“ಅಮ್ಮ” (amma) — “mother”, the first word every learner meets.',
    milestone: 'You can now introduce your family.',
    convo: [
      ['p', 'ನಮಸ್ಕಾರ! ಇವರು ಯಾರು?', 'Hello! Who is this?'],
      ['u', 'ಇವರು ನನ್ನ ತಂದೆ.', 'Perfect — “ಇವರು” shows respect'],
      ['p', 'ಚೆನ್ನಾಗಿದೆ! ನಿಮ್ಮ ತಾಯಿ ಎಲ್ಲಿದ್ದಾರೆ?', 'Lovely! Where is your mother?'],
      ['u', 'ಅವರು ಮನೆಯಲ್ಲಿದ್ದಾರೆ.', 'Good — “ಮನೆಯಲ್ಲಿ” = at home'],
      ['p', 'ನಾನು ಅವರನ್ನು ಭೇಟಿಯಾಗಲು ಬಯಸುತ್ತೇನೆ.', "I'd love to meet her."],
    ],
    debrief: [
      ['“ಅಪ್ಪ” and “ಅಮ್ಮ”', '“ಅಪ್ಪ” (father) and “ಅಮ್ಮ” (mother) are the warm everyday words; “ತಂದೆ” and “ತಾಯಿ” are more formal.'],
      ['Respectful plural', 'Elders take a plural verb: “ಅವರು ಬಂದರು” — even for one person.'],
    ],
    grammarMini: 'ಇವರು …',
    grammarTitle: '“ಇವರು …” — introducing people',
    grammarIntro: 'Use “ಇವರು” (this person, respectful):',
    A: ['ಇವರು (ivaru)', '“this person” — respectful', 'ಇವರು ನನ್ನ ತಂದೆ.'],
    B: ['ನನ್ನ (nanna)', '“my”', 'ಇವರು ನನ್ನ ತಾಯಿ.'],
    clip: 'ಭಾನುವಾರದ ಊಟ, ಎಲ್ಲರೂ ಒಟ್ಟಿಗೆ',
    podcast: 'ಮೀನಾ ಜೊತೆ ಮನೆ ಮಾತು — ಸಂಚಿಕೆ 6',
    article: 'ನನ್ನ ಕುಟುಂಬ',
    reader: [
      'ನನ್ನ ಕುಟುಂಬ ದೊಡ್ಡದು. ಇವರು ನನ್ನ ',
      ['ತಂದೆ', 'father'],
      ' ಮತ್ತು ಇವರು ನನ್ನ ',
      ['ತಾಯಿ', 'mother'],
      '. ನನಗೆ ಒಬ್ಬ ',
      ['ತಂಗಿ', 'younger sister'],
      ' ಇದ್ದಾಳೆ.',
    ],
    reviewWord: 'ತಂದೆ',
    reviewSource: 'from your family introduction, 2 days ago',
    reviewMeaning: 'father',
  },
  {
    ct: 'ಹೋಟೆಲ್ Hotel',
    partner: 'ರಾಜೇಶ್ Rajesh',
    role: 'hotel receptionist',
    place: 'Bengaluru hotel',
    scenarioTitle: 'ಹೋಟೆಲ್ · Bengaluru',
    prompt: 'I need a room for two nights.',
    hint: 'Say “ಎರಡು ರಾತ್ರಿಗೆ” for “for two nights”.',
    bank: ['ನನಗೆ', 'ಎರಡು', 'ರಾತ್ರಿಗೆ', 'ಒಂದು', 'ಕೋಣೆ', 'ಬೇಕು'],
    bankEn: ['to me', 'two', 'for nights', 'one / a', 'room', 'wanted'],
    correct: [0, 1, 2, 3, 4, 5],
    okTitle: 'ಭೇಷ್! 🎉',
    okBody: 'The ending “-ಗೆ” marks who or what something is for: “ರಾತ್ರಿಗೆ” = for the night(s).',
    noBody: 'Order: “ನನಗೆ” + “ಎರಡು ರಾತ್ರಿಗೆ” + “ಒಂದು ಕೋಣೆ” + “ಬೇಕು”.',
    cultureCaption: 'A lodge in Hampi · check-in',
    cultureTitle: 'A welcome with a drink',
    cultureBody:
      'Many Karnataka hotels welcome guests with water or hot coffee. Breakfast is often idli, dosa or bisi bele bath.',
    culturePhrase: '“ಕೋಣೆಯ ಬಾಡಿಗೆ ಎಷ್ಟು?” (koneya baadige eshtu?) — “how much is the room?”',
    milestone: 'You can now check into a hotel.',
    convo: [
      ['p', 'ನಮಸ್ಕಾರ, ಸ್ವಾಗತ! ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?', 'Welcome! How can I help?'],
      ['u', 'ನನಗೆ ಎರಡು ರಾತ್ರಿಗೆ ಒಂದು ಕೋಣೆ ಬೇಕು.', 'Great — a clear, polite request'],
      ['p', 'ಖಂಡಿತ. ತಿಂಡಿ ಬೇಕೆ?', 'Certainly. Would you like breakfast?'],
      ['u', 'ಬೇಕು, ದಯವಿಟ್ಟು.', 'Polite — “ದಯವಿಟ್ಟು” = please'],
      ['p', 'ಸರಿ, ಇಗೋ ನಿಮ್ಮ ಕೀಲಿ.', "All right, here's your key."],
    ],
    debrief: [
      ['“ದಯವಿಟ್ಟು”', '“ದಯವಿಟ್ಟು” is a polite “please”, used with strangers and in service settings.'],
      ['Numbers', '“ಎರಡು” (two) comes before the noun: “ಎರಡು ರಾತ್ರಿ”.'],
    ],
    grammarMini: '… -ಗೆ',
    grammarTitle: '“-ಗೆ” — “to / for”',
    grammarIntro: 'The ending “-ಗೆ” marks who or what something is for:',
    A: ['ರಾತ್ರಿಗೆ (raatrige)', '“for the night”', 'ಎರಡು ರಾತ್ರಿಗೆ'],
    B: ['ನನಗೆ (nanage)', '“to / for me”', 'ನನಗೆ ಒಂದು ಕೋಣೆ ಬೇಕು.'],
    clip: 'ಹಂಪಿಯ ಬೆಳಗು',
    podcast: 'ರಾಜೇಶ್ ಜೊತೆ ಆತಿಥ್ಯ — ಸಂಚಿಕೆ 7',
    article: 'ಹೋಟೆಲ್‌ನಲ್ಲಿ ವಾಸ',
    reader: [
      'ಹೋಟೆಲ್‌ನಲ್ಲಿ ನಾನು ಒಂದು ',
      ['ಕೋಣೆ', 'room'],
      ' ತೆಗೆದುಕೊಂಡೆ. ಅದು ಶುಚಿಯಾಗಿದೆ ಮತ್ತು ಶಾಂತವಾಗಿದೆ. ನಾನು ಎರಡು ',
      ['ರಾತ್ರಿ', 'nights'],
      ' ಉಳಿಯುತ್ತೇನೆ.',
    ],
    reviewWord: 'ಕೋಣೆ',
    reviewSource: 'from your hotel booking, 5 days ago',
    reviewMeaning: 'room',
  },
  {
    ct: 'ಮಾರುಕಟ್ಟೆ Market',
    partner: 'ಶಾರದಾ Sharada',
    role: 'fruit vendor',
    place: 'Bengaluru market',
    scenarioTitle: 'ಮಾರುಕಟ್ಟೆ · Bengaluru',
    prompt: 'How much is this?',
    hint: '“ಎಷ್ಟು?” is how you ask “how much?”.',
    bank: ['ಇದಕ್ಕೆ', 'ಎಷ್ಟು', 'ಬೆಲೆ', 'ಕಡಿಮೆ', 'ನನಗೆ', 'ಎರಡು'],
    bankEn: ['for this', 'how much', 'price', 'less', 'to me', 'two'],
    correct: [0, 1],
    okTitle: 'ವಾವ್! 🎉',
    okBody: '“ಇದಕ್ಕೆ ಎಷ್ಟು?” — literally “for-this how-much?”',
    noBody: 'Say “ಇದಕ್ಕೆ” (for this), then “ಎಷ್ಟು?”.',
    cultureCaption: 'KR Market, Bengaluru · morning',
    cultureTitle: 'Bargaining is a friendly chat',
    cultureBody:
      'In Indian markets the first price is rarely the last. Bargaining is friendly, with a smile — and walking away slowly often gets you the best price.',
    culturePhrase: '“ಸ್ವಲ್ಪ ಕಡಿಮೆ ಮಾಡಿ” (svalpa kadime maadi) — “reduce it a little”.',
    milestone: 'You can now shop and bargain.',
    convo: [
      ['p', 'ಬನ್ನಿ, ಬನ್ನಿ! ತಾಜಾ ಬಾಳೆಹಣ್ಣು ಇದೆ.', 'Come, come! Fresh bananas!'],
      ['u', 'ಇದಕ್ಕೆ ಎಷ್ಟು?', 'Good — short and natural'],
      ['p', 'ಡಜನ್‌ಗೆ ನಲವತ್ತು ರೂಪಾಯಿ.', 'Forty rupees a dozen.'],
      ['u', 'ಸ್ವಲ್ಪ ಕಡಿಮೆ ಮಾಡಿ.', 'Nice — “ಕಡಿಮೆ ಮಾಡಿ” = please reduce'],
      ['p', 'ಸರಿ, ಮುವ್ವತ್ತೈದು ಕೊಡಿ.', 'Okay, give thirty-five.'],
    ],
    debrief: [
      ['Numbers', 'Kannada numbers like “ಮುವ್ವತ್ತೈದು” (35) and “ನಲವತ್ತು” (40) are long — say them slowly.'],
      ['“ಸ್ವಲ್ಪ”', '“ಸ್ವಲ್ಪ” (a little) softens any request: “ಸ್ವಲ್ಪ ಕಡಿಮೆ ಮಾಡಿ”.'],
    ],
    grammarMini: '… ಎಷ್ಟು?',
    grammarTitle: '“ಎಷ್ಟು?” — asking the price',
    grammarIntro: 'Point to the item, then ask:',
    A: ['ಎಷ್ಟು (eshtu)', '“how much”', 'ಇದಕ್ಕೆ ಎಷ್ಟು?'],
    B: ['ಕಡಿಮೆ (kadime)', '“less / lower”', 'ಸ್ವಲ್ಪ ಕಡಿಮೆ ಮಾಡಿ.'],
    clip: 'ಕೆ.ಆರ್. ಮಾರುಕಟ್ಟೆಯ ಬೆಳಗು',
    podcast: 'ಶಾರದಾ ಜೊತೆ ಮಾರುಕಟ್ಟೆ — ಸಂಚಿಕೆ 8',
    article: 'ವಾರದ ಸಂತೆ',
    reader: [
      'ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ತಾಜಾ ಹಣ್ಣು ತರಕಾರಿ ಸಿಗುತ್ತದೆ. ನಾನು ವ್ಯಾಪಾರಿಯನ್ನು ಕೇಳಿದೆ, “ಇದಕ್ಕೆ ',
      ['ಎಷ್ಟು', 'how much'],
      '?” ಅವರು ಹೇಳಿದರು, “ನಲವತ್ತು ರೂಪಾಯಿ.” ನಾನು ಸ್ವಲ್ಪ ',
      ['ಕಡಿಮೆ', 'less'],
      ' ಮಾಡಲು ಹೇಳಿದೆ.',
    ],
    reviewWord: 'ಕಡಿಮೆ',
    reviewSource: 'from your haggling session, 1 day ago',
    reviewMeaning: 'less / lower',
  },
  {
    ct: 'ತುರ್ತು Emergency',
    partner: 'ಆಪರೇಟರ್ Operator',
    role: 'emergency responder',
    place: 'helpline',
    scenarioTitle: 'ಸಹಾಯವಾಣಿ · 112',
    prompt: 'Please call a doctor.',
    hint: '“ಕರೆಯಿರಿ” is the polite command: “please call”.',
    bank: ['ದಯವಿಟ್ಟು', 'ವೈದ್ಯರನ್ನು', 'ಕರೆಯಿರಿ', 'ಸಹಾಯ', 'ನನ್ನ', 'ಮಾಡಿ'],
    bankEn: ['please', 'the doctor', 'call', 'help', 'my', 'do'],
    correct: [0, 1, 2],
    okTitle: 'ಉತ್ತಮ! 🎉',
    okBody: 'Polite commands add “-ಇರಿ” or “-ಿ”: “ಕರೆಯಿರಿ”, “ಮಾಡಿ”, “ಬನ್ನಿ”.',
    noBody: 'Say “ದಯವಿಟ್ಟು”, then who (“ವೈದ್ಯರನ್ನು”), then the command “ಕರೆಯಿರಿ”.',
    cultureCaption: 'An ambulance in Bengaluru',
    cultureTitle: '112 — one number for everything',
    cultureBody:
      "India's single emergency number is 112, which connects to police, fire and ambulance. Say your location first — a landmark helps most — then what has happened.",
    culturePhrase: '“ಸಹಾಯ ಮಾಡಿ!” (sahaaya maadi!) — “help!”',
    milestone: 'You can now call for help in an emergency.',
    convo: [
      ['p', 'ಹಲೋ, ತುರ್ತು ಸೇವೆ. ಏನಾಯಿತು?', 'Hello, emergency service. What happened?'],
      ['u', 'ಸಹಾಯ ಮಾಡಿ! ಅಪಘಾತ ಆಗಿದೆ.', 'Clear — “ಅಪಘಾತ” = accident'],
      ['p', 'ನೀವು ಎಲ್ಲಿದ್ದೀರಿ?', 'Where are you?'],
      ['u', 'ನಾನು ನಿಲ್ದಾಣದ ಹತ್ತಿರ ಇದ್ದೇನೆ.', 'Good — “ಹತ್ತಿರ” = near'],
      ['p', 'ಶಾಂತವಾಗಿರಿ, ಆಂಬ್ಯುಲೆನ್ಸ್ ಬರುತ್ತಿದೆ.', 'Stay calm, the ambulance is coming.'],
    ],
    debrief: [
      ['“ಶಾಂತವಾಗಿರಿ”', '“ಶಾಂತವಾಗಿರಿ” (stay calm) is what responders say — you will hear it.'],
      ['Say the place first', 'Name your location first: “ನಾನು ನಿಲ್ದಾಣದ ಹತ್ತಿರ ಇದ್ದೇನೆ.”'],
    ],
    grammarMini: 'ಕರೆಯಿರಿ / ಮಾಡಿ',
    grammarTitle: 'Polite commands',
    grammarIntro: 'Add a polite ending to the verb stem:',
    A: ['ಕರೆಯಿರಿ (kareyiri)', '“please call”', 'ವೈದ್ಯರನ್ನು ಕರೆಯಿರಿ.'],
    B: ['ಮಾಡಿ (maadi)', '“please do”', 'ಸಹಾಯ ಮಾಡಿ.'],
    clip: '112 — ಒಂದು ನಂಬರ್, ಎಲ್ಲಾ ಸಹಾಯ',
    podcast: 'ತುರ್ತು ಕರೆ — ಸಂಚಿಕೆ 9',
    article: 'ತುರ್ತು ಸಂದರ್ಭದಲ್ಲಿ ಏನು ಮಾಡಬೇಕು',
    reader: [
      'ಅಪಘಾತವಾದರೆ ಗಾಬರಿಯಾಗಬೇಡಿ. ',
      ['112', 'the emergency number'],
      ' ಗೆ ಕರೆ ಮಾಡಿ, “',
      ['ಸಹಾಯ ಮಾಡಿ', 'help'],
      '!” ಎಂದು ಹೇಳಿ. ಆಂಬ್ಯುಲೆನ್ಸ್ ಬೇಗ ಬರುತ್ತದೆ.',
    ],
    reviewWord: 'ಆಂಬ್ಯುಲೆನ್ಸ್',
    reviewSource: 'from your emergency call, 6 days ago',
    reviewMeaning: 'ambulance',
  },
];

export const kannada = course(
  { name: 'Kannada', code: 'KN', font: 'kn', locale: 'kn-IN', greeting: 'ನಮಸ್ಕಾರ, Maya', accent: 'Karnataka (Bengaluru)' },
  chapters
);
