import { course, type ChapterInput } from './build';

const chapters: ChapterInput[] = [
  {
    ct: 'ചായ Chaya culture',
    partner: 'മോഹൻ Mohan',
    role: 'chayakada owner',
    place: 'Kochi tea shop',
    scenarioTitle: 'ചായക്കട · Kochi',
    goalTitle: 'Build it: order chaya',
    goalLine: 'Order chaya (tea) and make small talk.',
    goalShort: 'order chaya',
    scenarioSub: 'Roleplay · order chaya & chat',
    prompt: "I'd like one tea.",
    hint: 'Why “എനിക്ക് … വേണം”?',
    bank: ['എനിക്ക്', 'ഒരു', 'ചായ', 'വേണം', 'വെള്ളം', 'രണ്ട്'],
    bankEn: ['to me', 'one', 'tea', '(is) wanted', 'water', 'two'],
    correct: [0, 1, 2, 3],
    okTitle: 'കൊള്ളാം! 🎉',
    okBody: '“എനിക്ക് … വേണം” is the natural “I’d like” — literally “to me … is wanted.”',
    noBody: 'Start with “എനിക്ക്” (to me), then “ഒരു” (one), the item, then “വേണം.”',
    cultureCaption: 'A chayakada in Kochi · morning',
    cultureTitle: 'The chayakada is the village newspaper',
    cultureBody:
      "In Kerala the 'chayakada' (tea shop) is where politics, cricket and gossip are debated over a glass of chaya and a plate of banana fritters (pazhampori).",
    culturePhrase: '“എത്രയാണ്?” (ethrayaanu?) — “how much is it?”',
    milestone: 'You can now order chaya — and chat while it brews.',
    convo: [
      ['p', 'നമസ്കാരം! എന്താ വേണ്ടത്?', 'Hello! What would you like?'],
      ['u', 'എനിക്ക് ഒരു ചായ വേണം.', 'Nice — “എനിക്ക് … വേണം” is very natural'],
      ['p', 'ഇഞ്ചി ചായയാണോ സാധാരണ ചായയാണോ?', 'Ginger tea or plain tea?'],
      ['u', 'ഇഞ്ചി ചായ, നന്ദി.', 'Perfect — “ഇഞ്ചി” = ginger'],
      ['p', 'പത്തു രൂപയാണ്.', "That's ten rupees."],
    ],
    debrief: [
      ['“നന്ദി”', '“നന്ദി” is the everyday “thank you” — short and warm.'],
      ['The “ഴ” sound', "Malayalam's famous “ഴ” (zh), as in “വാഴപ്പഴം” (banana), curls the tongue back — listen closely."],
    ],
    grammarMini: 'എനിക്ക് … വേണം',
    grammarTitle: '“എനിക്ക് … വേണം” — how to say “I want”',
    grammarIntro: 'Malayalam says “to me, X is wanted”:',
    A: ['എനിക്ക് (enikku)', '“to me” — the wanter', 'എനിക്ക് ചായ വേണം.'],
    B: ['വേണം (venam)', '“is wanted” — never changes', 'എനിക്ക് വെള്ളം വേണം.'],
    clip: 'കൊച്ചിയിലെ ചായ, ആളുകൾക്കൊപ്പം',
    podcast: 'മോഹനോടൊപ്പം ചായ — എപ്പിസോഡ് 4',
    article: 'ചായയുടെ ചെറിയ ശീലം',
    reader: [
      'കേരളത്തിൽ പ്രഭാതം മിക്കപ്പോഴും ഒരു ചൂടുള്ള ',
      ['ചായ', 'tea'],
      'യോടെ തുടങ്ങുന്നു. ആളുകൾ ചായക്കടയിൽ ഇരുന്ന് ചെറിയ ഗ്ലാസിൽ ചായ ',
      ['കുടിക്കുന്നു', 'drink (from കുടിക്കുക, to drink)'],
      ', ',
      ['വർത്തമാനം പറയുന്നു', 'chat'],
      '. ദിവസത്തിലെ ഏറ്റവും മധുരമുള്ള നിമിഷമാണിത്.',
    ],
    reviewWord: 'വേണം',
    reviewSource: 'from your chaya order, 3 days ago',
    reviewMeaning: 'is wanted (used for “I’d like”)',
  },
  {
    ct: 'വഴി Directions',
    partner: 'സുനിത Sunitha',
    role: 'local resident',
    place: 'Kochi street',
    scenarioTitle: 'കൊച്ചിയിലെ തെരുവ് · Kochi',
    prompt: 'Where is the market?',
    hint: 'Start with the place: “മാർക്കറ്റ് എവിടെയാണ്?”',
    bank: ['മാർക്കറ്റ്', 'എവിടെയാണ്', 'ഞാൻ', 'പോകണം', 'ഇടത്', 'ചായ'],
    bankEn: ['market', 'where is', 'I', 'must go', 'left', 'tea'],
    correct: [0, 1],
    okTitle: 'നന്നായി! 🎉',
    okBody: 'Put the place first, then “എവിടെയാണ്?” — literally “market where-is?”',
    noBody: 'Name the place first, then ask “എവിടെയാണ്?”.',
    cultureCaption: 'Fort Kochi lanes · afternoon',
    cultureTitle: 'Landmarks beat street names',
    cultureBody:
      'In Kerala directions often use the nearest junction, temple, church or tea shop rather than street names. It is normal to ask two or three people to be sure.',
    culturePhrase: '“ഇവിടെ നിന്ന് എത്ര ദൂരം?” (ivide ninnu ethra dooram?) — “how far from here?”',
    milestone: 'You can now ask your way around town.',
    convo: [
      ['p', 'നമസ്കാരം! എന്തെങ്കിലും സഹായം വേണോ?', 'Hello! Do you need any help?'],
      ['u', 'അതെ, മാർക്കറ്റ് എവിടെയാണ്?', 'Great — “എവിടെയാണ്?” is the key question'],
      ['p', 'നേരെ പോയി രണ്ടാമത്തെ ജംഗ്ഷനിൽ വലത്തോട്ട് തിരിയുക.', 'Go straight, then turn right at the second junction.'],
      ['u', 'നന്ദി! അടുത്താണോ?', 'Nice — “അടുത്താണോ?” = is it near?'],
      ['p', 'അതെ, അഞ്ച് മിനിറ്റ് മതി.', 'Yes, five minutes is enough.'],
    ],
    debrief: [
      ['“ഇടത് / വലത്”', 'Left is “ഇടത്”, right is “വലത്” — add “-ഓട്ട്” for direction: “വലത്തോട്ട്” (to the right).'],
      ['Polite “നിങ്ങൾ”', 'With strangers use “നിങ്ങൾ” (formal you), not “നീ”.'],
    ],
    grammarMini: '… എവിടെയാണ്?',
    grammarTitle: '“… എവിടെയാണ്?” — asking where something is',
    grammarIntro: 'Put the place first, then “എവിടെയാണ്?”:',
    A: ['എവിടെ (evide)', '“where”', 'സ്റ്റേഷൻ എവിടെയാണ്?'],
    B: ['ആണ് (aanu)', '“is” — links two nouns', 'ഇത് മാർക്കറ്റ് ആണ്.'],
    clip: 'ഫോർട്ട് കൊച്ചിയിലൂടെ ഒരു നടത്തം',
    podcast: 'സുനിതയോടൊപ്പം വഴി തേടി — എപ്പിസോഡ് 5',
    article: 'കൊച്ചിയിൽ വഴി ചോദിക്കുമ്പോൾ',
    reader: [
      'കൊച്ചിയിൽ വഴി ചോദിക്കുന്നത് എളുപ്പമാണ്. ആളുകൾ എപ്പോഴും സഹായിക്കും. അവർ പറയും, “നേരെ പോയി ',
      ['വലത്തോട്ട്', 'to the right'],
      ' തിരിയുക.” അടുത്ത് തന്നെ ',
      ['മാർക്കറ്റ്', 'market'],
      ' ഉണ്ട്.',
    ],
    reviewWord: 'വലത്തോട്ട്',
    reviewSource: 'from your last direction request, 3 days ago',
    reviewMeaning: 'to the right',
  },
  {
    ct: 'കുടുംബം Family',
    partner: 'മീന Meena',
    role: 'friend',
    place: 'home',
    scenarioTitle: 'ഞങ്ങളുടെ വീട് · Thrissur',
    prompt: 'This is my father.',
    hint: 'Use “ഇത് എന്റെ … ആണ്” for introductions.',
    bank: ['ഇത്', 'എന്റെ', 'അച്ഛനാണ്', 'അമ്മ', 'സഹോദരി', 'ഉണ്ട്'],
    bankEn: ['this', 'my', 'is father', 'mother', 'sister', 'there is'],
    correct: [0, 1, 2],
    okTitle: 'അടിപൊളി! 🎉',
    okBody: '“അച്ഛനാണ്” joins “അച്ഛൻ” (father) and “ആണ്” (is) into one word.',
    noBody: 'Say “ഇത്” (this), then “എന്റെ” (my), then the person with “-ആണ്”.',
    cultureCaption: 'An Onam sadya in Thrissur · noon',
    cultureTitle: 'Family at the sadya',
    cultureBody:
      "At Onam, Kerala's harvest festival, families sit together on the floor for the 'sadya' — a feast of many dishes served on a banana leaf.",
    culturePhrase: '“അമ്മ” (amma) — “mother”, the first word every learner meets.',
    milestone: 'You can now introduce your family.',
    convo: [
      ['p', 'നമസ്കാരം! ഇത് ആരാണ്?', 'Hello! Who is this?'],
      ['u', 'ഇത് എന്റെ അച്ഛനാണ്.', 'Perfect — “അച്ഛനാണ്” = is father'],
      ['p', 'കൊള്ളാം! അമ്മ എവിടെയാണ്?', 'Lovely! And where is your mother?'],
      ['u', 'അമ്മ വീട്ടിലുണ്ട്.', 'Good — “വീട്ടിൽ” = at home'],
      ['p', 'എനിക്ക് അവരെ കാണണം.', "I'd love to meet her."],
    ],
    debrief: [
      ['“അച്ഛൻ” and “അമ്മ”', '“അച്ഛൻ” (father) and “അമ്മ” (mother) are the everyday words used by all.'],
      ['“ചേട്ടൻ” and “ചേച്ചി”', 'Older siblings get “ചേട്ടൻ” (elder brother) and “ചേച്ചി” (elder sister) — also used for non-relatives.'],
    ],
    grammarMini: 'ഇത് … ആണ്',
    grammarTitle: '“ഇത് … ആണ്” — introducing people',
    grammarIntro: 'Use “ഇത്” (this) and “ആണ്” (is):',
    A: ['ഇത് (ith)', '“this”', 'ഇത് എന്റെ അച്ഛനാണ്.'],
    B: ['ആണ് (aanu)', '“is” — often joins the noun: അച്ഛനാണ്', 'അത് എന്റെ അമ്മയാണ്.'],
    clip: 'ഞായറാഴ്ചയിലെ ഊണ്, എല്ലാവരും ഒരുമിച്ച്',
    podcast: 'മീനയോടൊപ്പം വീട്ടുവിശേഷങ്ങൾ — എപ്പിസോഡ് 6',
    article: 'എന്റെ കുടുംബം',
    reader: [
      'എന്റെ കുടുംബം വലുതാണ്. ഇത് എന്റെ ',
      ['അച്ഛൻ', 'father'],
      ' ആണ്, ഇത് എന്റെ ',
      ['അമ്മ', 'mother'],
      ' ആണ്. എനിക്ക് ഒരു ',
      ['സഹോദരി', 'sister'],
      ' ഉണ്ട്.',
    ],
    reviewWord: 'അച്ഛൻ',
    reviewSource: 'from your family introduction, 2 days ago',
    reviewMeaning: 'father',
  },
  {
    ct: 'ഹോട്ടൽ Hotel',
    partner: 'രാജേഷ് Rajesh',
    role: 'hotel receptionist',
    place: 'Kochi hotel',
    scenarioTitle: 'ഹോട്ടൽ · Kochi',
    prompt: 'I need a room for two nights.',
    hint: 'Say “രണ്ട് രാത്രിക്ക്” for “for two nights”.',
    bank: ['എനിക്ക്', 'രണ്ട്', 'രാത്രിക്ക്', 'ഒരു', 'മുറി', 'വേണം'],
    bankEn: ['to me', 'two', 'for nights', 'one / a', 'room', 'wanted'],
    correct: [0, 1, 2, 3, 4, 5],
    okTitle: 'ഗംഭീരം! 🎉',
    okBody: 'The ending “-ക്ക്” marks who or what something is for: “രാത്രിക്ക്” = for the night(s).',
    noBody: 'Order: “എനിക്ക്” + “രണ്ട് രാത്രിക്ക്” + “ഒരു മുറി” + “വേണം”.',
    cultureCaption: 'A homestay in Alleppey · check-in',
    cultureTitle: 'A welcome with a drink',
    cultureBody:
      'Kerala hotels and homestays often greet guests with a glass of tender-coconut water or hot tea. Breakfast might be appam with stew or puttu with kadala curry.',
    culturePhrase: '“മുറിയുടെ വാടക എത്രയാണ്?” (muriyude vaadaka ethrayaanu?) — “how much is the room?”',
    milestone: 'You can now check into a hotel.',
    convo: [
      ['p', 'നമസ്കാരം, സ്വാഗതം! എങ്ങനെ സഹായിക്കണം?', 'Welcome! How can I help?'],
      ['u', 'എനിക്ക് രണ്ട് രാത്രിക്ക് ഒരു മുറി വേണം.', 'Great — a clear, polite request'],
      ['p', 'തീർച്ചയായും. പ്രഭാതഭക്ഷണം വേണോ?', 'Certainly. Would you like breakfast?'],
      ['u', 'വേണം, ദയവായി.', 'Polite — “ദയവായി” = please'],
      ['p', 'ശരി, ഇതാ നിങ്ങളുടെ താക്കോൽ.', "All right, here's your key."],
    ],
    debrief: [
      ['“ദയവായി”', '“ദയവായി” is a polite “please”, used with strangers and in service settings.'],
      ['Numbers', '“രണ്ട്” (two) comes before the noun: “രണ്ട് രാത്രി”.'],
    ],
    grammarMini: '… -ക്ക്',
    grammarTitle: '“-ക്ക്” — “for / to”',
    grammarIntro: 'The ending “-ക്ക്” marks who or what something is for:',
    A: ['രാത്രിക്ക് (raathrikku)', '“for the night”', 'രണ്ട് രാത്രിക്ക്'],
    B: ['എനിക്ക് (enikku)', '“to / for me”', 'എനിക്ക് ഒരു മുറി വേണം.'],
    clip: 'ആലപ്പുഴയിലെ പ്രഭാതം',
    podcast: 'രാജേഷിനോടൊപ്പം ആതിഥ്യം — എപ്പിസോഡ് 7',
    article: 'ഹോട്ടലിലെ താമസം',
    reader: [
      'ഹോട്ടലിൽ ഞാൻ ഒരു ',
      ['മുറി', 'room'],
      ' എടുത്തു. അത് വൃത്തിയുള്ളതും ശാന്തവുമാണ്. ഞാൻ രണ്ട് ',
      ['രാത്രി', 'nights'],
      ' താമസിക്കും.',
    ],
    reviewWord: 'മുറി',
    reviewSource: 'from your hotel booking, 5 days ago',
    reviewMeaning: 'room',
  },
  {
    ct: 'ചന്ത Market',
    partner: 'ചേച്ചി Chechi',
    role: 'fruit vendor',
    place: 'Kochi market',
    scenarioTitle: 'ചന്ത · Kochi',
    prompt: 'How much is this?',
    hint: '“എത്രയാണ്?” is how you ask “how much is it?”.',
    bank: ['ഇതിന്', 'എത്രയാണ്', 'വില', 'കുറവ്', 'എനിക്ക്', 'രണ്ട്'],
    bankEn: ['for this', 'how much is it', 'price', 'less', 'to me', 'two'],
    correct: [0, 1],
    okTitle: 'കൊള്ളാം! 🎉',
    okBody: '“ഇതിന് എത്രയാണ്?” — literally “for-this how-much-is?”',
    noBody: 'Say “ഇതിന്” (for this), then “എത്രയാണ്?”.',
    cultureCaption: 'Broadway market, Kochi · morning',
    cultureTitle: 'Bargaining is a friendly chat',
    cultureBody:
      'In Indian markets the first price is rarely the last. Bargaining is friendly, with a smile — and walking away slowly often gets you the best price.',
    culturePhrase: '“കുറച്ച് കുറയ്ക്കാമോ?” (kurach kuraikkaamo?) — “could you reduce it a little?”',
    milestone: 'You can now shop and bargain.',
    convo: [
      ['p', 'വരൂ, വരൂ! പുതിയ വാഴപ്പഴം ഉണ്ട്.', 'Come, come! Fresh bananas!'],
      ['u', 'ഇതിന് എത്രയാണ്?', 'Good — short and natural'],
      ['p', 'ഒരു ഡസന് നാല്പത് രൂപ.', 'Forty rupees a dozen.'],
      ['u', 'കുറച്ച് കുറയ്ക്കാമോ?', 'Nice — “കുറയ്ക്കാമോ?” = can you reduce?'],
      ['p', 'ശരി, മുപ്പത്തഞ്ച് തരൂ.', 'Okay, give thirty-five.'],
    ],
    debrief: [
      ['Numbers', 'Malayalam numbers like “മുപ്പത്തഞ്ച്” (35) and “നാല്പത്” (40) are long — say them slowly.'],
      ['“-ഓ” for questions', 'Adding “-ഓ” turns a statement into a yes/no question: “കുറയ്ക്കാമോ?”'],
    ],
    grammarMini: '… എത്രയാണ്?',
    grammarTitle: '“എത്രയാണ്?” — asking the price',
    grammarIntro: 'Point to the item, then ask:',
    A: ['എത്ര (ethra)', '“how much”', 'ഇതിന് എത്രയാണ്?'],
    B: ['കുറയ്ക്കാമോ (kuraikkaamo)', '“can you reduce?”', 'കുറച്ച് കുറയ്ക്കാമോ?'],
    clip: 'ബ്രോഡ്‌വേയിലെ പ്രഭാതം',
    podcast: 'ചേച്ചിയോടൊപ്പം ചന്ത — എപ്പിസോഡ് 8',
    article: 'ആഴ്ച ചന്ത',
    reader: [
      'ചന്തയിൽ പുതിയ പഴങ്ങളും പച്ചക്കറികളും കിട്ടും. ഞാൻ കച്ചവടക്കാരിയോട് ചോദിച്ചു, “ഇതിന് ',
      ['എത്രയാണ്', 'how much is it'],
      '?” അവർ പറഞ്ഞു, “നാല്പത് രൂപ.” ഞാൻ കുറച്ച് ',
      ['കുറയ്ക്കാൻ', 'to reduce'],
      ' പറഞ്ഞു.',
    ],
    reviewWord: 'കുറയ്ക്കാമോ',
    reviewSource: 'from your haggling session, 1 day ago',
    reviewMeaning: 'can you reduce?',
  },
  {
    ct: 'അടിയന്തരം Emergency',
    partner: 'ഓപ്പറേറ്റർ Operator',
    role: 'emergency responder',
    place: 'helpline',
    scenarioTitle: 'ഹെൽപ്‌ലൈൻ · 112',
    prompt: 'Please call a doctor.',
    hint: '“വിളിക്കൂ” is the polite command: “please call”.',
    bank: ['ദയവായി', 'ഡോക്ടറെ', 'വിളിക്കൂ', 'സഹായം', 'എന്റെ', 'ചെയ്യൂ'],
    bankEn: ['please', 'the doctor', 'call', 'help', 'my', 'do'],
    correct: [0, 1, 2],
    okTitle: 'ഉത്തമം! 🎉',
    okBody: 'Polite commands end in “-ൂ”: “വിളിക്കൂ”, “സഹായിക്കൂ”, “വരൂ”.',
    noBody: 'Say “ദയവായി”, then who (“ഡോക്ടറെ”), then the command “വിളിക്കൂ”.',
    cultureCaption: 'An ambulance in Kochi',
    cultureTitle: '112 — one number for everything',
    cultureBody:
      "India's single emergency number is 112, which connects to police, fire and ambulance. Say your location first — a landmark helps most — then what has happened.",
    culturePhrase: '“സഹായിക്കൂ!” (sahaayikkoo!) — “help!”',
    milestone: 'You can now call for help in an emergency.',
    convo: [
      ['p', 'ഹലോ, എമർജൻസി സർവീസ്. എന്താണ് സംഭവിച്ചത്?', 'Hello, emergency service. What happened?'],
      ['u', 'സഹായിക്കൂ! അപകടം ഉണ്ടായി.', 'Clear — “അപകടം” = accident'],
      ['p', 'നിങ്ങൾ എവിടെയാണ്?', 'Where are you?'],
      ['u', 'ഞാൻ സ്റ്റേഷന് അടുത്താണ്.', 'Good — “അടുത്ത്” = near'],
      ['p', 'ശാന്തമായിരിക്കൂ, ആംബുലൻസ് വരുന്നുണ്ട്.', 'Stay calm, the ambulance is coming.'],
    ],
    debrief: [
      ['“ശാന്തമായിരിക്കൂ”', '“ശാന്തമായിരിക്കൂ” (stay calm) is what responders say — you will hear it.'],
      ['Say the place first', 'Name your location first: “ഞാൻ സ്റ്റേഷന് അടുത്താണ്.”'],
    ],
    grammarMini: 'വിളിക്കൂ / സഹായിക്കൂ',
    grammarTitle: 'Polite commands end in “-ൂ”',
    grammarIntro: 'Add “-ൂ” to the verb stem for a polite command:',
    A: ['വിളിക്കൂ (vilikkoo)', '“please call”', 'ഡോക്ടറെ വിളിക്കൂ.'],
    B: ['സഹായിക്കൂ (sahaayikkoo)', '“please help”', 'എന്നെ സഹായിക്കൂ.'],
    clip: '112 — ഒരു നമ്പർ, എല്ലാ സഹായവും',
    podcast: 'എമർജൻസി കോൾ — എപ്പിസോഡ് 9',
    article: 'അടിയന്തരഘട്ടത്തിൽ എന്ത് ചെയ്യണം',
    reader: [
      'അപകടം ഉണ്ടായാൽ പേടിക്കരുത്. ',
      ['112', 'the emergency number'],
      ' ൽ വിളിച്ച് പറയുക, “',
      ['സഹായിക്കൂ', 'help'],
      '!” ആംബുലൻസ് വേഗം എത്തും.',
    ],
    reviewWord: 'ആംബുലൻസ്',
    reviewSource: 'from your emergency call, 6 days ago',
    reviewMeaning: 'ambulance',
  },
];

export const malayalam = course(
  { name: 'Malayalam', code: 'ML', font: 'ml', locale: 'ml-IN', greeting: 'നമസ്കാരം, Maya', accent: 'Kerala (Kochi)' },
  chapters
);
