import { course, type ChapterInput } from './build';

const chapters: ChapterInput[] = [
  {
    ct: 'चहा Chai culture',
    partner: 'विजय Vijay',
    role: 'chai wala',
    place: 'Pune tea stall',
    scenarioTitle: 'चहाची टपरी · Pune',
    goalTitle: 'Build it: order chai',
    goalLine: 'Order chai and make small talk.',
    goalShort: 'order chai',
    scenarioSub: 'Roleplay · order chai & chat',
    prompt: "I'd like one tea.",
    hint: 'Why “मला … हवा आहे”?',
    bank: ['मला', 'एक', 'चहा', 'हवा आहे', 'पाणी', 'दोन'],
    bankEn: ['to me', 'one', 'tea', '(is) wanted', 'water', 'two'],
    correct: [0, 1, 2, 3],
    okTitle: 'छान! 🎉',
    okBody: '“मला … हवा आहे” is the natural “I’d like” — literally “to me … is wanted.” “हवा” changes with the thing wanted.',
    noBody: 'Start with “मला” (to me), then the number, the item, then “हवा आहे.”',
    cultureCaption: 'A chai tapri in Pune · morning',
    cultureTitle: "The tapri is the city's living room",
    cultureBody:
      'In Maharashtra, the roadside chai tapri is where friends meet, plans are made and news travels. Chai comes in small glasses, often with ginger (आलं), and a plate of vada pav is the usual companion.',
    culturePhrase: '“कितीला?” (kitila?) — “how much?”, the short everyday way to ask a price.',
    milestone: 'You can now order chai — and chat while it brews.',
    convo: [
      ['p', 'नमस्कार! काय देऊ?', 'Hello! What can I get you?'],
      ['u', 'मला एक चहा हवा आहे.', 'Nice — “मला … हवा आहे” is very natural'],
      ['p', 'आलं घालून की साधा?', 'With ginger, or plain?'],
      ['u', 'आलं घालून, धन्यवाद.', 'Perfect — “आलं घालून” = with ginger'],
      ['p', 'दहा रुपये झाले.', 'That comes to ten rupees.'],
    ],
    debrief: [
      ['“धन्यवाद” vs “आभारी आहे”', '“धन्यवाद” is the everyday thanks; “आभारी आहे” is more formal.'],
      ['The “ळ” sound', 'Marathi has a distinct retroflex “ळ”, as in “कळले” (understood) — curl the tongue back.'],
    ],
    grammarMini: 'मला … हवा आहे',
    grammarTitle: '“मला … हवा आहे” — how to say “I want”',
    grammarIntro: 'Marathi says “to me, X is wanted” — and “हवा” agrees with the thing wanted:',
    A: ['मला (mala)', '“to me” — the wanter', 'मला चहा हवा आहे.'],
    B: ['हवा / हवी / हवे (hava / havi / have)', '“wanted” — masculine / feminine / neuter', 'मला पाणी हवे आहे.'],
    clip: 'पुण्यातला चहा, माणसांसोबत',
    podcast: 'विजयसोबत चहा — भाग ४',
    article: 'चहाची छोटीशी परंपरा',
    reader: [
      'महाराष्ट्रात सकाळची सुरुवात बहुतेक वेळा एका गरम ',
      ['चहा', 'chai — tea'],
      'ने होते. लोक टपरीवर उभे राहून लहान कपातून चहा ',
      ['पितात', 'drink (they drink — from पिणे, to drink)'],
      ' आणि एकमेकांशी ',
      ['गप्पा मारतात', 'chat with each other'],
      '. हा दिवसाचा सर्वात छान क्षण आहे.',
    ],
    reviewWord: 'हवा',
    reviewSource: 'from your chai order, 3 days ago',
    reviewMeaning: 'wanted / needed (used for “I’d like”)',
  },
  {
    ct: 'दिशा Directions',
    partner: 'सुनीता Sunita',
    role: 'local resident',
    place: 'Pune street',
    scenarioTitle: 'पुण्याचा रस्ता · Pune',
    prompt: 'Where is the market?',
    hint: 'Start with the place: “बाजार कुठे आहे?”',
    bank: ['बाजार', 'कुठे', 'आहे', 'मी', 'जातो', 'डावीकडे'],
    bankEn: ['market', 'where', 'is', 'I', 'go', 'to the left'],
    correct: [0, 1, 2],
    okTitle: 'खूप छान! 🎉',
    okBody: 'Put the place first, then “कुठे आहे?” — literally “market where is?”',
    noBody: 'Name the place first, then ask “कुठे आहे?”.',
    cultureCaption: 'A lane near Laxmi Road, Pune · afternoon',
    cultureTitle: 'Landmarks beat street names',
    cultureBody:
      "In Indian cities people often give directions by landmarks — “after the temple, near the big banyan tree” — rather than street names. It's normal to ask two or three people to be sure.",
    culturePhrase: '“इथून किती लांब आहे?” (ithun kiti lamb aahe?) — “how far is it from here?”',
    milestone: 'You can now ask your way around town.',
    convo: [
      ['p', 'नमस्कार! मदत हवी आहे का?', 'Hello! Do you need help?'],
      ['u', 'हो, बाजार कुठे आहे?', 'Great — “कुठे आहे?” is the key question'],
      ['p', 'सरळ जा आणि दुसऱ्या चौकात उजवीकडे वळा.', 'Go straight and turn right at the second crossing.'],
      ['u', 'धन्यवाद! जवळ आहे का?', 'Nice — “जवळ आहे का?” = is it near?'],
      ['p', 'हो, पाच मिनिटांवर आहे.', "Yes, it's five minutes away."],
    ],
    debrief: [
      ['“डावीकडे / उजवीकडे”', 'Left is “डावीकडे”, right is “उजवीकडे” — note the shared ending “-कडे” (towards).'],
      ['Polite “आपण”', 'With strangers, “आपण” (you, formal) sounds more respectful than “तू”.'],
    ],
    grammarMini: '… कुठे आहे?',
    grammarTitle: '“… कुठे आहे?” — asking where something is',
    grammarIntro: 'Put the place first, then “कुठे आहे?”:',
    A: ['कुठे (kuthe)', '“where”', 'बाजार कुठे आहे?'],
    B: ['आहे (aahe)', '“is” — the present-tense “to be”', 'स्टेशन कुठे आहे?'],
    clip: 'पेठांमधून फेरफटका',
    podcast: 'सुनीतासोबत वाट शोधताना — भाग ५',
    article: 'पुण्यात रस्ता विचारताना',
    reader: [
      'पुण्यात रस्ता विचारणे सोपे आहे. लोक नेहमी मदत करतात. ते म्हणतात, “सरळ जा आणि ',
      ['उजवीकडे', 'to the right'],
      ' वळा.” जवळच ',
      ['बाजार', 'market'],
      ' आहे.',
    ],
    reviewWord: 'उजवीकडे',
    reviewSource: 'from your last direction request, 3 days ago',
    reviewMeaning: 'to the right',
  },
  {
    ct: 'कुटुंब Family',
    partner: 'मीना Meena',
    role: 'friend',
    place: 'home',
    scenarioTitle: 'आमचं घर · Pune',
    prompt: 'This is my father.',
    hint: 'Use “हे माझे … आहेत” for introductions.',
    bank: ['हे', 'माझे', 'वडील', 'आहेत', 'आई', 'बहीण'],
    bankEn: ['this', 'my', 'father', 'are (respectful)', 'mother', 'sister'],
    correct: [0, 1, 2, 3],
    okTitle: 'अप्रतिम! 🎉',
    okBody: '“आहेत” is the respectful plural — elders always take it, even when it is one person.',
    noBody: 'Say “हे” (this), then “माझे” (my), the person, and finish with “आहेत”.',
    cultureCaption: 'A family dinner in Nashik · evening',
    cultureTitle: 'Family is the first introduction',
    cultureBody:
      'In Maharashtra, introducing someone often starts with family — whose son or daughter they are, and where the family is from. Elders are addressed with respect, often as “काका” (uncle) or “काकू” (aunt) even when they are not relatives.',
    culturePhrase: '“आई” (aai) — “mother”, the word every Marathi learner meets first.',
    milestone: 'You can now introduce your family.',
    convo: [
      ['p', 'नमस्कार! हे कोण आहेत?', 'Hello! Who is this?'],
      ['u', 'हे माझे वडील आहेत.', 'Perfect — “आहेत” shows respect'],
      ['p', 'छान! आणि तुमची आई कुठे आहे?', 'Lovely! And where is your mother?'],
      ['u', 'ती घरी आहे.', 'Good — “ती” = she'],
      ['p', 'त्यांना भेटायला आवडेल.', "I'd love to meet her."],
    ],
    debrief: [
      ['“आई” and “बाबा”', '“आई” (mother) and “बाबा” (father) are the warm everyday words; “वडील” is more formal.'],
      ['Respectful plural', 'Elders take a plural verb — “आई आल्या” — even when it is one person.'],
    ],
    grammarMini: 'हे … आहेत',
    grammarTitle: '“हे … आहेत” — introducing people',
    grammarIntro: 'Use “हे” (this) and “आहेत” to show respect:',
    A: ['हे (he)', '“this”', 'हे माझे वडील आहेत.'],
    B: ['आहेत (aahet)', '“are” — respectful plural', 'त्या माझ्या आई आहेत.'],
    clip: 'रविवारचे जेवण, सगळे एकत्र',
    podcast: 'मीनासोबत घरच्या गोष्टी — भाग ६',
    article: 'माझे कुटुंब',
    reader: [
      'माझे कुटुंब मोठे आहे. हे माझे ',
      ['वडील', 'father'],
      ' आहेत आणि त्या माझ्या ',
      ['आई', 'mother'],
      ' आहेत. मला एक ',
      ['बहीण', 'sister'],
      ' आहे.',
    ],
    reviewWord: 'वडील',
    reviewSource: 'from your family introduction, 2 days ago',
    reviewMeaning: 'father',
  },
  {
    ct: 'हॉटेल Hotel',
    partner: 'राहुल Rahul',
    role: 'hotel receptionist',
    place: 'Pune hotel',
    scenarioTitle: 'हॉटेल · Pune',
    prompt: 'I need a room for two nights.',
    hint: '“खोली” is feminine, so it takes “हवी”.',
    bank: ['मला', 'दोन', 'रात्रींसाठी', 'खोली', 'हवी आहे', 'चहा'],
    bankEn: ['to me', 'two', 'for nights', 'room', 'wanted', 'tea'],
    correct: [0, 1, 2, 3, 4],
    okTitle: 'शाब्बास! 🎉',
    okBody: '“हवी” matches the feminine word “खोली” — the “wanted” word changes with the thing wanted.',
    noBody: 'Order: “मला” + number + “रात्रींसाठी” + “खोली” + “हवी आहे”.',
    cultureCaption: 'A small lodge in Kolhapur · check-in',
    cultureTitle: 'Hospitality comes with chai',
    cultureBody:
      "At many hotels and lodges in Maharashtra you'll be welcomed with a smile and often offered tea or water first. Asking the price and showing an ID at check-in is standard.",
    culturePhrase: '“खोली किती रुपयांना?” (kholi kiti rupayana?) — “how much is the room?”',
    milestone: 'You can now check into a hotel.',
    convo: [
      ['p', 'नमस्कार, आपले स्वागत आहे! कशी मदत करू?', 'Welcome! How can I help?'],
      ['u', 'मला दोन रात्रींसाठी खोली हवी आहे.', 'Great — “हवी” matches “खोली”'],
      ['p', 'नक्की. नाश्ता हवा आहे का?', 'Certainly. Would you like breakfast?'],
      ['u', 'हो, कृपया.', 'Polite — “कृपया” = please'],
      ['p', 'ठीक आहे, ही तुमची चावी.', 'All right, here is your key.'],
    ],
    debrief: [
      ['“कृपया”', '“कृपया” is a polite “please”, used with strangers and in service settings.'],
      ['Numbers', '“दोन” (two) comes before the noun: “दोन रात्री”.'],
    ],
    grammarMini: 'खोली हवी आहे',
    grammarTitle: 'Gender agreement with “हवा / हवी / हवे”',
    grammarIntro: '“Wanted” changes with the thing wanted:',
    A: ['हवी (havi)', '“wanted” — feminine things', 'मला खोली हवी आहे.'],
    B: ['हवा (hava)', '“wanted” — masculine things', 'मला चहा हवा आहे.'],
    clip: 'लॉजची सकाळ',
    podcast: 'राहुलसोबत पाहुणचार — भाग ७',
    article: 'हॉटेलमध्ये मुक्काम',
    reader: [
      'हॉटेलमध्ये मी ',
      ['खोली', 'room'],
      ' घेतली. ती स्वच्छ आणि शांत आहे. मी दोन ',
      ['रात्री', 'nights'],
      ' राहणार आहे.',
    ],
    reviewWord: 'खोली',
    reviewSource: 'from your hotel booking, 5 days ago',
    reviewMeaning: 'room',
  },
  {
    ct: 'बाजार Market',
    partner: 'काकू Kaku',
    role: 'fruit vendor',
    place: 'Pune market',
    scenarioTitle: 'मंडई · Pune',
    prompt: 'How much is this?',
    hint: '“कितीला?” is the everyday way to ask a price.',
    bank: ['हे', 'कितीला', 'आहे', 'स्वस्त', 'मला', 'दोन'],
    bankEn: ['this', 'for how much', 'is', 'cheap', 'to me', 'two'],
    correct: [0, 1, 2],
    okTitle: 'वा! 🎉',
    okBody: '“हे कितीला आहे?” is short and natural — literally “this for-how-much is?”',
    noBody: 'Point with “हे” (this), then ask “कितीला आहे?”.',
    cultureCaption: 'Mandai market, Pune · morning',
    cultureTitle: 'Bargaining is a conversation',
    cultureBody:
      'In Indian markets the first price is rarely the last. Bargaining is friendly, with a smile — and walking away slowly often gets you the best price.',
    culturePhrase: '“थोडे कमी करा” (thode kami kara) — “reduce it a little”.',
    milestone: 'You can now shop and bargain.',
    convo: [
      ['p', 'या, या! ताजी केळी आहेत.', 'Come, come! Fresh bananas!'],
      ['u', 'हे कितीला आहे?', 'Good — short and natural'],
      ['p', 'चाळीस रुपये डझन.', 'Forty rupees a dozen.'],
      ['u', 'थोडे कमी करा ना.', 'Nice — “कमी करा” = lower it'],
      ['p', 'ठीक आहे, पस्तीस द्या.', 'Okay, give thirty-five.'],
    ],
    debrief: [
      ['Numbers 30–40', 'Marathi numbers are irregular: “पस्तीस” (35), “चाळीस” (40) — worth memorising.'],
      ['“ना” softener', 'Adding “ना” makes a request friendlier: “कमी करा ना.”'],
    ],
    grammarMini: '… कितीला?',
    grammarTitle: '“कितीला?” — asking the price',
    grammarIntro: 'Point to the item, then ask:',
    A: ['कितीला (kitila)', '“for how much?”', 'हे कितीला आहे?'],
    B: ['कमी (kami)', '“less / lower”', 'थोडे कमी करा.'],
    clip: 'मंडईतली सकाळ',
    podcast: 'काकूंसोबत बाजार — भाग ८',
    article: 'आठवडी बाजार',
    reader: [
      'बाजारात ताजी फळे आणि भाज्या मिळतात. मी विक्रेत्याला विचारले, “हे ',
      ['कितीला', 'for how much'],
      ' आहे?” त्याने सांगितले, “चाळीस रुपये.” मी थोडे ',
      ['कमी', 'less'],
      ' करायला सांगितले.',
    ],
    reviewWord: 'कमी',
    reviewSource: 'from your haggling session, 1 day ago',
    reviewMeaning: 'less / lower',
  },
  {
    ct: 'आणीबाणी Emergency',
    partner: 'ऑपरेटर Operator',
    role: 'emergency responder',
    place: 'helpline',
    scenarioTitle: 'हेल्पलाइन · 112',
    prompt: 'Please call a doctor.',
    hint: '“बोलवा” is the polite command: “please call”.',
    bank: ['कृपया', 'डॉक्टरांना', 'बोलवा', 'मदत', 'माझे', 'करा'],
    bankEn: ['please', 'the doctor (to)', 'call', 'help', 'my', 'do'],
    correct: [0, 1, 2],
    okTitle: 'उत्तम! 🎉',
    okBody: 'Polite commands end in “-वा” / “-रा”: “बोलवा”, “करा”, “या”.',
    noBody: 'Say “कृपया”, then who (“डॉक्टरांना”), then the command “बोलवा”.',
    cultureCaption: 'An ambulance on a Mumbai road',
    cultureTitle: '112 — one number for everything',
    cultureBody:
      "India's single emergency number is 112, which connects to police, fire and ambulance. Say your location first — a landmark helps most — then what has happened.",
    culturePhrase: '“मदत करा!” (madat kara!) — “help!”',
    milestone: 'You can now call for help in an emergency.',
    convo: [
      ['p', 'हॅलो, आणीबाणी सेवा. काय झाले?', 'Hello, emergency service. What happened?'],
      ['u', 'मदत करा! अपघात झाला आहे.', 'Clear — “अपघात” = accident'],
      ['p', 'तुम्ही कुठे आहात?', 'Where are you?'],
      ['u', 'मी स्टेशनजवळ आहे.', 'Good — “जवळ” = near'],
      ['p', 'शांत राहा, रुग्णवाहिका येत आहे.', 'Stay calm, the ambulance is coming.'],
    ],
    debrief: [
      ['“शांत राहा”', '“शांत राहा” (stay calm) is what responders say — you will hear it.'],
      ['Say the place first', 'Name your location first: “मी स्टेशनजवळ आहे.”'],
    ],
    grammarMini: 'बोलवा / करा',
    grammarTitle: 'Polite commands',
    grammarIntro: 'Add a polite ending to the verb stem:',
    A: ['बोलवा (bolva)', '“please call” (polite)', 'डॉक्टरांना बोलवा.'],
    B: ['करा (kara)', '“please do”', 'मदत करा.'],
    clip: '११२ — एक नंबर, सगळी मदत',
    podcast: 'आणीबाणी कॉल — भाग ९',
    article: 'आणीबाणीत काय करावे',
    reader: [
      'अपघात झाला तर घाबरू नका. ',
      ['112', 'the emergency number'],
      ' वर फोन करा आणि सांगा, “',
      ['मदत करा', 'help'],
      '!” रुग्णवाहिका लवकर येते.',
    ],
    reviewWord: 'रुग्णवाहिका',
    reviewSource: 'from your emergency call, 6 days ago',
    reviewMeaning: 'ambulance',
  },
];

export const marathi = course(
  { name: 'Marathi', code: 'MR', font: 'hi', locale: 'mr-IN', greeting: 'नमस्कार, Maya', accent: 'Maharashtra (Pune)' },
  chapters
);
